/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package financiamentos;

import conn.ConexaoFB;
import conn.ConexaoMySQL;
import tools.ColorRender;
import tools.FiltrarTabela;
import tools.JNumberFormatField99;
import tools.ManipulaData;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import tabelasMySQL.CadBancos;
import tabelasMySQL.FinContratos;
import tabelasMySQL.FinModalidades;

/**
 *
 * @author ferna
 */
public class Fin_Contratos extends javax.swing.JInternalFrame {

    private javax.swing.text.MaskFormatter competencia, data;
    private String sql;
    private ConexaoFB cnfb = new ConexaoFB();
    private final ConexaoMySQL cn;
    private int var_consulta;
    private CadBancos banco;
    private FinModalidades modalidade;
    private FinContratos contrato;
    private String cnpjBanco;

    /**
     * Creates new form Fin_Contratos.
     *
     * @param conn
     */
    public Fin_Contratos(ConexaoMySQL conn) {
        try {
            competencia = new javax.swing.text.MaskFormatter("##/####");
            data = new javax.swing.text.MaskFormatter("##/##/####");
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        initComponents();
        this.cn = conn;
        contrato = new FinContratos(conn);
        montaTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPesquisar2 = new javax.swing.JFrame();
        jPanel10 = new javax.swing.JPanel();
        jTxtPesquisa_Multi2 = new javax.swing.JTextField();
        jBtnConfirmar = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTblConsulta_Multi = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jTxtCompetencia = new javax.swing.JFormattedTextField(competencia);
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTxtCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTxtIdBanco = new javax.swing.JTextField();
        jTxtNomeBanco = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTxtNumero = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTxtIdModalidade = new javax.swing.JTextField();
        jTxtNomeModalidade = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jTxtEmissao = new javax.swing.JFormattedTextField(data);
        jLabel6 = new javax.swing.JLabel();
        jTxtVencimento = new javax.swing.JFormattedTextField(data);
        jLabel7 = new javax.swing.JLabel();
        jCbJuros = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jCmbRecurso = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jTxtTaxa = new JNumberFormatField99(new DecimalFormat("#,##0.00"));
        jLabel10 = new javax.swing.JLabel();
        jCmbAmortiz = new javax.swing.JComboBox<>();
        jCbInverveniencia = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        jTxtValor = new JNumberFormatField99(new DecimalFormat("#,##0.00"));
        jLabel12 = new javax.swing.JLabel();
        jTxtObs = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTxtConta = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTxtDocumento = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTxtFornecedor = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTxtSubcontrato = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        jPesquisar2.setTitle("Pesquisar");
        jPesquisar2.setMinimumSize(new java.awt.Dimension(700, 400));

        jTxtPesquisa_Multi2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTxtPesquisa_Multi2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxtPesquisa_Multi2KeyReleased(evt);
            }
        });

        jBtnConfirmar.setText("Adicionar");
        jBtnConfirmar.setEnabled(false);
        jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmarActionPerformed(evt);
            }
        });

        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        jTblConsulta_Multi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTblConsulta_Multi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTblConsulta_Multi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTblConsulta_MultiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTblConsulta_MultiMouseEntered(evt);
            }
        });
        jScrollPane4.setViewportView(jTblConsulta_Multi);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addGap(0, 453, Short.MAX_VALUE)
                        .addComponent(jBtnCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnConfirmar))
                    .addComponent(jTxtPesquisa_Multi2)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTxtPesquisa_Multi2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnConfirmar)
                    .addComponent(jBtnCancelar))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPesquisar2Layout = new javax.swing.GroupLayout(jPesquisar2.getContentPane());
        jPesquisar2.getContentPane().setLayout(jPesquisar2Layout);
        jPesquisar2Layout.setHorizontalGroup(
            jPesquisar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPesquisar2Layout.setVerticalGroup(
            jPesquisar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setClosable(true);
        setTitle("Contratos de Financiamentos");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisa de Contratos"));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Importar");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Alterar");

        jLabel1.setText("Competência");

        jButton1.setText("Pesquisar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jRadioButton1)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton2)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTxtCompetencia, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jRadioButton1)
                .addComponent(jRadioButton2)
                .addComponent(jTxtCompetencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel1)
                .addComponent(jButton1))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Contrato"));

        jLabel2.setText("Código");

        jTxtCodigo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTxtCodigo.setEnabled(false);

        jLabel3.setText("Banco");

        jTxtIdBanco.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTxtIdBanco.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtIdBancoFocusLost(evt);
            }
        });

        jTxtNomeBanco.setEnabled(false);

        jButton2.setText("...");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Número");

        jTxtNumero.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTxtNumero.setEnabled(false);

        jLabel5.setText("Modalidade");

        jTxtIdModalidade.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTxtIdModalidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtIdModalidadeFocusLost(evt);
            }
        });

        jTxtNomeModalidade.setEnabled(false);

        jButton3.setText("...");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTxtEmissao.setEnabled(false);

        jLabel6.setText("Data de Emissão");

        jTxtVencimento.setEnabled(false);

        jLabel7.setText("Data de Vencimento");

        jCbJuros.setText("Juros Automático");

        jLabel8.setText("Recurso");

        jCmbRecurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LIVRE", "OBRIGATÓRIO" }));

        jLabel9.setText("Taxa Anual");

        jLabel10.setText("Amortização");

        jCmbAmortiz.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ANUAL", "MENSAL", "SEMESTRAL", "TRIMESTRAL" }));

        jCbInverveniencia.setText("Interveniência");

        jLabel11.setText("Valor");

        jTxtValor.setEnabled(false);

        jLabel12.setText("Observação");

        jTxtObs.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel13.setText("Conta");

        jTxtConta.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTxtConta.setEnabled(false);

        jLabel14.setText("Tipo Documento");

        jTxtDocumento.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTxtDocumento.setEnabled(false);

        jLabel15.setText("Fornecedor");

        jTxtFornecedor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTxtFornecedor.setEnabled(false);

        jLabel16.setText("Segmento");

        jTxtSubcontrato.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTxtIdBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtNomeBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTxtNumero))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTxtIdModalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtNomeModalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTxtEmissao, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTxtVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCmbRecurso, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCmbAmortiz, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTxtTaxa, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTxtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCbInverveniencia)
                    .addComponent(jCbJuros)))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTxtConta, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTxtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTxtFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTxtSubcontrato, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTxtObs))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTxtIdBanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtNomeBanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jLabel4)
                    .addComponent(jTxtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTxtIdModalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtNomeModalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3)
                    .addComponent(jTxtEmissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTxtVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jCbJuros))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jCmbRecurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtTaxa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jCmbAmortiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCbInverveniencia)
                    .addComponent(jLabel11)
                    .addComponent(jTxtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTxtConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jTxtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jTxtFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jTxtSubcontrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTxtObs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jButton4.setText("Gravar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Cancelar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton4)
            .addComponent(jButton5)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            String competencia = jTxtCompetencia.getText();
            boolean importar = jRadioButton1.isSelected();
            buscaContratos(importar, "01/" + competencia, tools.FormatNumbers.dateBrDefault(tools.ManipulaData.lastDay(competencia)));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        var_consulta = 9;
        incluiPesquisa();

    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
        var_consulta = 9;
        incluiPesquisa();
    }//GEN-LAST:event_jTable1KeyReleased

    private void jTxtPesquisa_Multi2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtPesquisa_Multi2KeyReleased
        new FiltrarTabela(jTblConsulta_Multi, jTxtPesquisa_Multi2.getText());
    }//GEN-LAST:event_jTxtPesquisa_Multi2KeyReleased

    private void jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmarActionPerformed
        incluiPesquisa();
        jPesquisar2.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jBtnConfirmarActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        jPesquisar2.setVisible(false);        // TODO add your handling code here:
        jPesquisar2.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jTblConsulta_MultiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblConsulta_MultiMouseClicked
        jBtnConfirmar.setEnabled(true);    // TODO add your handling code here:
    }//GEN-LAST:event_jTblConsulta_MultiMouseClicked

    private void jTblConsulta_MultiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblConsulta_MultiMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTblConsulta_MultiMouseEntered

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        var_consulta = 1;
        montaLista();
        jPesquisar2.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTxtIdBancoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtIdBancoFocusLost
        jTxtNomeBanco.setText("");
        try {
            int id = Integer.parseInt(jTxtIdBanco.getText());
            var_consulta = 11;
            incluiPesquisa();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jTxtIdBancoFocusLost

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        var_consulta = 2;
        montaLista();
        jPesquisar2.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTxtIdModalidadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtIdModalidadeFocusLost
        jTxtNomeModalidade.setText("");
        try {
            int id = Integer.parseInt(jTxtIdModalidade.getText());
            var_consulta = 22;
            incluiPesquisa();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jTxtIdModalidadeFocusLost

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (insereDados()) {
            if (contrato.gravaDados(jRadioButton1.isSelected())) {
                try {
                    JOptionPane.showMessageDialog(this, "Contrato gravado com sucesso.");
                    limpaCampos();
                    buscaContratos(jRadioButton1.isSelected(), "01/" + jTxtCompetencia.getText(), tools.FormatNumbers.dateBrDefault(tools.ManipulaData.lastDay(jTxtCompetencia.getText())));
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, e.getMessage());
                }
            } else {
                JOptionPane.showMessageDialog(this, "Não foi possível gravar os dados.");
            }
        }

    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnConfirmar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JCheckBox jCbInverveniencia;
    private javax.swing.JCheckBox jCbJuros;
    private javax.swing.JComboBox<String> jCmbAmortiz;
    private javax.swing.JComboBox<String> jCmbRecurso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JFrame jPesquisar2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTblConsulta_Multi;
    private javax.swing.JTextField jTxtCodigo;
    private static javax.swing.JTextField jTxtCompetencia;
    private javax.swing.JTextField jTxtConta;
    private javax.swing.JTextField jTxtDocumento;
    private static javax.swing.JTextField jTxtEmissao;
    private javax.swing.JTextField jTxtFornecedor;
    private javax.swing.JTextField jTxtIdBanco;
    private javax.swing.JTextField jTxtIdModalidade;
    private javax.swing.JTextField jTxtNomeBanco;
    private javax.swing.JTextField jTxtNomeModalidade;
    private javax.swing.JTextField jTxtNumero;
    private javax.swing.JTextField jTxtObs;
    private javax.swing.JTextField jTxtPesquisa_Multi2;
    private javax.swing.JTextField jTxtSubcontrato;
    private static javax.swing.JTextField jTxtTaxa;
    private static javax.swing.JTextField jTxtValor;
    private static javax.swing.JTextField jTxtVencimento;
    // End of variables declaration//GEN-END:variables

    private DefaultTableModel montaTabela() {
        DefaultTableModel lista = (DefaultTableModel) jTable1.getModel();

        lista.setColumnCount(0);
        lista.setRowCount(0);

        lista.addColumn("Lançamento");
        lista.addColumn("Número");
        lista.addColumn("Instituição");
        lista.addColumn("Liberação");
        lista.addColumn("Vencimento");
        lista.addColumn("Valor");
        lista.addColumn("conta");
        lista.addColumn("tipodoc");
        lista.addColumn("historico");
        lista.addColumn("fornecedor");
        lista.addColumn("cnpjbanco");

        jTable1.getColumnModel().getColumn(0).setMaxWidth(80);
        jTable1.getColumnModel().getColumn(0).setMinWidth(80);
        jTable1.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(80);
        jTable1.getTableHeader().getColumnModel().getColumn(0).setMinWidth(80);
        jTable1.getColumnModel().getColumn(1).setMaxWidth(100);
        jTable1.getColumnModel().getColumn(1).setMinWidth(100);
        jTable1.getTableHeader().getColumnModel().getColumn(1).setMaxWidth(100);
        jTable1.getTableHeader().getColumnModel().getColumn(1).setMinWidth(100);

        jTable1.getColumnModel().getColumn(3).setMaxWidth(80);
        jTable1.getColumnModel().getColumn(3).setMinWidth(80);
        jTable1.getTableHeader().getColumnModel().getColumn(3).setMaxWidth(80);
        jTable1.getTableHeader().getColumnModel().getColumn(3).setMinWidth(80);
        jTable1.getColumnModel().getColumn(4).setMaxWidth(80);
        jTable1.getColumnModel().getColumn(4).setMinWidth(80);
        jTable1.getTableHeader().getColumnModel().getColumn(4).setMaxWidth(80);
        jTable1.getTableHeader().getColumnModel().getColumn(4).setMinWidth(80);
        jTable1.getColumnModel().getColumn(5).setMaxWidth(100);
        jTable1.getColumnModel().getColumn(5).setMinWidth(100);
        jTable1.getTableHeader().getColumnModel().getColumn(5).setMaxWidth(100);
        jTable1.getTableHeader().getColumnModel().getColumn(5).setMinWidth(100);
        jTable1.getColumnModel().getColumn(6).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(6).setMinWidth(0);
        jTable1.getTableHeader().getColumnModel().getColumn(6).setMaxWidth(0);
        jTable1.getTableHeader().getColumnModel().getColumn(6).setMinWidth(0);
        jTable1.getColumnModel().getColumn(7).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(7).setMinWidth(0);
        jTable1.getTableHeader().getColumnModel().getColumn(7).setMaxWidth(0);
        jTable1.getTableHeader().getColumnModel().getColumn(7).setMinWidth(0);
        jTable1.getColumnModel().getColumn(8).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(8).setMinWidth(0);
        jTable1.getTableHeader().getColumnModel().getColumn(8).setMaxWidth(0);
        jTable1.getTableHeader().getColumnModel().getColumn(8).setMinWidth(0);
        jTable1.getColumnModel().getColumn(9).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(9).setMinWidth(0);
        jTable1.getTableHeader().getColumnModel().getColumn(9).setMaxWidth(0);
        jTable1.getTableHeader().getColumnModel().getColumn(9).setMinWidth(0);
        jTable1.getColumnModel().getColumn(10).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(10).setMinWidth(0);
        jTable1.getTableHeader().getColumnModel().getColumn(10).setMaxWidth(0);
        jTable1.getTableHeader().getColumnModel().getColumn(10).setMinWidth(0);

        jTable1.setDefaultRenderer(Object.class, new ColorRender());

        return lista;
    }

    private void buscaContratos(boolean importar, String dataInicial, String dataFinal) {

        DefaultTableModel lista = montaTabela();
        limpaCampos();

        if (importar) {
            ArrayList codigos = new ArrayList();
            sql = "SELECT id FROM fechamento.fin_contratos;";
            if (cn.iniciarTransacao()) {
                try {
                    cn.executeConsulta(sql);
                    while (cn.rs.next()) {
                        codigos.add(cn.rs.getString("id"));
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Erro ao preencher Lista.\n" + e);
                } finally {
                    cn.finalizarTransacao();
                }
            }
            System.out.println("Códigos existentes: " + codigos);

            sql = " select a.CODIGO,a.DOC,c.NOME,a.DT_EMISSAO,a.DT_VENC,SUM(b.VALOR) as valor,a.CONTA_FORNECEDOR,a.TIPODOC,a.HISTORICO,a.FORNECEDOR, left(c.CPF_CNPJ,8) as cnpjBanco "
                    + "from fin_contas_pagar a "
                    + "left join fin_contas_pagar_detalhe b on (b.empresa = a.empresa and b.codigo = a.codigo) "
                    + "left join cad_terceiros c on (c.empresa = a.empresa and c.codigo = a.fornecedor) "
                    + "where a.empresa = 1 and a.tipodoc in (30,33,47) "
                    + "and a.dt_emissao between '" + dataInicial.replace("/", ".") + "' "
                    + "and '" + dataFinal.replace("/", ".") + "' "
                    + "and b.planoconta != '6256' "
                    + "and b.codigo NOT IN (" + codigos.toString().replace("[", "").replace("]", "") + ") "
                    + "GROUP BY 1,2,3,4,5,7,8,9,10,11;";

            if (cnfb.conecta()) {
                try {
                    cnfb.executeConsulta(sql);
                    while (cnfb.rs.next()) {
                        lista.addRow(new String[]{
                            cnfb.rs.getString("codigo"),
                            cnfb.rs.getString("doc"),
                            cnfb.rs.getString("nome"),
                            tools.FormatNumbers.dateBrDefault(cnfb.rs.getDate("dt_emissao")),
                            tools.FormatNumbers.dateBrDefault(cnfb.rs.getDate("dt_venc")),
                            tools.FormatNumbers.numUsToBr(cnfb.rs.getDouble("valor")),
                            cnfb.rs.getString("conta_fornecedor"),
                            cnfb.rs.getString("tipodoc"),
                            cnfb.rs.getString("historico"),
                            cnfb.rs.getString("fornecedor"),
                            cnfb.rs.getString("cnpjBanco"),});
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                } finally {
                    cnfb.desconecta();
                }
            }

        } else {

            if (cn.iniciarTransacao()) {
                try {
                    sql = "select * from fechamento.fin_contratos a "
                            + "left join fechamento.cad_bancos b on (b.id = a.banco) "
                            + "where month(a.liberacao) = '" + tools.ManipulaData.getMonth(jTxtCompetencia.getText()) + "' "
                            + "and year(a.liberacao) = '" + tools.ManipulaData.getYear(jTxtCompetencia.getText()) + "';";
                    cn.executeConsulta(sql);
                    while (cn.rs.next()) {
                        lista.addRow(new String[]{
                            cn.rs.getString("id"),
                            cn.rs.getString("numero"),
                            cn.rs.getString("title"),
                            tools.FormatNumbers.dateBrDefault(cn.rs.getDate("liberacao")),
                            tools.FormatNumbers.dateBrDefault(cn.rs.getDate("vencimento")),
                            tools.FormatNumbers.numUsToBr(cn.rs.getDouble("valor")),
                            cn.rs.getString("conta"),
                            cn.rs.getString("tipodoc"),
                            cn.rs.getString("obs"),
                            cn.rs.getString("fornecedor"),
                            "0"
                        });
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                } finally {
                    cn.finalizarTransacao();
                }
            }

        }

    }

    private void limpaCampos() {
        jTxtCodigo.setText("");
        jTxtNumero.setText("");
        //jTxtEmissao.setText("");
        //jTxtVencimento.setText("");
        jTxtValor.setText("000");
        jTxtConta.setText("");
        jTxtDocumento.setText("");
        jTxtObs.setText("");
        jTxtFornecedor.setText("");

        jTxtIdBanco.setText("");
        jTxtNomeBanco.setText("");
        jTxtIdModalidade.setText("");
        jTxtNomeModalidade.setText("");

        jTxtTaxa.setText("0,00");
        jTxtEmissao.setText("  /  /    ");
        jTxtVencimento.setText("  /  /    ");

        jCbJuros.setSelected(false);
        jCbInverveniencia.setSelected(false);
    }

    private void incluiPesquisa() {
        int linha;

        switch (var_consulta) {

            case 1:
                linha = jTblConsulta_Multi.getSelectedRow();
                jTxtIdBanco.setText(jTblConsulta_Multi.getValueAt(linha, 0).toString());
                jTxtNomeBanco.setText(jTblConsulta_Multi.getValueAt(linha, 1).toString());

                break;

            case 11:
                banco = new CadBancos(false, jTxtIdBanco.getText(), cn);
                jTxtNomeBanco.setText(banco.getTitle());

                break;
            case 2:
                linha = jTblConsulta_Multi.getSelectedRow();
                jTxtIdModalidade.setText(jTblConsulta_Multi.getValueAt(linha, 0).toString());
                jTxtNomeModalidade.setText(jTblConsulta_Multi.getValueAt(linha, 1).toString());
                break;

            case 22:
                modalidade = new FinModalidades(Integer.parseInt(jTxtIdModalidade.getText()), cn);
                jTxtNomeModalidade.setText(modalidade.getDescricao());
                break;

            case 9:
                linha = jTable1.getSelectedRow();
                jTxtCodigo.setText(jTable1.getValueAt(linha, 0).toString());
                jTxtNumero.setText(jTable1.getValueAt(linha, 1).toString());
                jTxtEmissao.setText(jTable1.getValueAt(linha, 3).toString());
                jTxtVencimento.setText(jTable1.getValueAt(linha, 4).toString());
                jTxtValor.setText(jTable1.getValueAt(linha, 5).toString().replace(".", "").replace(",", ""));
                jTxtConta.setText(jTable1.getValueAt(linha, 6).toString());
                jTxtDocumento.setText(jTable1.getValueAt(linha, 7).toString());
                jTxtObs.setText(jTable1.getValueAt(linha, 8).toString());
                jTxtFornecedor.setText(jTable1.getValueAt(linha, 9).toString());
                cnpjBanco = jTable1.getValueAt(linha, 10).toString();

                if (jRadioButton1.isSelected()) {
                    banco = new CadBancos(true, cnpjBanco, cn);
                    jTxtIdBanco.setText(banco.getId());
                    jTxtNomeBanco.setText(banco.getTitle());
                } else {
                    sql = "SELECT * FROM fechamento.fin_contratos WHERE id = '" + jTxtCodigo.getText() + "';";
                    if (cn.iniciarTransacao()) {
                        try {
                            cn.executeConsulta(sql);
                            while (cn.rs.next()) {
                                jTxtIdBanco.setText(cn.rs.getString("banco"));
                                jTxtIdModalidade.setText(cn.rs.getString("modalidade"));
                                jCmbRecurso.setSelectedItem(cn.rs.getString("recurso"));
                                jCmbAmortiz.setSelectedItem(cn.rs.getString("amortizacao"));
                                jTxtTaxa.setText(tools.FormatNumbers.numUsToBr(cn.rs.getDouble("taxa")).replace(",", ""));
                                jCbJuros.setSelected(cn.rs.getBoolean("autoupd"));
                                jCbInverveniencia.setSelected(cn.rs.getBoolean("interveniencia"));
                                jTxtSubcontrato.setText(cn.rs.getString("subcontrato"));
                            }

                            var_consulta = 11;
                            incluiPesquisa();

                            var_consulta = 22;
                            incluiPesquisa();

                        } catch (Exception e) {
                            JOptionPane.showMessageDialog(null, e);
                        } finally {
                            cn.finalizarTransacao();
                        }
                    }
                }

                break;
        }

    }

    private void montaLista() {

        DefaultTableModel lista = (DefaultTableModel) jTblConsulta_Multi.getModel();

        lista.setRowCount(0);
        lista.setColumnCount(0);

        switch (var_consulta) {
            case 1:

                lista.addColumn("Código");
                lista.addColumn("Nome");
                lista.addColumn("Febraban");

                jTblConsulta_Multi.getColumnModel().getColumn(0).setMaxWidth(80);
                jTblConsulta_Multi.getColumnModel().getColumn(0).setMinWidth(80);
                jTblConsulta_Multi.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(80);
                jTblConsulta_Multi.getTableHeader().getColumnModel().getColumn(0).setMinWidth(80);
                jTblConsulta_Multi.getColumnModel().getColumn(2).setMaxWidth(80);
                jTblConsulta_Multi.getColumnModel().getColumn(2).setMinWidth(80);
                jTblConsulta_Multi.getTableHeader().getColumnModel().getColumn(2).setMaxWidth(80);
                jTblConsulta_Multi.getTableHeader().getColumnModel().getColumn(2).setMinWidth(80);

                sql = "SELECT * FROM cad_bancos ORDER BY title;";
                if (cn.iniciarTransacao()) {
                    try {
                        cn.executeConsulta(sql);
                        while (cn.rs.next()) {
                            lista.addRow(new String[]{
                                cn.rs.getString("id"),
                                cn.rs.getString("title"),
                                cn.rs.getString("code")
                            });
                        }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    } finally {
                        cn.finalizarTransacao();
                    }
                }

                break;

            case 2:
                lista.addColumn("Código");
                lista.addColumn("Descrição");

                jTblConsulta_Multi.getColumnModel().getColumn(0).setMaxWidth(80);
                jTblConsulta_Multi.getColumnModel().getColumn(0).setMinWidth(80);
                jTblConsulta_Multi.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(80);
                jTblConsulta_Multi.getTableHeader().getColumnModel().getColumn(0).setMinWidth(80);

                sql = "SELECT * FROM fin_modalidades ORDER BY descricao;";
                if (cn.iniciarTransacao()) {
                    try {
                        cn.executeConsulta(sql);
                        while (cn.rs.next()) {
                            lista.addRow(new String[]{
                                cn.rs.getString("id"),
                                cn.rs.getString("descricao")
                            });
                        }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    } finally {
                        cn.finalizarTransacao();
                    }
                }

                break;
        }

        jTblConsulta_Multi.setDefaultRenderer(Object.class, new ColorRender());
    }

    private boolean insereDados() {

        if ("".equals(jTxtSubcontrato.getText())) {
            jTxtSubcontrato.setText("0");
        }

        boolean resposta = false;
        try {
            contrato.setAmortizacao(jCmbAmortiz.getSelectedItem().toString());
            contrato.setAutoupd(jCbJuros.isSelected());
            contrato.setBanco(Integer.parseInt(jTxtIdBanco.getText()));
            contrato.setConta(Integer.parseInt(jTxtConta.getText()));
            contrato.setId(Integer.parseInt(jTxtCodigo.getText()));
            contrato.setInterveniencia(jCbInverveniencia.isSelected());
            contrato.setLiberacao(tools.ManipulaData.parseBrToDate(jTxtEmissao.getText()));
            contrato.setVencimento(tools.ManipulaData.parseBrToDate(jTxtVencimento.getText()));
            contrato.setLiquidado(false);
            contrato.setModalidade(Integer.parseInt(jTxtIdModalidade.getText()));
            contrato.setNumero(jTxtNumero.getText());
            contrato.setObs(jTxtObs.getText());
            contrato.setRecurso(jCmbRecurso.getSelectedItem().toString());
            contrato.setTaxa(Double.parseDouble(jTxtTaxa.getText().replace(".", "").replace(",", ".")));
            contrato.setValor(Double.parseDouble(jTxtValor.getText().replace(".", "").replace(",", ".")));
            contrato.setFornecedor(Integer.parseInt(jTxtFornecedor.getText()));
            contrato.setSubcontrato(Integer.parseInt(jTxtSubcontrato.getText()));
            contrato.setDocumento(jTxtDocumento.getText());

            resposta = true;
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Não foi possível converter algum valor.\n" + ex);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao inserir dados. \n" + e);
            Logger.getLogger(Fin_Contratos.class.getName()).log(Level.SEVERE, null, e);
        }

        return resposta;
    }

//    public static void main(String[] args) {
//        TelaPrincipal tp = new TelaPrincipal();
//        Fin_Contratos contrato = new Fin_Contratos();
//        tp.dispose();
//        contrato.buscaContratos(false, "01/01/2017", "30/06/2017");
//    }
}
