/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package financiamentos;

import conn.ConexaoMySQL;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author ferna
 */
public class IntFrm_Financ_Garantias extends javax.swing.JInternalFrame {

    private final ConexaoMySQL cn;
    private String sql;
    private boolean var_gravar = true;
    private MaskFormatter data;
    private int var_consulta;

    /**
     * Creates new form IntFrm_Financ_Garantias
     */
    public IntFrm_Financ_Garantias(conn.ConexaoMySQL conn) {
        try {
            data = new javax.swing.text.MaskFormatter("##/##/####");
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

        this.cn = conn;

        initComponents();

        montaTabelaContratos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTxtIdBem = new javax.swing.JTextField();
        jTxtNomeBem = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTxtGrau = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTxtLocalReg = new javax.swing.JTextField();
        jTxtQtd = new tools.JNumberFormatField99(tools.MascaraTextField.numeroBR());
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTxtDtBx = new javax.swing.JFormattedTextField(data);
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setClosable(true);
        setTitle("Garantias");

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Garantias"));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Bem", "Grau", "Local", "Baixa Automatca", "Data Baixa", "Quantidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(0);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(0);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
            jTable1.getColumnModel().getColumn(2).setMinWidth(40);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(40);
            jTable1.getColumnModel().getColumn(2).setMaxWidth(40);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setMinWidth(0);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(0);
            jTable1.getColumnModel().getColumn(4).setMaxWidth(0);
            jTable1.getColumnModel().getColumn(5).setMinWidth(80);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(80);
            jTable1.getColumnModel().getColumn(5).setMaxWidth(80);
            jTable1.getColumnModel().getColumn(6).setMinWidth(80);
            jTable1.getColumnModel().getColumn(6).setPreferredWidth(80);
            jTable1.getColumnModel().getColumn(6).setMaxWidth(80);
        }

        jLabel1.setText("Bem");

        jTxtIdBem.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtIdBemFocusLost(evt);
            }
        });

        jTxtNomeBem.setEnabled(false);

        jButton1.setText("...");

        jLabel2.setText("Grau");

        jLabel3.setText("Local Registro");

        jLabel4.setText("Quantidade");

        jLabel5.setText("Data Baixa");

        jCheckBox1.setText("Baixa Automática");

        jButton2.setText("Gravar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Excluir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Limpar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtIdBem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtNomeBem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtQtd))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtGrau, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtLocalReg)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jCheckBox1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtDtBx, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxtIdBem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtNomeBem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTxtGrau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTxtLocalReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTxtQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTxtDtBx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder("Contratos"));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "id", "Contrato", "Banco"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.getTableHeader().setReorderingAllowed(false);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jTable2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable2KeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setMinWidth(0);
            jTable2.getColumnModel().getColumn(0).setPreferredWidth(0);
            jTable2.getColumnModel().getColumn(0).setMaxWidth(0);
            jTable2.getColumnModel().getColumn(1).setMinWidth(90);
            jTable2.getColumnModel().getColumn(1).setPreferredWidth(90);
            jTable2.getColumnModel().getColumn(1).setMaxWidth(90);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        saveData();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        tools.ClearFields.ClearFields(jPanel2);
        montaTabelaGarantias();
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (var_gravar == false) {
            try {
                sql = "DELETE FROM fechamento.fin_contratos_garantias "
                        + "where id = '" + jTable2.getValueAt(jTable2.getSelectedRow(), 0).toString() + "' and "
                        + "id_bem = '" + jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString() + "';";
                cn.iniciarTransacao();
                cn.executeAtualizacao(sql);
                tools.ClearFields.ClearFields(jPanel2);
            } catch (Exception e) {
                tools.DefaultMsg.errorMsg(e.getMessage());
            } finally {
                cn.finalizarTransacao();
                montaTabelaGarantias();
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        tools.ClearFields.ClearFields(jPanel2);
        jTxtIdBem.setEnabled(true);
        var_gravar = true;
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        mostraDadosGarantias();
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTxtIdBemFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtIdBemFocusLost
        if (!jTxtIdBem.getText().equals("")) {
            var_consulta = 1;
            incluiPesquisa();
        } else {
            jTxtNomeBem.setText("");
        }
    }//GEN-LAST:event_jTxtIdBemFocusLost

    private void jTable2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable2KeyReleased
        atualizaPelaSeta(jTable2, evt);
    }//GEN-LAST:event_jTable2KeyReleased

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
        atualizaPelaSeta(jTable1, evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1KeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTxtDtBx;
    private javax.swing.JTextField jTxtGrau;
    private javax.swing.JTextField jTxtIdBem;
    private javax.swing.JTextField jTxtLocalReg;
    private javax.swing.JTextField jTxtNomeBem;
    private javax.swing.JTextField jTxtQtd;
    // End of variables declaration//GEN-END:variables

    private void montaTabelaContratos() {
        DefaultTableModel lista = (DefaultTableModel) jTable2.getModel();
        lista.setRowCount(0);
        jTable2.setDefaultRenderer(Object.class, new tools.ColorRender());

        try {
            sql = "SELECT "
                    + "min(c.id) as id, "
                    + "c.numero, "
                    + "b.title as banco "
                    + "FROM fechamento.fin_contratos c "
                    + "left join fechamento.cad_bancos b on b.id = c.banco "
                    + "group by c.numero "
                    + "order by b.title, c.numero;";
            cn.iniciarTransacao();
            cn.executeConsulta(sql);
            while (cn.rs.next()) {
                lista.addRow(new Object[]{
                    cn.rs.getString("id"),
                    cn.rs.getString("numero"),
                    cn.rs.getString("banco")
                });
            }

        } catch (Exception e) {
            tools.DefaultMsg.errorMsg(e.getMessage());
        } finally {
            cn.finalizarTransacao();
        }

    }

    private void saveData() {

        try {
            if (var_gravar) {
                sql = ("INSERT INTO fechamento.fin_contratos_garantias (id, id_bem, "
                        + "grau, local_registro, dt_baixa, quantidade, bx_autom) VALUES ( '"
                        + jTable2.getValueAt(jTable2.getSelectedRow(), 0).toString() + "','"
                        + jTxtIdBem.getText() + "','" + jTxtGrau.getText() + "','"
                        + jTxtLocalReg.getText() + "','"
                        + tools.ManipulaData.dateUSstr(jTxtDtBx.getText()) + "','"
                        + jTxtQtd.getText().replace(".", "").replace(",", ".") + "',"
                        + jCheckBox1.isSelected() + ");").replace("'null'", "null");
            } else {
                sql = ("UPDATE fechamento.fin_contratos_garantias SET "
                        + "grau = '" + jTxtGrau.getText() + "',"
                        + "local_registro = '" + jTxtLocalReg.getText() + "',"
                        + "dt_baixa = '" + tools.ManipulaData.dateUSstr(jTxtDtBx.getText()) + "',"
                        + "quantidade = '" + jTxtQtd.getText().replace(".", "").replace(",", ".") + "',"
                        + "bx_autom = " + jCheckBox1.isSelected() + " "
                        + "where id = '" + jTable2.getValueAt(jTable2.getSelectedRow(), 0).toString() + "' and "
                        + "id_bem = '" + jTxtIdBem.getText() + "';").replace("'null'", "null");

            }
            cn.iniciarTransacao();
            cn.executeAtualizacao(sql);

            tools.ClearFields.ClearFields(jPanel2);

            var_gravar = true;

        } catch (Exception e) {
            tools.DefaultMsg.errorMsg(e.getMessage());
        } finally {
            cn.finalizarTransacao();
            montaTabelaGarantias();
        }
    }

    private void montaTabelaGarantias() {

        var_gravar = true;

        jTxtIdBem.setEnabled(true);

        DefaultTableModel lista = (DefaultTableModel) jTable1.getModel();
        lista.setRowCount(0);
        jTable1.setDefaultRenderer(Object.class, new tools.ColorRender());

        try {
            sql = "select g.*, b.nome "
                    + "from fechamento.fin_contratos_garantias g "
                    + "left join fechamento.cad_bens b on b.id = g.id_bem "
                    + "where g.id = '" + jTable2.getValueAt(jTable2.getSelectedRow(), 0).toString() + "';";
            cn.iniciarTransacao();
            cn.executeConsulta(sql);
            while (cn.rs.next()) {
                lista.addRow(new Object[]{
                    cn.rs.getString("id_bem"),
                    cn.rs.getString("nome"),
                    cn.rs.getString("grau"),
                    cn.rs.getString("local_registro"),
                    cn.rs.getBoolean("bx_autom"),
                    tools.ManipulaData.dateBRstr(cn.rs.getDate("dt_baixa")),
                    tools.FormatNumbers.numUsToBr(cn.rs.getDouble("quantidade"))
                });
            }
        } catch (Exception e) {
            tools.DefaultMsg.errorMsg(e.getMessage());
        } finally {
            cn.finalizarTransacao();
        }
    }

    private void mostraDadosGarantias() {

        jTxtIdBem.setEnabled(false);

        int linha = jTable1.getSelectedRow();

        jTxtIdBem.setText(jTable1.getValueAt(linha, 0).toString());
        jTxtNomeBem.setText(jTable1.getValueAt(linha, 1).toString());
        jTxtGrau.setText(jTable1.getValueAt(linha, 2).toString());
        jTxtLocalReg.setText(jTable1.getValueAt(linha, 3).toString());
        jTxtQtd.setText(jTable1.getValueAt(linha, 6).toString());
        try {
            jCheckBox1.setSelected(Boolean.parseBoolean(jTable1.getValueAt(linha, 4).toString()));

            tools.ManipulaData.parseBrToDate(jTable1.getValueAt(linha, 5).toString());

            jTxtDtBx.setText(jTable1.getValueAt(linha, 5).toString());
        } catch (Exception e) {
            jTxtDtBx.setText("");
        }

        var_gravar = false;
    }

    private void incluiPesquisa() {
        switch (var_consulta) {
            case 1:
                try {
                    sql = "select * from fechamento.cad_bens "
                            + "where id = '" + jTxtIdBem.getText() + "';";
                    cn.iniciarTransacao();
                    cn.executeConsulta(sql);
                    while (cn.rs.next()) {
                        jTxtNomeBem.setText(cn.rs.getString("nome"));
                    }
                } catch (Exception e) {
                    jTxtNomeBem.setText("");
                } finally {
                    cn.finalizarTransacao();
                }
                break;
        }
    }

    private void atualizaPelaSeta(JTable tbl, KeyEvent evt) {
        if (evt.getKeyCode() == KeyEvent.VK_UP
                | evt.getKeyCode() == KeyEvent.VK_DOWN) {

            if (tbl.equals(jTable1)) {
                mostraDadosGarantias();
            } else {
                montaTabelaGarantias();
            }

        }
    }
}
