/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dominiosistemas;

import com.sun.glass.events.KeyEvent;
import conn.ConexaoFB;
import conn.ConexaoMySQL;
import tools.ColorRender;
import tools.FiltrarTabela;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;
import view.TelaPrincipal;

/**
 *
 * @author luiz.barcellos
 */
public class Exporta_DomSis extends javax.swing.JInternalFrame {

    private int var_consulta;
    private final ConexaoMySQL cn;
    private final ConexaoFB cnfb = new ConexaoFB();
    private MaskFormatter data;
    private String id;
    private DateFormat dateIn = new SimpleDateFormat("dd/MM/yyyy");
    private DateFormat dateAno = new SimpleDateFormat("01/01/yyyy");
    private TelaPrincipal telaPrincipal;

    /**
     * Creates new form Exporta_DomSis
     *
     * @param x
     */
    public Exporta_DomSis(JFrame x) {

        try {
            telaPrincipal = (TelaPrincipal) x;
            data = new javax.swing.text.MaskFormatter("##/##/####");
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

        this.cn = telaPrincipal.cn;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPesquisar = new javax.swing.JFrame();
        jPanel4 = new javax.swing.JPanel();
        jTxtPesquisa_Multi = new javax.swing.JTextField();
        jBtnConfirmar = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTblConsulta_Multi = new javax.swing.JTable();
        jSeletor = new javax.swing.JFileChooser();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTxtId = new javax.swing.JTextField();
        jTxtNome = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jTxtDti = new javax.swing.JFormattedTextField(data);
        jLabel2 = new javax.swing.JLabel();
        jTxtDtf = new javax.swing.JFormattedTextField(data);
        jLabel3 = new javax.swing.JLabel();
        jCBClientes = new javax.swing.JCheckBox();
        jCBFornecedores = new javax.swing.JCheckBox();
        jCBProdutos = new javax.swing.JCheckBox();
        jCBNotasEntrada = new javax.swing.JCheckBox();
        jCBNotasSaida = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jTxtCaminho = new javax.swing.JTextField();
        jCBPlanoContas = new javax.swing.JCheckBox();
        jCBNotasAnteriores = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();

        jPesquisar.setTitle("Pesquisar");
        jPesquisar.setMinimumSize(new java.awt.Dimension(700, 400));

        jTxtPesquisa_Multi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTxtPesquisa_Multi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtPesquisa_MultiKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxtPesquisa_MultiKeyReleased(evt);
            }
        });

        jBtnConfirmar.setText("Adicionar");
        jBtnConfirmar.setEnabled(false);
        jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmarActionPerformed(evt);
            }
        });

        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        jTblConsulta_Multi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTblConsulta_Multi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTblConsulta_Multi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTblConsulta_MultiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTblConsulta_MultiMouseEntered(evt);
            }
        });
        jScrollPane4.setViewportView(jTblConsulta_Multi);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 453, Short.MAX_VALUE)
                        .addComponent(jBtnCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnConfirmar))
                    .addComponent(jTxtPesquisa_Multi)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTxtPesquisa_Multi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnConfirmar)
                    .addComponent(jBtnCancelar))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPesquisarLayout = new javax.swing.GroupLayout(jPesquisar.getContentPane());
        jPesquisar.getContentPane().setLayout(jPesquisarLayout);
        jPesquisarLayout.setHorizontalGroup(
            jPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPesquisarLayout.setVerticalGroup(
            jPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jSeletor.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        jSeletor.setCurrentDirectory(new java.io.File("c:\\"));
            jSeletor.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

            setClosable(true);
            setTitle("Geração de Arquivo para Domínio Sistemas");

            jLabel1.setText("Pessoa");

            jTxtId.addFocusListener(new java.awt.event.FocusAdapter() {
                public void focusGained(java.awt.event.FocusEvent evt) {
                    jTxtIdFocusGained(evt);
                }
                public void focusLost(java.awt.event.FocusEvent evt) {
                    jTxtIdFocusLost(evt);
                }
            });
            jTxtId.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyPressed(java.awt.event.KeyEvent evt) {
                    jTxtIdKeyPressed(evt);
                }
            });

            jTxtNome.setEnabled(false);

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jTxtId, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jTxtNome))
            );
            jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            );

            jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Parâmetros de Exportação"));

            jTxtDti.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyPressed(java.awt.event.KeyEvent evt) {
                    jTxtDtiKeyPressed(evt);
                }
            });

            jLabel2.setText("Período Inicial");

            jTxtDtf.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyPressed(java.awt.event.KeyEvent evt) {
                    jTxtDtfKeyPressed(evt);
                }
            });

            jLabel3.setText("Período Final");

            jCBClientes.setText("Clientes");

            jCBFornecedores.setText("Fornecedores");

            jCBProdutos.setText("Produtos");

            jCBNotasEntrada.setText("Notas de Entrada");

            jCBNotasSaida.setText("Notas de Saída");

            jLabel4.setText("Local");

            jTxtCaminho.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyPressed(java.awt.event.KeyEvent evt) {
                    jTxtCaminhoKeyPressed(evt);
                }
            });

            jCBPlanoContas.setText("Plano de Contas");

            jCBNotasAnteriores.setText("Notas Anteriores");
            jCBNotasAnteriores.setToolTipText("Consulta todas as notas fiscas de entrada e saída emitidas anteriormente, mas quitadas nas datas informadas.");

            javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
            jPanel2.setLayout(jPanel2Layout);
            jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTxtDti, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTxtDtf, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jCBNotasEntrada)
                                .addComponent(jCBClientes)
                                .addComponent(jCBNotasAnteriores))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jCBFornecedores)
                                .addComponent(jCBNotasSaida))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jCBProdutos)
                                .addComponent(jCBPlanoContas))))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(jLabel4)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jTxtCaminho))
            );
            jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jTxtDti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTxtDtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCBClientes)
                        .addComponent(jCBFornecedores)
                        .addComponent(jCBProdutos))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCBNotasEntrada)
                        .addComponent(jCBNotasSaida)
                        .addComponent(jCBPlanoContas))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jCBNotasAnteriores)
                    .addGap(18, 18, 18)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jTxtCaminho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            );

            jButton1.setText("Exportar");
            jButton1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
                }
            });

            jButton2.setText("Cancelar");
            jButton2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton2ActionPerformed(evt);
                }
            });

            buttonGroup1.add(jRadioButton1);
            jRadioButton1.setSelected(true);
            jRadioButton1.setText("Cooper");

            buttonGroup1.add(jRadioButton2);
            jRadioButton2.setText("TRR");

            javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
            jPanel3.setLayout(jPanel3Layout);
            jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addComponent(jRadioButton1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jRadioButton2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
            );
            jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jButton1)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
            );

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap())
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void jTxtPesquisa_MultiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtPesquisa_MultiKeyReleased
        new FiltrarTabela(jTblConsulta_Multi, jTxtPesquisa_Multi.getText());
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtPesquisa_MultiKeyReleased

    private void jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmarActionPerformed
        incluiPesquisa();
        jPesquisar.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jBtnConfirmarActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        jPesquisar.setVisible(false);        // TODO add your handling code here:
        jPesquisar.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jTblConsulta_MultiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblConsulta_MultiMouseClicked
        jBtnConfirmar.setEnabled(true);    // TODO add your handling code here:
    }//GEN-LAST:event_jTblConsulta_MultiMouseClicked

    private void jTblConsulta_MultiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblConsulta_MultiMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTblConsulta_MultiMouseEntered

    private void jTxtIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtIdKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_F2) {
            var_consulta = 1;
            jPesquisar.setVisible(true);
            montaLista();
        }
    }//GEN-LAST:event_jTxtIdKeyPressed

    private void jTxtPesquisa_MultiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtPesquisa_MultiKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTblConsulta_Multi.setRowSelectionInterval(0, 0);

            incluiPesquisa();
            jPesquisar.setVisible(false);
        }

    }//GEN-LAST:event_jTxtPesquisa_MultiKeyPressed

    private void jTxtIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtIdFocusLost
        if (!jTxtId.getText().equals("")
                && !id.equals(jTxtId.getText())) {
            var_consulta = 2;
            jTxtNome.setText("");
            incluiPesquisa();
        } else {
            jTxtNome.setText("");
        }
    }//GEN-LAST:event_jTxtIdFocusLost

    private void jTxtIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtIdFocusGained
        id = jTxtId.getText();        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtIdFocusGained

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        final int x;

        if (jRadioButton1.isSelected()) {
            x = 1;
        } else {
            x = 2;
        }
        
        final JInternalFrame tela = this;
        
        new Thread() {
            public void run() {
                try {
                    
                    tela.setVisible(false);
                    //tela.setFocusable(false);
                    
                    new LimberExportaDados(cn, jCBPlanoContas.isSelected(),
                            jCBClientes.isSelected(), jCBFornecedores.isSelected(),
                            jCBProdutos.isSelected(), jCBNotasEntrada.isSelected(),
                            jCBNotasSaida.isSelected(), jCBNotasAnteriores.isSelected(), jTxtDti.getText().replace("/", "."),
                            jTxtDtf.getText().replace("/", "."), jTxtId.getText(),
                            jTxtCaminho.getText(), x);

                    JOptionPane.showMessageDialog(null, "Exportação executada com sucesso.");
                    

                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                } finally {
                    //tela.setFocusable(true);
                    tela.setVisible(true);
                }
            }
        }.start();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTxtCaminhoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtCaminhoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_F2) {
            int returnVal = jSeletor.showOpenDialog(this);
            if (returnVal == jSeletor.APPROVE_OPTION) {
                try {
                    jTxtCaminho.setText(jSeletor.getCurrentDirectory().toString());
                } catch (Exception ex) {
                    System.out.println("Não foi possível definir o caminho para salvar.");
                }
            } else {
                System.out.println("File access cancelled by user.");
            }
        }
    }//GEN-LAST:event_jTxtCaminhoKeyPressed

    private void jTxtDtfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtDtfKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            jTxtDtf.setText(dateIn.format(new Date()));
        }

// TODO add your handling code here:
    }//GEN-LAST:event_jTxtDtfKeyPressed

    private void jTxtDtiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtDtiKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            jTxtDti.setText(dateAno.format(new Date()));
        }
    }//GEN-LAST:event_jTxtDtiKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnConfirmar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCBClientes;
    private javax.swing.JCheckBox jCBFornecedores;
    private javax.swing.JCheckBox jCBNotasAnteriores;
    private javax.swing.JCheckBox jCBNotasEntrada;
    private javax.swing.JCheckBox jCBNotasSaida;
    private javax.swing.JCheckBox jCBPlanoContas;
    private javax.swing.JCheckBox jCBProdutos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JFrame jPesquisar;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JFileChooser jSeletor;
    private javax.swing.JTable jTblConsulta_Multi;
    private javax.swing.JTextField jTxtCaminho;
    private javax.swing.JTextField jTxtDtf;
    private javax.swing.JTextField jTxtDti;
    private javax.swing.JTextField jTxtId;
    private javax.swing.JTextField jTxtNome;
    private javax.swing.JTextField jTxtPesquisa_Multi;
    // End of variables declaration//GEN-END:variables

    private void montaLista() {

        DefaultTableModel lista = (DefaultTableModel) jTblConsulta_Multi.getModel();

        lista.setRowCount(0);
        lista.setColumnCount(0);

        lista.addColumn("Código");
        lista.addColumn("Nome");

        jTblConsulta_Multi.getColumnModel().getColumn(0).setMaxWidth(50);
        jTblConsulta_Multi.getColumnModel().getColumn(0).setMinWidth(50);
        jTblConsulta_Multi.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(50);
        jTblConsulta_Multi.getTableHeader().getColumnModel().getColumn(0).setMinWidth(50);
        jTblConsulta_Multi.setDefaultRenderer(Object.class, new ColorRender());

        String sql = "SELECT DISTINCT a.CODIGO, a.NOME "
                + "FROM CAD_TERCEIROS a "
                + "where a.EMPRESA = 1 "
                + "and EXISTS (SELECT * from CAD_TERCEIROS_PRODUTORES b "
                + "     where b.EMPRESA = a.EMPRESA and b.CODIGO = a.CODIGO) "
                + "order by a.NOME;";

        if (cnfb.conecta()) {
            try {
                cnfb.executeConsulta(sql);
                while (cnfb.rs.next()) {
                    lista.addRow(new String[]{
                        cnfb.rs.getString("codigo"),
                        cnfb.rs.getString("nome")
                    });
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            } finally {
                cnfb.desconecta();
            }
        }

    }

    private void incluiPesquisa() {

        int linha = jTblConsulta_Multi.getSelectedRow();

        switch (var_consulta) {

            case 1:

                jTxtId.setText(jTblConsulta_Multi.getValueAt(linha, 0).toString());
                jTxtNome.setText(jTblConsulta_Multi.getValueAt(linha, 1).toString());

                break;

            case 2:
                String sql = "SELECT DISTINCT a.CODIGO, a.NOME "
                        + "FROM CAD_TERCEIROS a "
                        + "where a.EMPRESA = 1 "
                        + "and EXISTS (SELECT * from CAD_TERCEIROS_PRODUTORES b "
                        + "     where b.EMPRESA = a.EMPRESA and b.CODIGO = a.CODIGO) "
                        + "and a.codigo = '" + jTxtId.getText() + "' "
                        + "order by a.NOME;";

                if (cnfb.conecta()) {
                    try {
                        cnfb.executeConsulta(sql);
                        while (cnfb.rs.next()) {
                            jTxtNome.setText(cnfb.rs.getString("nome"));
                        }

                        if ("".equals(jTxtNome.getText())) {
                            throw new UnsupportedOperationException("Não foi possível localizar um produtor rural com o código informado");
                        }

                    } catch (UnsupportedOperationException ex) {
                        jTxtId.grabFocus();
                        JOptionPane.showMessageDialog(null, ex.getMessage());
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e.getMessage());
                    } finally {
                        cnfb.desconecta();
                    }
                }

                break;

        }
    }
    
    public static void main(String[] args) {
        String pessoa = "2";
        String dti = "01/01/2017";
        String dtf = "31/12/2017";
        
        String sql = "select a.codigo as lancamento, "
                            + "case a.especie when 'NFE' then 36 else 99 end as especie, "
                            + "b.cnpj as inscricao_cliente, b.insc_municipal, "
                            + "b.insc, "
                            + "case (select first 1 a1.operacao from com_entradas_produtos a1 where a1.empresa = a.empresa and a1.codigo = a.codigo) "
                            + " when '1602' then '75' "
                            + " when '1701' then '108' "
                            + " when '1105' then '113' "
                            + " when '6212' then '111' "
                            + " when '1109' then '113' "
                            + " when '6216' then '114' "
                            + " when '6313' then '115' "
                            + " else (select first 1 a1.operacao from com_entradas_produtos a1 where a1.empresa = a.empresa and a1.codigo = a.codigo) end as cod_acumulador, "
                            + "case (select first 1 a2.cfop from com_entradas_produtos a2 where a2.empresa = a.empresa and a2.codigo = a.codigo) "
                            + " when '1202' then '5201' "
                            + " when '1949' then '5949' "
                            + " when '1102' then '5101' "
                            + " when '1101' then '5101' "
                            + " when '1556' then '5101' "
                            + " else (select first 1 a2.cfop from com_entradas_produtos a2 where a2.empresa = a.empresa and a2.codigo = a.codigo) end as cfop, "
                            + "m.uf as sigla_uf_cliente, "
                            + "a.numero as nro_doc, a.serie, "
                            + "a.dt_entrada as dt_saida, "
                            + "a.dt_emissao, "
                            + "(select sum(a3.vlr_contabil_item) from com_entradas_produtos a3 where a3.empresa = a.empresa and a3.codigo = a.codigo) as vlr_contabil, "
                            + "a.observacao, a.nfe_chave_acesso, "
                            + "a.total_produtos, "
                            + "case a.cif_fob when 'D' then 'F' when 'E' then 'C' else 'S' end as mod_frete, "
                            + "a.vlr_funrural as funrural, "
                            + "a.TOTAL_BASE_ICMS, "
                            + "a.TOTAL_VALOR_ICMS,"
                            + "o.FUNRURAL as desconta_funrural, "
                            + "p.produto as cod_produto, "
                            + "p.QUANTIDADE, "
                            + "p.VLR_CONTABIL_ITEM, "
                            + "p.VLR_BASE_ICMS, "
                            + "p.ALIQ_ICMS,"
                            + "p.UNITARIO,"
                            + "p.SITUACAO_TRIBUTARIA,"
                            + "case left(s.CLASSIFICACAO,2) when '01' then 'S' else 'N' end as movim_fis_prod,"
                            + "case when o.COMPRA_FIXAR = 'S' or o.COMPLEMENTO_FIXAR = 'S' or o.VENDA_COMPRA_PRODUTOS = 'S' or o.VENDA_ENTREGA_FUTURA = 'S' then 1 else 0 end as gera_financeiro "
                            + "from com_entradas a "
                            + "left join cad_estabelecimentos b on (b.empresa = a.empresa and b.codigo = a.estabelec) "
                            + "left join cad_municipios m on (m.codigo = b.municipio) "
                            + "left join COM_ENTRADAS_PRODUTOS p on (p.EMPRESA = a.EMPRESA and p.CODIGO = a.CODIGO) "
                            + "left join CAD_OPERACOES_FISC o on (o.EMPRESA = p.EMPRESA and o.CODIGO = p.OPERACAO) "
                            + "left join CAD_SETORES s on (s.EMPRESA = p.EMPRESA and s.CODIGO = p.PRODUTO) "
                            + "where a.empresa = 1 and a.fornecedor = '" + pessoa + "' "
                            + "and a.dt_entrada between '" + dti.replace("/", ".") + "' and '" + dtf.replace("/", ".") + "';";
        
        System.out.println(sql);
    }
}
