/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lancamentos;

import conn.ConexaoFB;
import tools.ColorRender;
import tools.FiltrarTabela;
import tools.TelaDeAvisos;
import java.awt.event.KeyEvent;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author ferna
 */
public class IntFrm_LiberaLancamentos extends javax.swing.JInternalFrame {

    private int var_consulta;
    private String sql;
    private final ConexaoFB cnfb = new ConexaoFB();
    private Object lastCount;
    private MaskFormatter data;

    private DateFormat dateIn = new SimpleDateFormat("dd/MM/yyyy");
    private DecimalFormat df = new DecimalFormat("#,##0.00");
    private String classificacao;

    /**
     * Creates new form IntFrm_LiberaLancamentos
     */
    public IntFrm_LiberaLancamentos() {
        try {
            data = new javax.swing.text.MaskFormatter("##/##/####");
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

        initComponents();

        montaTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPesquisar = new javax.swing.JFrame();
        jPanel10 = new javax.swing.JPanel();
        jTxtPesquisa_Multi = new javax.swing.JTextField();
        jBtnConfirmar = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTblConsulta_Multi = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTxtConta = new javax.swing.JTextField();
        jTxtNomeConta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTxtDti = new javax.swing.JFormattedTextField(data);
        jTxtDtf = new javax.swing.JFormattedTextField(data);
        jLabel3 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jTextField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTxtRegister = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable(){
            @Override
            public void changeSelection(int rowIndex, int columnIndex, boolean toggle, boolean extend) {
                super.changeSelection(rowIndex, columnIndex, !extend, extend);
            }};
            jPanel2 = new javax.swing.JPanel();
            jButton2 = new javax.swing.JButton();
            jTxtNroLctos = new javax.swing.JTextField();
            jLabel4 = new javax.swing.JLabel();
            jTxtValorLctos = new javax.swing.JTextField();
            jLabel5 = new javax.swing.JLabel();
            jLabel6 = new javax.swing.JLabel();
            jTxtSaldoLctos = new javax.swing.JTextField();
            jTxtTipoSaldo = new javax.swing.JTextField();

            jPesquisar.setTitle("Pesquisar");
            jPesquisar.setMinimumSize(new java.awt.Dimension(700, 400));

            jTxtPesquisa_Multi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
            jTxtPesquisa_Multi.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyPressed(java.awt.event.KeyEvent evt) {
                    jTxtPesquisa_MultiKeyPressed(evt);
                }
                public void keyReleased(java.awt.event.KeyEvent evt) {
                    jTxtPesquisa_MultiKeyReleased(evt);
                }
            });

            jBtnConfirmar.setText("Adicionar");
            jBtnConfirmar.setEnabled(false);
            jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jBtnConfirmarActionPerformed(evt);
                }
            });

            jBtnCancelar.setText("Cancelar");
            jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jBtnCancelarActionPerformed(evt);
                }
            });

            jTblConsulta_Multi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
            jTblConsulta_Multi.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null}
                },
                new String [] {
                    "Title 1", "Title 2", "Title 3", "Title 4"
                }
            ));
            jTblConsulta_Multi.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jTblConsulta_MultiMouseClicked(evt);
                }
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    jTblConsulta_MultiMouseEntered(evt);
                }
            });
            jScrollPane4.setViewportView(jTblConsulta_Multi);

            javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
            jPanel10.setLayout(jPanel10Layout);
            jPanel10Layout.setHorizontalGroup(
                jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel10Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                            .addGap(0, 453, Short.MAX_VALUE)
                            .addComponent(jBtnCancelar)
                            .addGap(18, 18, 18)
                            .addComponent(jBtnConfirmar))
                        .addComponent(jTxtPesquisa_Multi)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addContainerGap())
            );
            jPanel10Layout.setVerticalGroup(
                jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel10Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jTxtPesquisa_Multi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnConfirmar)
                        .addComponent(jBtnCancelar))
                    .addContainerGap())
            );

            javax.swing.GroupLayout jPesquisarLayout = new javax.swing.GroupLayout(jPesquisar.getContentPane());
            jPesquisar.getContentPane().setLayout(jPesquisarLayout);
            jPesquisarLayout.setHorizontalGroup(
                jPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );
            jPesquisarLayout.setVerticalGroup(
                jPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );

            setClosable(true);
            setTitle("Liberação de Lançamentos");

            jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Parâmetros"));

            jLabel1.setText("Conta");

            jTxtConta.setNextFocusableComponent(jTxtDti);
            jTxtConta.addFocusListener(new java.awt.event.FocusAdapter() {
                public void focusGained(java.awt.event.FocusEvent evt) {
                    jTxtContaFocusGained(evt);
                }
                public void focusLost(java.awt.event.FocusEvent evt) {
                    jTxtContaFocusLost(evt);
                }
            });
            jTxtConta.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyPressed(java.awt.event.KeyEvent evt) {
                    jTxtContaKeyPressed(evt);
                }
            });

            jTxtNomeConta.setEnabled(false);

            jLabel2.setText("Data Inicial");

            jTxtDti.setNextFocusableComponent(jTxtDtf);
            jTxtDti.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyPressed(java.awt.event.KeyEvent evt) {
                    jTxtDtiKeyPressed(evt);
                }
            });

            jTxtDtf.setNextFocusableComponent(jRadioButton1);
            jTxtDtf.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyPressed(java.awt.event.KeyEvent evt) {
                    jTxtDtfKeyPressed(evt);
                }
            });

            jLabel3.setText("Data Final");

            buttonGroup1.add(jRadioButton1);
            jRadioButton1.setSelected(true);
            jRadioButton1.setText("Liberar");
            jRadioButton1.setNextFocusableComponent(jCheckBox1);
            jRadioButton1.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jRadioButton1MouseClicked(evt);
                }
            });
            jRadioButton1.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyPressed(java.awt.event.KeyEvent evt) {
                    jRadioButton1KeyPressed(evt);
                }
            });

            buttonGroup1.add(jRadioButton2);
            jRadioButton2.setText("Estornar Liberação");
            jRadioButton2.setNextFocusableComponent(jCheckBox1);
            jRadioButton2.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jRadioButton2MouseClicked(evt);
                }
            });
            jRadioButton2.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyPressed(java.awt.event.KeyEvent evt) {
                    jRadioButton2KeyPressed(evt);
                }
            });

            jButton1.setText("Pesquisar");
            jButton1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
                }
            });

            jCheckBox1.setSelected(true);
            jCheckBox1.setText("Não Listar Entradas e Saídas");
            jCheckBox1.setNextFocusableComponent(jButton1);
            jCheckBox1.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyPressed(java.awt.event.KeyEvent evt) {
                    jCheckBox1KeyPressed(evt);
                }
            });

            jTextField1.setEnabled(false);

            jLabel7.setText("Lançamento");

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTxtDti, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTxtDtf, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jRadioButton1)
                                    .addGap(18, 18, 18)
                                    .addComponent(jRadioButton2))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTxtConta, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTxtNomeConta, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(0, 41, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTxtRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCheckBox1)
                            .addGap(18, 18, 18)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap())
            );
            jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jTxtConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTxtNomeConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jTxtDti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTxtDtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(jRadioButton1)
                        .addComponent(jRadioButton2))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jCheckBox1)
                        .addComponent(jLabel7)
                        .addComponent(jTxtRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap())
            );

            jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null}
                },
                new String [] {
                    "Title 1", "Title 2", "Title 3", "Title 4"
                }
            ));
            jScrollPane1.setViewportView(jTable1);

            jButton2.setText("Liberar");
            jButton2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton2ActionPerformed(evt);
                }
            });

            jTxtNroLctos.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
            jTxtNroLctos.setEnabled(false);

            jLabel4.setText("Registros");

            jTxtValorLctos.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
            jTxtValorLctos.setEnabled(false);

            jLabel5.setText("Movimentação");

            jLabel6.setText("Saldo");

            jTxtSaldoLctos.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
            jTxtSaldoLctos.setEnabled(false);

            jTxtTipoSaldo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
            jTxtTipoSaldo.setEnabled(false);

            javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
            jPanel2.setLayout(jPanel2Layout);
            jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jTxtSaldoLctos, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jTxtTipoSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jLabel5)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jTxtValorLctos, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(44, 44, 44)
                    .addComponent(jLabel4)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jTxtNroLctos, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
            );
            jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jTxtNroLctos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTxtValorLctos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jTxtSaldoLctos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtTipoSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            );

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap())
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        final TelaDeAvisos tela;
        final JInternalFrame frame = this;

        try {

            if (jTable1.getRowCount() == 0) {
                throw new UnsupportedOperationException("Não há lançamentos para liberar.");
            }

            tela = new TelaDeAvisos();

            new Thread() {
                public void run() {

                    frame.setVisible(false);

                    if (cnfb.conecta()) {
                        try {

                            LiberacaoLancamentos freeLanc = new LiberacaoLancamentos(cnfb);

                            for (int i = 0; i < jTable1.getRowCount(); i++) {

                                String lancamento = jTable1.getValueAt(i, 0).toString();

                                if (jRadioButton1.isSelected()) {
                                    tela.setMsgStatus("Liberando " + jTable1.getValueAt(i, 5), i, jTable1.getRowCount());
                                    freeLanc.liberar(lancamento);
                                } else {
                                    tela.setMsgStatus("Estornando liberação de " + jTable1.getValueAt(i, 5), i, jTable1.getRowCount());
                                    freeLanc.estonarLiberar(lancamento);
                                }

                            }

                            montaTabela();

                        } catch (Exception e) {
                            JOptionPane.showMessageDialog(null, e.getMessage());
                        } finally {
                            frame.setVisible(true);
                            tela.dispose();
                            if (cnfb.isConnected()) {
                                cnfb.desconecta();
                            }
                        }
                    }
                }
            }.start();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTxtContaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtContaFocusLost
        String conta = jTxtConta.getText();

        if (!conta.equals(lastCount)) {

            jTxtNomeConta.setText("");
            jTextField1.setText("");

            if (!"".equals(conta)) {

                var_consulta = 1;
                incluiPesquisa();

            }
        }

    }//GEN-LAST:event_jTxtContaFocusLost

    private void jTxtContaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtContaFocusGained
        lastCount = jTxtConta.getText();// TODO add your handling code here:
    }//GEN-LAST:event_jTxtContaFocusGained

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {

            if ("".equals(jTxtNomeConta.getText()) && "".equals(jTxtRegister.getText())) {
                jTxtConta.grabFocus();
                throw new UnsupportedOperationException("Selecione uma conta ou um lançamento para continuar.");
            }
            if ("  /  /    ".equals(jTxtDti.getText()) && "".equals(jTxtRegister.getText())) {
                jTxtDti.grabFocus();
                throw new UnsupportedOperationException("Informe uma data inicial ou um lançamento para continuar.");
            }
            if ("  /  /    ".equals(jTxtDtf.getText()) && "".equals(jTxtRegister.getText())) {
                jTxtDtf.grabFocus();
                throw new UnsupportedOperationException("Informe uma data final ou um lançamento para continuar.");
            }
            var_consulta = 2;
            incluiPesquisa();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton1MouseClicked
        montaTabela();
    }//GEN-LAST:event_jRadioButton1MouseClicked

    private void jRadioButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton2MouseClicked
        montaTabela();        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2MouseClicked

    private void jTxtPesquisa_MultiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtPesquisa_MultiKeyReleased
        new FiltrarTabela(jTblConsulta_Multi, jTxtPesquisa_Multi.getText());
    }//GEN-LAST:event_jTxtPesquisa_MultiKeyReleased

    private void jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmarActionPerformed
        incluiPesquisa();
        jPesquisar.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jBtnConfirmarActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        jPesquisar.dispose();
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jTblConsulta_MultiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblConsulta_MultiMouseClicked
        jBtnConfirmar.setEnabled(true);    // TODO add your handling code here:
    }//GEN-LAST:event_jTblConsulta_MultiMouseClicked

    private void jTblConsulta_MultiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblConsulta_MultiMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTblConsulta_MultiMouseEntered

    private void jTxtContaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtContaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_F2) {
            jPesquisar.setVisible(true);
            jPesquisar.setTitle("Plano de Contas");
            var_consulta = 11;
            jTxtPesquisa_Multi.setText("");

            montaLista();
        } else {
            tools.AcaoPadrao.acaoPadraoTeclado(evt, jTxtConta, this);
        }
    }//GEN-LAST:event_jTxtContaKeyPressed

    private void jTxtPesquisa_MultiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtPesquisa_MultiKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTblConsulta_Multi.setRowSelectionInterval(0, 0);
            incluiPesquisa();
            jPesquisar.dispose();
        }
    }//GEN-LAST:event_jTxtPesquisa_MultiKeyPressed

    private void jTxtDtiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtDtiKeyPressed
        tools.AcaoPadrao.acaoPadraoTeclado(evt, jTxtDti, this);

    }//GEN-LAST:event_jTxtDtiKeyPressed

    private void jTxtDtfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtDtfKeyPressed
        tools.AcaoPadrao.acaoPadraoTeclado(evt, jTxtDtf, this);        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtDtfKeyPressed

    private void jRadioButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jRadioButton1KeyPressed
        tools.AcaoPadrao.acaoPadraoTeclado(evt, jRadioButton1, this);        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1KeyPressed

    private void jRadioButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jRadioButton2KeyPressed
        tools.AcaoPadrao.acaoPadraoTeclado(evt, jRadioButton2, this);
    }//GEN-LAST:event_jRadioButton2KeyPressed

    private void jCheckBox1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCheckBox1KeyPressed
        tools.AcaoPadrao.acaoPadraoTeclado(evt, jCheckBox1, this);

    }//GEN-LAST:event_jCheckBox1KeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnConfirmar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JFrame jPesquisar;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTblConsulta_Multi;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTxtConta;
    private javax.swing.JFormattedTextField jTxtDtf;
    private javax.swing.JFormattedTextField jTxtDti;
    private javax.swing.JTextField jTxtNomeConta;
    private javax.swing.JTextField jTxtNroLctos;
    private javax.swing.JTextField jTxtPesquisa_Multi;
    private javax.swing.JTextField jTxtRegister;
    private javax.swing.JTextField jTxtSaldoLctos;
    private javax.swing.JTextField jTxtTipoSaldo;
    private javax.swing.JTextField jTxtValorLctos;
    // End of variables declaration//GEN-END:variables

    private void incluiPesquisa() {
        switch (var_consulta) {
            case 1:
                sql = "SELECT nome, classificacao, tipo FROM cad_planocontas WHERE empresa = 1 "
                        + "AND codigo = '" + jTxtConta.getText() + "' ";

                if (cnfb.conecta()) {
                    try {
                        cnfb.executeConsulta(sql);
                        while (cnfb.rs.next()) {
                            jTxtNomeConta.setText(cnfb.rs.getString("classificacao") + " - "
                                    + cnfb.rs.getString("nome"));
                            jTextField1.setText(cnfb.rs.getString("tipo"));
                            classificacao = cnfb.rs.getString("classificacao");
                        }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, e.getMessage());
                    } finally {
                        cnfb.desconecta();
                    }
                }

                break;

            case 11:
                int linha = jTblConsulta_Multi.getSelectedRow();

                jTxtNomeConta.setText(jTblConsulta_Multi.getValueAt(linha, 2)
                        + " - " + jTblConsulta_Multi.getValueAt(linha, 3));
                jTextField1.setText(jTblConsulta_Multi.getValueAt(linha, 0).toString());
                jTxtConta.setText(jTblConsulta_Multi.getValueAt(linha, 1).toString());

                jTxtDti.grabFocus();

                break;

            case 2:

                DefaultTableModel lista = montaTabela();

                String conta;
                int x = 0;
                Double valor = 0.00;
                Double outstandingbalanceaccount = 0.00;

                ArrayList contas = new ArrayList();
                ArrayList lancamentos = new ArrayList();
                contas.clear();

                if (cnfb.conecta()) {
                    try {
                        // SE CONTA JÁ FOR ANALÍTICA, PROCESSA APENAS ELA, 
                        // COM UM ARRAYLIST DE TAMANHO 1
                        // SE CONTA FOR TOTALIZADORA, ENCONTRA TODAS AS 
                        // ANALÍTICAS VINCULADAS.
                        if ("A".equals(jTextField1.getText())) {
                            contas.add(jTxtConta.getText());
                        } else if ("".equals(jTextField1.getText())){
                            contas.add("0");
                        } else {
                            sql = "SELECT codigo FROM cad_planocontas WHERE empresa = 1 and tipo = 'A' and classificacao starting with '" + classificacao + "';";

                            cnfb.executeConsulta(sql);
                            while (cnfb.rs.next()) {
                                contas.add(cnfb.rs.getString("codigo"));
                            }
                            cnfb.rs.close();
                        }

                        /**
                         * INICIA O LAÇO E EXECUTA UMA VEZ PARA CADA CONTA
                         * CAPTURADA
                         *
                         */
                        for (int i = 0; i < contas.size(); i++) {

                            conta = contas.get(i).toString();

                            /**
                             * CONSULTA SALDO A LIBERAR
                             */
                            sql = "SELECT a.numero, a.data, a.debito, a.credito, a.complemento, "
                                    + "case when a.credito = '" + conta + "' then a.valor "
                                    + "else a.valor *-1 end as valor "
                                    + "FROM ctb_lancamentos a "
                                    + "WHERE a.empresa = 1 "
                                    + "AND not exists (select * from ctb_bloqueia_lctos x "
                                    + "     where x.empresa = a.empresa "
                                    + "     and (x.estabelec = a.estab_debito or x.estabelec = a.estab_credito) "
                                    + "     and a.data <= x.data) ";

                            if (!"  /  /    ".equals(jTxtDtf.getText()) && !"  /  /    ".equals(jTxtDti.getText())) {
                                sql += "and a.data between '" + jTxtDti.getText().replace("/", ".") + "' "
                                        + "and '" + jTxtDtf.getText().replace("/", ".") + "' ";
                            }

                            if (!"0".equals(conta)) {
                                sql += "AND (a.debito = '" + conta + "' "
                                        + "OR a.credito = '" + conta + "') ";
                            }

                            if (jCheckBox1.isSelected()) {
                                sql += "and a.origem  not in ('COM', 'CTRP', 'VEN', 'CTRR', 'VENCTR', 'AJCTR') ";
                            }

                            if (jRadioButton1.isSelected()) {
                                sql += "and (a.liberado = 'N' or a.liberado is null) ";
                            } else {
                                sql += "and a.liberado = 'S' ";
                            }

                            if (!"".equals(jTxtRegister.getText())) {
                                sql += "and a.numero = '" + jTxtRegister.getText() + "' ";
                            }

                            cnfb.executeConsulta(sql);
                            while (cnfb.rs.next()) {
                                if (!lancamentos.contains(cnfb.rs.getString("numero"))) {
                                    lista.addRow(new String[]{
                                        cnfb.rs.getString("numero"),
                                        dateIn.format(cnfb.rs.getDate("data")),
                                        cnfb.rs.getString("debito"),
                                        cnfb.rs.getString("credito"),
                                        df.format(cnfb.rs.getDouble("valor")),
                                        cnfb.rs.getString("complemento")
                                    });

                                    lancamentos.add(cnfb.rs.getString("numero"));
                                }

                                valor += cnfb.rs.getDouble("valor");
                                x++;
                            }
                            cnfb.rs.close();

                            /**
                             * CONSULTA SALDO DA CONTA
                             */
                            sql = "SELECT a.numero, a.data, a.debito, a.credito, a.complemento, "
                                    + "case when a.credito = '" + conta + "' then a.valor "
                                    + "else a.valor *-1 end as valor "
                                    + "FROM ctb_lancamentos a "
                                    + "WHERE a.empresa = 1 "
                                    + "and a.data <= '" + jTxtDtf.getText().replace("/", ".") + "' "
                                    + "AND (a.debito = '" + conta + "' "
                                    + "OR a.credito = '" + conta + "'); ";

                            cnfb.executeConsulta(sql);
                            while (cnfb.rs.next()) {

                                outstandingbalanceaccount += cnfb.rs.getDouble("valor");
                            }
                            cnfb.rs.close();

                        }
                    } catch (Exception e) {
                        montaTabela();
                        x = 0;
                        valor = 0.00;
                        JOptionPane.showMessageDialog(this, e.getMessage());
                    } finally {
                        cnfb.desconecta();
                    }
                }

                Character tipo;

                if (outstandingbalanceaccount < 0.00) {
                    tipo = "D".charAt(0);
                } else {
                    tipo = "C".charAt(0);
                }

                jTxtNroLctos.setText("" + x);
                jTxtValorLctos.setText(df.format(valor * -1));
                jTxtSaldoLctos.setText(df.format(Math.abs(outstandingbalanceaccount)));
                jTxtTipoSaldo.setText(tipo.toString());

        }
    }

    private DefaultTableModel montaTabela() {

        DefaultTableModel lista = (DefaultTableModel) jTable1.getModel();

        lista.setRowCount(0);
        lista.setColumnCount(0);

        lista.addColumn("Número");
        lista.addColumn("Data");
        lista.addColumn("Débito");
        lista.addColumn("Crédito");
        lista.addColumn("Valor");
        lista.addColumn("Complemento");

        jTable1.getColumnModel().getColumn(0).setMaxWidth(80);
        jTable1.getColumnModel().getColumn(0).setMinWidth(80);
        jTable1.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(80);
        jTable1.getTableHeader().getColumnModel().getColumn(0).setMinWidth(80);
        jTable1.getColumnModel().getColumn(1).setMaxWidth(80);
        jTable1.getColumnModel().getColumn(1).setMinWidth(80);
        jTable1.getTableHeader().getColumnModel().getColumn(1).setMaxWidth(80);
        jTable1.getTableHeader().getColumnModel().getColumn(1).setMinWidth(80);
        jTable1.getColumnModel().getColumn(2).setMaxWidth(80);
        jTable1.getColumnModel().getColumn(2).setMinWidth(80);
        jTable1.getTableHeader().getColumnModel().getColumn(2).setMaxWidth(80);
        jTable1.getTableHeader().getColumnModel().getColumn(2).setMinWidth(80);
        jTable1.getColumnModel().getColumn(3).setMaxWidth(80);
        jTable1.getColumnModel().getColumn(3).setMinWidth(80);
        jTable1.getTableHeader().getColumnModel().getColumn(3).setMaxWidth(80);
        jTable1.getTableHeader().getColumnModel().getColumn(3).setMinWidth(80);
        jTable1.getColumnModel().getColumn(4).setMaxWidth(80);
        jTable1.getColumnModel().getColumn(4).setMinWidth(80);
        jTable1.getTableHeader().getColumnModel().getColumn(4).setMaxWidth(80);
        jTable1.getTableHeader().getColumnModel().getColumn(4).setMinWidth(80);

        jTable1.setDefaultRenderer(Object.class, new ColorRender());

        return lista;
    }

    private void montaLista() {
        DefaultTableModel lista = (DefaultTableModel) jTblConsulta_Multi.getModel();

        lista.setRowCount(0);
        lista.setColumnCount(0);

        lista.addColumn("tipo");
        lista.addColumn("Código");
        lista.addColumn("Classificacao");
        lista.addColumn("Nome");

        jTblConsulta_Multi.getColumnModel().getColumn(0).setMaxWidth(0);
        jTblConsulta_Multi.getColumnModel().getColumn(0).setMinWidth(0);
        jTblConsulta_Multi.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
        jTblConsulta_Multi.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);
        jTblConsulta_Multi.getColumnModel().getColumn(1).setMaxWidth(40);
        jTblConsulta_Multi.getColumnModel().getColumn(1).setMinWidth(40);
        jTblConsulta_Multi.getTableHeader().getColumnModel().getColumn(1).setMaxWidth(40);
        jTblConsulta_Multi.getTableHeader().getColumnModel().getColumn(1).setMinWidth(40);
        jTblConsulta_Multi.getColumnModel().getColumn(2).setMaxWidth(80);
        jTblConsulta_Multi.getColumnModel().getColumn(2).setMinWidth(80);
        jTblConsulta_Multi.getTableHeader().getColumnModel().getColumn(2).setMaxWidth(80);
        jTblConsulta_Multi.getTableHeader().getColumnModel().getColumn(2).setMinWidth(80);

        jTblConsulta_Multi.setDefaultRenderer(Object.class, new ColorRender());

        sql = "SELECT tipo, codigo, classificacao, nome "
                + "FROM cad_planocontas WHERE empresa = 1 AND ativo = 'S' "
                + "ORDER BY classificacao, nome, codigo;";

        if (cnfb.conecta()) {
            try {
                cnfb.executeConsulta(sql);
                while (cnfb.rs.next()) {
                    lista.addRow(new String[]{
                        cnfb.rs.getString("tipo"),
                        cnfb.rs.getString("codigo"),
                        cnfb.rs.getString("classificacao"),
                        cnfb.rs.getString("nome")
                    });
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            } finally {
                cnfb.desconecta();
            }
        }

    }
}
