/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lancamentos;

import conn.ConexaoFB;
import tools.ColorRender;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author luiz.barcellos
 */
public class IntFrm_AlteraLancamentos extends javax.swing.JInternalFrame {

    private MaskFormatter data;
    private ConexaoFB cnfb = new ConexaoFB();

    private DateFormat dateIn = new SimpleDateFormat("dd/MM/yyyy");
    private DecimalFormat df = new DecimalFormat("#,##0.00");
    private int var_consulta;
    private Object lastCount;

    private final int LANCAMENTOS = 1;

    private final int CTA_DEBITO_P = 2;
    private final int CTA_CREDITO_P = 3;
    private final int CTA_DEBITO_U = 4;
    private final int CTA_CREDITO_U = 5;
    private final int HISTORICO = 6;

    private final int DADOS_DEBITO = 7;
    private final int DADOS_CREDITO = 8;
    private String sql;

    /**
     * Creates new form IntFrm_AlteraLancamentos
     */
    public IntFrm_AlteraLancamentos() {
        try {
            data = new javax.swing.text.MaskFormatter("##/##/####");
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTxtDti = new javax.swing.JFormattedTextField(data);
        jTxtDtf = new javax.swing.JFormattedTextField(data);
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTxtCtaDebito = new javax.swing.JTextField();
        jTxtCtaCredito = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTxtNomeDebito = new javax.swing.JTextField();
        jTxtNomeCredito = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTxtComplemento = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTxtCtaDebito_u = new javax.swing.JTextField();
        jTxtCtaCredito_u = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTxtNomeDebito_u = new javax.swing.JTextField();
        jTxtNomeCredito_u = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTxtHistorico = new javax.swing.JTextField();
        jTxtNomeHistorico = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();

        setClosable(true);
        setTitle("Alteracao de Lançamentos");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Parâmetros de Pesquisa"));

        jLabel1.setText("Data Inicial");

        jLabel2.setText("Data Final");

        jLabel3.setText("Débito");

        jTxtCtaDebito.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTxtCtaDebitoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtCtaDebitoFocusLost(evt);
            }
        });

        jTxtCtaCredito.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTxtCtaCreditoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtCtaCreditoFocusLost(evt);
            }
        });

        jLabel4.setText("Crédito");

        jTxtNomeDebito.setEnabled(false);

        jTxtNomeCredito.setEnabled(false);

        jLabel5.setText("Complemento");

        jButton1.setText("Pesquisar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTxtDti, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtDtf, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtCtaCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtCtaDebito, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTxtNomeDebito, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                            .addComponent(jTxtNomeCredito)))
                    .addComponent(jTxtComplemento))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxtDti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtDtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTxtCtaDebito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtNomeDebito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTxtCtaCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtNomeCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTxtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Novos Dados"));

        jLabel8.setText("Débito");

        jTxtCtaDebito_u.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTxtCtaDebito_uFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtCtaDebito_uFocusLost(evt);
            }
        });

        jTxtCtaCredito_u.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTxtCtaCredito_uFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtCtaCredito_uFocusLost(evt);
            }
        });

        jLabel9.setText("Crédito");

        jTxtNomeDebito_u.setEnabled(false);

        jTxtNomeCredito_u.setEnabled(false);

        jLabel10.setText("Histórico");

        jButton2.setText("Gravar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTxtHistorico.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTxtHistoricoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtHistoricoFocusLost(evt);
            }
        });

        jTxtNomeHistorico.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtCtaCredito_u, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtCtaDebito_u, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTxtNomeDebito_u, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                                    .addComponent(jTxtNomeCredito_u))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTxtHistorico, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtNomeHistorico))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTxtCtaDebito_u, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtNomeDebito_u, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTxtCtaCredito_u, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtNomeCredito_u, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTxtHistorico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtNomeHistorico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Conta Crédito"));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setEnabled(false);
        jScrollPane1.setViewportView(jTable1);

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder("Lançamentos"));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jScrollPane3.setBorder(javax.swing.BorderFactory.createTitledBorder("Conta Débito"));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable3.setEnabled(false);
        jScrollPane3.setViewportView(jTable3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {

            if (jTable2.getRowCount() == 0) {
                throw new UnsupportedOperationException("Não existem dados na tabela a serem alterados.");

            }

            if ("".equals(jTxtNomeDebito_u.getText()) && "".equals(jTxtNomeCredito_u.getText()) && "".equals(jTxtNomeHistorico.getText())) {
                throw new UnsupportedOperationException("Você deve informar algum dado para alterar.");
            }

            if (cnfb.conecta()) {
                try {

                    boolean selected;
                    String numero;

                    if (jTable2.getSelectedRowCount() > 0) {

                        selected = true;

                    } else {
                        selected = false;
                    }

                    for (int i = 0; i < jTable2.getRowCount(); i++) {

                        numero = jTable2.getValueAt(i, 0).toString();

                        if (selected) {

                            if (jTable2.isRowSelected(i)) {
                                gravaDados(numero, jTxtCtaDebito_u.getText(), jTxtCtaCredito_u.getText(), jTxtHistorico.getText());
                            }

                        } else {
                            gravaDados(numero, jTxtCtaDebito_u.getText(), jTxtCtaCredito_u.getText(), jTxtHistorico.getText());
                        }

                    }

                } catch (Exception e) {
                    throw new UnsupportedOperationException(e);
                } finally {
                    cnfb.desconecta();
                    var_consulta = LANCAMENTOS;
                    incluiPesquisa();
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        } finally {

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        var_consulta = LANCAMENTOS;
        incluiPesquisa();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTxtCtaDebitoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtCtaDebitoFocusLost
        String conta = jTxtCtaDebito.getText();

        if (!conta.equals(lastCount)) {

            jTxtNomeDebito.setText("");

            if (!"".equals(conta)) {

                var_consulta = CTA_DEBITO_P;
                incluiPesquisa();

            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCtaDebitoFocusLost

    private void jTxtCtaDebitoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtCtaDebitoFocusGained
        lastCount = jTxtCtaDebito.getText();        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCtaDebitoFocusGained

    private void jTxtCtaCreditoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtCtaCreditoFocusGained
        lastCount = jTxtCtaCredito.getText();
    }//GEN-LAST:event_jTxtCtaCreditoFocusGained

    private void jTxtCtaCreditoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtCtaCreditoFocusLost
        String conta = jTxtCtaCredito.getText();

        if (!conta.equals(lastCount)) {

            jTxtNomeCredito.setText("");

            if (!"".equals(conta)) {

                var_consulta = CTA_CREDITO_P;
                incluiPesquisa();

            }
        }
    }//GEN-LAST:event_jTxtCtaCreditoFocusLost

    private void jTxtCtaDebito_uFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtCtaDebito_uFocusGained
        lastCount = jTxtCtaDebito_u.getText();
    }//GEN-LAST:event_jTxtCtaDebito_uFocusGained

    private void jTxtCtaDebito_uFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtCtaDebito_uFocusLost
        String conta = jTxtCtaDebito_u.getText();

        if (!conta.equals(lastCount)) {

            jTxtNomeDebito_u.setText("");

            if (!"".equals(conta)) {

                var_consulta = CTA_DEBITO_U;
                incluiPesquisa();

            }
        }
    }//GEN-LAST:event_jTxtCtaDebito_uFocusLost

    private void jTxtCtaCredito_uFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtCtaCredito_uFocusGained
        lastCount = jTxtCtaCredito_u.getText();
    }//GEN-LAST:event_jTxtCtaCredito_uFocusGained

    private void jTxtCtaCredito_uFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtCtaCredito_uFocusLost
        String conta = jTxtCtaCredito_u.getText();

        if (!conta.equals(lastCount)) {

            jTxtNomeCredito_u.setText("");

            if (!"".equals(conta)) {

                var_consulta = CTA_CREDITO_U;
                incluiPesquisa();

            }
        }
    }//GEN-LAST:event_jTxtCtaCredito_uFocusLost

    private void jTxtHistoricoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtHistoricoFocusGained
        lastCount = jTxtHistorico.getText();
    }//GEN-LAST:event_jTxtHistoricoFocusGained

    private void jTxtHistoricoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtHistoricoFocusLost
        String conta = jTxtHistorico.getText();

        if (!conta.equals(lastCount)) {

            jTxtNomeHistorico.setText("");

            if (!"".equals(conta)) {

                var_consulta = HISTORICO;
                incluiPesquisa();

            }
        }
    }//GEN-LAST:event_jTxtHistoricoFocusLost

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        var_consulta = DADOS_DEBITO;
        incluiPesquisa();
        var_consulta = DADOS_CREDITO;
        incluiPesquisa();
    }//GEN-LAST:event_jTable2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTxtComplemento;
    private javax.swing.JTextField jTxtCtaCredito;
    private javax.swing.JTextField jTxtCtaCredito_u;
    private javax.swing.JTextField jTxtCtaDebito;
    private javax.swing.JTextField jTxtCtaDebito_u;
    private javax.swing.JFormattedTextField jTxtDtf;
    private javax.swing.JFormattedTextField jTxtDti;
    private javax.swing.JTextField jTxtHistorico;
    private javax.swing.JTextField jTxtNomeCredito;
    private javax.swing.JTextField jTxtNomeCredito_u;
    private javax.swing.JTextField jTxtNomeDebito;
    private javax.swing.JTextField jTxtNomeDebito_u;
    private javax.swing.JTextField jTxtNomeHistorico;
    // End of variables declaration//GEN-END:variables

    private void incluiPesquisa() {

        int linha = jTable2.getSelectedRow();

        switch (var_consulta) {
            case CTA_CREDITO_P:

                jTxtNomeCredito.setText(consultaContas(jTxtCtaCredito.getText()));

                break;

            case CTA_CREDITO_U:

                jTxtNomeCredito_u.setText(consultaContas(jTxtCtaCredito_u.getText()));

                break;

            case CTA_DEBITO_P:

                jTxtNomeDebito.setText(consultaContas(jTxtCtaDebito.getText()));

                break;

            case CTA_DEBITO_U:

                jTxtNomeDebito_u.setText(consultaContas(jTxtCtaDebito_u.getText()));

                break;

            case HISTORICO:

                //jTxtNomeHistorico.setText(consultaContas(jTxtHistorico.getText()));
                sql = "SELECT nome FROM CAD_HIST_CONTABIL "
                        + "where codigo = '" + jTxtHistorico.getText() + "' "
                        + "and empresa = 1;";

                if (cnfb.conecta()) {
                    try {
                        cnfb.executeConsulta(sql);
                        while (cnfb.rs.next()) {
                            jTxtNomeHistorico.setText(cnfb.rs.getString("nome"));
                        }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, e.getMessage());
                    } finally {
                        cnfb.desconecta();
                    }
                }

                break;

            case LANCAMENTOS:

                DefaultTableModel lista = (DefaultTableModel) jTable2.getModel();

                lista.setRowCount(0);
                lista.setColumnCount(0);

                lista.addColumn("Número");
                lista.addColumn("Data");
                lista.addColumn("Débito");
                lista.addColumn("Crédito");
                lista.addColumn("Valor");
                lista.addColumn("Histórico");
                lista.addColumn("Complemento");

                try {
                    String dti = jTxtDti.getText().replace("/", ".");
                    String dtf = jTxtDtf.getText().replace("/", ".");

                    if ("  /  /    ".equals(dti) | "  /  /    ".equals(dtf)) {
                        jTxtDti.grabFocus();
                        throw new UnsupportedOperationException("Você deve informar data inicial e final para pesquisar.");
                    }

                    if ("".equals(jTxtNomeDebito.getText()) && "".equals(jTxtNomeCredito.getText())) {
                        jTxtCtaDebito.grabFocus();
                        throw new UnsupportedOperationException("Você deve selecionar ao menos uma conta para pesquisar.");
                    }

                    sql = "select a.numero, a.data, a.debito, a.credito, a.valor, "
                            + "a.historico, a.complemento "
                            + "from ctb_lancamentos a "
                            + "where a.empresa = 1 "
                            + "AND a.data between '" + dti + "' and '" + dtf + "' ";

                    if (!"".equals(jTxtNomeDebito.getText())) {
                        sql += "AND a.debito = '" + jTxtCtaDebito.getText() + "' ";
                    }

                    if (!"".equals(jTxtNomeCredito.getText())) {
                        sql += "AND a.credito = '" + jTxtCtaCredito.getText() + "' ";
                    }

                    if (!"".equals(jTxtComplemento.getText())) {
                        sql += "AND upper(a.complemento) like ('%" + jTxtComplemento.getText().toUpperCase() + "%') ";
                    }

                    if (cnfb.conecta()) {
                        try {
                            cnfb.executeConsulta(sql);
                            while (cnfb.rs.next()) {
                                lista.addRow(new String[]{
                                    cnfb.rs.getString("numero"),
                                    dateIn.format(cnfb.rs.getDate("data")),
                                    cnfb.rs.getString("debito"),
                                    cnfb.rs.getString("credito"),
                                    df.format(cnfb.rs.getDouble("valor")),
                                    cnfb.rs.getString("historico"),
                                    cnfb.rs.getString("complemento")
                                });
                            }
                        } catch (Exception e) {
                            throw new UnsupportedOperationException(e);
                        } finally {
                            cnfb.desconecta();
                        }
                    }

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());
                }

                break;

            case DADOS_CREDITO:

                if (jTable2.getValueAt(linha, 3).toString() != null) {
                    consultaClassContas(jTable1, jTable2.getValueAt(linha, 3).toString());
                }

                break;

            case DADOS_DEBITO:
                if (jTable2.getValueAt(linha, 2).toString() != null) {
                    consultaClassContas(jTable3, jTable2.getValueAt(linha, 2).toString());
                }
                break;

        }

    }

    private String consultaContas(String codigo) {

        String resultado = "";

        sql = "SELECT nome, classificacao FROM cad_planocontas WHERE empresa = 1 "
                + "AND codigo = '" + codigo + "';";

        if (cnfb.conecta()) {
            try {
                cnfb.executeConsulta(sql);
                while (cnfb.rs.next()) {
                    resultado = cnfb.rs.getString("classificacao") + " - " + cnfb.rs.getString("nome");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            } finally {
                cnfb.desconecta();
            }
        }

        return resultado;
    }

    private void consultaClassContas(JTable x, String conta) {

        DefaultTableModel lista = (DefaultTableModel) x.getModel();

        lista.setRowCount(0);
        lista.setColumnCount(0);

        lista.addColumn("tipo");
        lista.addColumn("");

        x.getColumnModel().getColumn(0).setMaxWidth(0);
        x.getColumnModel().getColumn(0).setMinWidth(0);
        x.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
        x.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);

        x.setDefaultRenderer(Object.class, new ColorRender());

        sql = "select b.nome, b.classificacao, b.tipo "
                + "from cad_planocontas a "
                + "left join cad_planocontas b on (b.empresa = a.empresa and a.classificacao starting with (b.classificacao)) "
                + "where a.empresa = 1 and a.codigo = '" + conta + "' "
                + "ORDER BY b.classificacao, a.nome; ";

        if (cnfb.conecta()) {
            try {
                cnfb.executeConsulta(sql);
                while (cnfb.rs.next()) {
                    lista.addRow(new String[]{
                        cnfb.rs.getString("tipo"),
                        cnfb.rs.getString("classificacao") + " - " + cnfb.rs.getString("nome")
                    });
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            } finally {
                cnfb.desconecta();
            }
        }

    }

    private void gravaDados(String numero, String debito, String credito, String historico) throws Exception {
        boolean virgula = false;

        sql = "UPDATE ctb_lancamentos SET ";

        if (!"".equals(debito)) {

            sql += "debito = '" + debito + "' ";

            virgula = true;
        }

        if (!"".equals(credito)) {

            if (virgula) {
                sql += ", ";
            }

            sql += "credito = '" + credito + "' ";

            virgula = true;
        }

        if (!"".equals(historico)) {
            if (virgula) {
                sql += ", ";
            }

            sql += "historico = '" + historico + "' ";
        }

        sql += "WHERE empresa = 1 and numero = '" + numero + "';";

        cnfb.executeAtualizacao(sql);

    }

}
