/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package funrural;

import conn.ConexaoFB;
import conn.ConexaoMySQL;
import conn.ConexaoORCL;
import tools.ColorRender;
import tools.ManipulaData;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;
import tools.EmpresaFilial;
import tools.TelaDeAvisos;
import java.util.ArrayList;

/**
 *
 * @author luiz.barcellos
 */
public class ImportFunrural extends javax.swing.JInternalFrame {

    private final DateFormat dateIn = new SimpleDateFormat("dd/MM/yyyy");
    private final DateFormat dateOut = new SimpleDateFormat("yyyy/MM/dd");
    private String sql;
    private Date dtf;
    private Date dti;
    private boolean importar;
    private String comp;
    private ManipulaData mData = new ManipulaData();
    private MaskFormatter competencia, data;
    private final ConexaoMySQL cn;
    private ConexaoFB cnfb = new ConexaoFB();
    private ConexaoORCL cnor = new ConexaoORCL();
    private DecimalFormat df = new DecimalFormat("#,##0.00");
    private EmpresaFilial emp;

    /**
     * Creates new form ImportFunrural
     */
    public ImportFunrural(ConexaoMySQL conn) {
        try {
            competencia = new javax.swing.text.MaskFormatter("##/####");
            data = new javax.swing.text.MaskFormatter("##/##/####");
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        this.cn = conn;
        emp = new EmpresaFilial(conn);

        initComponents();

        montaTabela();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jTxtCompetencia = new javax.swing.JFormattedTextField(competencia);
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTxtQtd = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTxtVlrBruto = new javax.swing.JTextField();
        jTxtVlrFunrural = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTxtVlrSenar = new javax.swing.JTextField();
        jTxtTotal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTxtContabilidade = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTxtQtd1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTxtVlrBruto1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTxtVlrFunrural1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTxtVlrSenar1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTxtTotal1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setTitle("Lançamentos FUNRURAL");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisa Aquisição de Produção"));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Importar");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Consultar");

        jLabel1.setText("Competência");

        jButton1.setText("Pesquisar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Gravar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Estornar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel8.setText("Status");

        jTextField1.setEnabled(false);

        jButton4.setText("Folha de Pagamentos");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jRadioButton1)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton2)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTxtCompetencia, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jRadioButton1)
                .addComponent(jRadioButton2)
                .addComponent(jTxtCompetencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel1)
                .addComponent(jButton1)
                .addComponent(jButton2)
                .addComponent(jButton3)
                .addComponent(jLabel8)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton4))
        );

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setEnabled(false);
        jTable1.setRequestFocusEnabled(false);
        jTable1.setRowSelectionAllowed(false);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Resumo dos Lançamentos"));

        jLabel2.setText("Lançamentos");

        jTxtQtd.setEnabled(false);
        jTxtQtd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtQtdActionPerformed(evt);
            }
        });

        jLabel3.setText("Valor Bruto");

        jTxtVlrBruto.setEnabled(false);

        jTxtVlrFunrural.setEnabled(false);

        jLabel4.setText("Valor Funrural");

        jLabel5.setText("Valor Senar");

        jTxtVlrSenar.setEnabled(false);

        jTxtTotal.setEnabled(false);

        jLabel6.setText("Total");

        jLabel7.setText("Contabilidade");

        jTxtContabilidade.setEnabled(false);

        jLabel9.setText("Lançamentos");

        jTxtQtd1.setEnabled(false);
        jTxtQtd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtQtd1ActionPerformed(evt);
            }
        });

        jLabel10.setText("Valor Bruto");

        jTxtVlrBruto1.setEnabled(false);

        jLabel11.setText("Valor Funrural");

        jTxtVlrFunrural1.setEnabled(false);

        jLabel12.setText("Valor Senar");

        jTxtVlrSenar1.setEnabled(false);

        jLabel13.setText("Total");

        jTxtTotal1.setEnabled(false);

        jLabel14.setText("Folha de Pagamentos");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtVlrBruto, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtVlrFunrural, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtVlrSenar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtContabilidade, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtQtd1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtVlrBruto1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtVlrFunrural1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtVlrSenar1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(205, 205, 205))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 10, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTxtQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTxtVlrBruto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtVlrFunrural, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jTxtVlrSenar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jTxtContabilidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 10, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTxtQtd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jTxtVlrBruto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtVlrFunrural1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jTxtVlrSenar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1222, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        comp = jTxtCompetencia.getText();
        importar = jRadioButton1.isSelected();

        //MANIPULA E CONVERTE DATAS
        try {
            dti = dateIn.parse("01/" + comp);
            dtf = mData.lastDay(comp);
            buscaLancamentos();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

        somaFolhaPagamentos();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTxtQtdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtQtdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtQtdActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        integrar("I");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        integrar("E");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTxtQtd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtQtd1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtQtd1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        somaFolhaPagamentos();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void buscaLancamentos() {
        DefaultTableModel lista = montaTabela();

        ArrayList lancamentos = new ArrayList();

        sql = "select concat(a.codfil,a.NUMNOT) as lancamento from vetorh.R032PRD a where a.CMPPRD = '01/" + jTxtCompetencia.getText() + "'";
        if (cnor.conecta()) {
            try {
                cnor.executeConsulta(sql);
                while (cnor.rs.next()) {
                    lancamentos.add(cnor.rs.getString("lancamento"));
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            } finally {
                cnor.desconecta();
            }
        }

        int seq = 0;
        String codFil = "0";
        String totanalit = "A";

        sql = "with funrural as ( "
                + "select c.ESTABELEC as UNIDADE, c.dt_entrada as DATA,"
                + "b.nome as CLIENTE, b.CPF_CNPJ as insc_federal, "
                + "a.aliq_funrural as TX_FUNRURAL, a.aliq_senar as TX_SENAR,"
                + "a.valor_senar, case when c.dt_entrada <= '10.01.2018' and b.pessoa_fj = 'F' then a.vlr_contabil_item * 0.013 else a.valor_funrural end as valor_funrural, "
                + "a.total AS VLR_BRUTO, round((a.total * 0.10)/100,2) as RAT_CALC, "
                + "round((a.total * 0.20)/100,2) as SENAR_CALC, "
                + "round((a.total * 2.00)/100,2) as FUNRURAL_CALC, "
                + "ROUND((round((a.total * 0.10)/100,2) + round((a.total * 0.20)/100,2) + round((a.total * 2.00)/100,2) - a.VALOR_SENAR - a.VALOR_FUNRURAL),0) as DIFERENCA, "
                + "c.numero AS DOC, c.SERIE "
                + "from COM_ENTRADAS c "
                + "inner join COM_ENTRADAS_PRODUTOS a on (a.empresa=c.empresa and a.codigo=c.codigo and (a.OPERACAO in (1105,1109,1111,6207,6216,6217,6313,6869,6879,1108))) "
                + "left join CAD_TERCEIROS b on (c.empresa=b.empresa and a.fornecedor=b.codigo)  "
                + "where c.empresa = 1   "
                + "and (c.dt_entrada BETWEEN '" + dateIn.format(dti).replace("/", ".") + "' and '" + dateIn.format(dtf).replace("/", ".") + "')) "
                + "SELECT f.unidade, "
                + "         f.insc_federal, "
                + "         f.cliente, "
                + "         f.doc, "
                + "         f.serie, "
                + "         f.data, "
                + "         sum(f.vlr_bruto) as vlr_bruto, "
                + "         sum(f.valor_funrural) as valor_funrural, "
                + "         sum(f.valor_senar) as valor_senar "
                + "FROM funrural f "
                + "GROUP BY 1,2,3,4,5,6 "
                + "ORDER BY f.unidade, f.doc;";

        if (cnfb.conecta()) {
            try {
                cnfb.executeConsulta(sql);
                while (cnfb.rs.next()) {
                    //PESQUISA UNIDADE DA FOLHA
                    emp.codFilial("1", cnfb.rs.getString("unidade"), "CONTABIL", "0");

                    //VERIFICA SE LANÇAMENTO POSSUI FUNRURAL A CALCULAR
                    if ("0,00".equals(df.format(cnfb.rs.getDouble("valor_funrural")))
                            && "0,00".equals(df.format(cnfb.rs.getDouble("valor_senar")))) {
                        totanalit = "T";
                    } else if (lancamentos.contains(emp.getFilFolha() + cnfb.rs.getString("doc"))) {
                        totanalit = "O";
                    } else {
                        totanalit = "A";
                    }

                    // ALTERA A SEQUENCIA SE HOUVER FUNRURAL A LANÇAR
                    if (!"T".equals(totanalit)) {
                        if (codFil.equals(emp.getFilFolha())) {
                            seq++;
                        } else {
                            seq = 1;
                        }
                    }

                    lista.addRow(new String[]{
                        totanalit,
                        cnfb.rs.getString("unidade"),
                        emp.getFilFolha(),
                        cnfb.rs.getString("insc_federal"),
                        cnfb.rs.getString("cliente"),
                        cnfb.rs.getString("doc"),
                        cnfb.rs.getString("serie"),
                        dateIn.format(cnfb.rs.getDate("data")),
                        df.format(cnfb.rs.getDouble("vlr_bruto")),
                        df.format(cnfb.rs.getDouble("valor_funrural")),
                        df.format(cnfb.rs.getDouble("valor_senar")),
                        seq + ""

                    });

                    codFil = emp.getFilFolha();
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            } finally {
                cnfb.desconecta();
            }
        }

        somaLancamentos();
        somaContabilidade();
        verificaStatus();

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private static javax.swing.JTextField jTxtCompetencia;
    private javax.swing.JTextField jTxtContabilidade;
    private javax.swing.JTextField jTxtQtd;
    private javax.swing.JTextField jTxtQtd1;
    private javax.swing.JTextField jTxtTotal;
    private javax.swing.JTextField jTxtTotal1;
    private javax.swing.JTextField jTxtVlrBruto;
    private javax.swing.JTextField jTxtVlrBruto1;
    private javax.swing.JTextField jTxtVlrFunrural;
    private javax.swing.JTextField jTxtVlrFunrural1;
    private javax.swing.JTextField jTxtVlrSenar;
    private javax.swing.JTextField jTxtVlrSenar1;
    // End of variables declaration//GEN-END:variables

    private DefaultTableModel montaTabela() {
        DefaultTableModel lista = (DefaultTableModel) jTable1.getModel();

        lista.setColumnCount(0);
        lista.setRowCount(0);

        lista.addColumn("totanalit");
        lista.addColumn("Filial");
        lista.addColumn("Folha");
        lista.addColumn("Inscrição Federal");
        lista.addColumn("Produtor");
        lista.addColumn("Documento");
        lista.addColumn("Série");
        lista.addColumn("Emissão");
        lista.addColumn("Valor");
        lista.addColumn("Funrural");
        lista.addColumn("Senar");
        lista.addColumn("Seq");

        jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(0).setMinWidth(0);
        jTable1.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
        jTable1.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);
        jTable1.getColumnModel().getColumn(4).setMaxWidth(300);
        jTable1.getColumnModel().getColumn(4).setMinWidth(300);
        jTable1.getTableHeader().getColumnModel().getColumn(4).setMaxWidth(300);
        jTable1.getTableHeader().getColumnModel().getColumn(4).setMinWidth(300);
        jTable1.getColumnModel().getColumn(11).setMaxWidth(30);
        jTable1.getColumnModel().getColumn(11).setMinWidth(30);
        jTable1.getTableHeader().getColumnModel().getColumn(11).setMaxWidth(30);
        jTable1.getTableHeader().getColumnModel().getColumn(11).setMinWidth(30);

        jTable1.setDefaultRenderer(Object.class, new ColorRender());

        return lista;
    }

    private void somaLancamentos() {
        int qtd = 0;
        Double vlr_bruto = 0.00;
        Double vlr_funrural = 0.00;
        Double vlr_senar = 0.00;

        for (int i = 0; i < jTable1.getRowCount(); i++) {
            qtd++;

            vlr_bruto += Double.parseDouble(jTable1.getValueAt(i, 8).toString().replace(".", "").replace(",", "."));
            vlr_funrural += Double.parseDouble(jTable1.getValueAt(i, 9).toString().replace(".", "").replace(",", "."));
            vlr_senar += Double.parseDouble(jTable1.getValueAt(i, 10).toString().replace(".", "").replace(",", "."));

        }

        jTxtQtd.setText(qtd + "");
        jTxtVlrBruto.setText(df.format(vlr_bruto));
        jTxtVlrFunrural.setText(df.format(vlr_funrural));
        jTxtVlrSenar.setText(df.format(vlr_senar));
        jTxtTotal.setText(df.format(vlr_funrural + vlr_senar));

    }

    private void somaContabilidade() {
        String sql = "SELECT  a.estab_credito, b.nome, a.data, a.valor, a.complemento "
                + "from ctb_lancamentos a "
                + "left join cad_estabelecimentos b on (a.estab_credito = b.codigo and a.empresa = b.empresa) "
                + "where a.empresa = 1 and a.data BETWEEN '" + dateIn.format(dti).replace("/", ".") + "' and '" + dateIn.format(dtf).replace("/", ".") + "' "
                + "and a.credito = 1580 and a.origem != 'CTB';";

        Double vlr_cont = 0.00;

        if (cnfb.conecta()) {
            try {
                cnfb.executeConsulta(sql);

                while (cnfb.rs.next()) {
                    vlr_cont += cnfb.rs.getDouble("valor");
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            } finally {
                cnfb.desconecta();
            }
        }

        jTxtContabilidade.setText(df.format(vlr_cont));

    }

    private void verificaStatus() {

        int qtd = 0;

        for (int i = 0; i < jTable1.getRowCount(); i++) {
            if ("A".equals(jTable1.getValueAt(i, 0))) {
                qtd++;
            }
        }

        if (qtd == 0) {
            jTextField1.setText("INTEGRADO");
        } else {
            jTextField1.setText("PENDENTE");
        }

    }

    private void integrar(final String tipOpe) {
        final ImportFunrural p = this;

        new Thread() {
            String competencia = jTxtCompetencia.getText();
            int sequencia;
            int filial;
            String cpf;
            String cliente;
            String doc;
            String serie;
            String dt_emissao;
            Double vlr_bruto;
            Double funrural;
            String senar;
            TelaDeAvisos tela;

            public void run() {
                try {
                    tela = tela = new TelaDeAvisos();
                    tela.setMsgStatus("Exportando FUNRURAL para Folha de Pagamentos...", 0, 0);
                    p.setVisible(false);
                    for (int i = 0; i < jTable1.getRowCount(); i++) {

                        tela.setProgresso(i + 1, jTable1.getRowCount());

                        if (("A".equals(jTable1.getValueAt(i, 0).toString())
                                && "I".equals(tipOpe))
                                || ("O".equals(jTable1.getValueAt(i, 0).toString())
                                && "E".equals(tipOpe))) {
                            sequencia = Integer.parseInt(jTable1.getValueAt(i, 11).toString());
                            filial = Integer.parseInt(jTable1.getValueAt(i, 2).toString());
                            cpf = jTable1.getValueAt(i, 3).toString();
                            cliente = jTable1.getValueAt(i, 4).toString();
                            doc = jTable1.getValueAt(i, 5).toString();
                            serie = jTable1.getValueAt(i, 6).toString();
                            dt_emissao = jTable1.getValueAt(i, 7).toString();
                            vlr_bruto = Double.parseDouble(jTable1.getValueAt(i, 8).toString().replace(".", "").replace(",", "."));
                            funrural = Double.parseDouble(jTable1.getValueAt(i, 9).toString().replace(".", "").replace(",", "."));
                            senar = jTable1.getValueAt(i, 10).toString();

                            new IntegraFunrural(tipOpe, competencia, sequencia, filial, cpf, cliente, doc, serie, dt_emissao, vlr_bruto, funrural, senar);
                        }
                    }

                    tela.dispose();
                    JOptionPane.showMessageDialog(null, "Integração Concluída!");
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(p, e.getMessage());
                } finally {
                    tela.dispose();
                    p.setVisible(true);
                    montaTabela();
                }
            }
        }.start();

    }

    private void somaFolhaPagamentos() {

        int qtd = 0;
        Double vlr_bruto = 0.00;
        Double funrural = 0.00;
        Double senar = 0.00;
        Double rat = 0.00;

        String sql = " select count(*) as qtd, sum(a.RECBRU) as vlr_bruto, "
                + "sum(a.VALPRE) as funrural, sum(a.valfin) as rat, sum(a.VALSEN) as senar "
                + "from VETORH.r032prd a "
                + "WHERE a.CMPPRD = '01/" + jTxtCompetencia.getText() + "'";

        if (cnor.conecta()) {
            try {
                cnor.executeConsulta(sql);
                while (cnor.rs.next()) {
                    qtd = cnor.rs.getInt("qtd");
                    vlr_bruto = cnor.rs.getDouble("vlr_bruto");
                    funrural = cnor.rs.getDouble("funrural");
                    senar = cnor.rs.getDouble("senar");
                    rat = cnor.rs.getDouble("rat");
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            } finally {
                cnor.desconecta();
            }
        }

        jTxtQtd1.setText(qtd + "");
        jTxtVlrBruto1.setText(df.format(vlr_bruto));
        jTxtVlrFunrural1.setText(df.format(funrural + rat));
        jTxtVlrSenar1.setText(df.format(senar));
        jTxtTotal1.setText(df.format(senar + funrural + rat));

    }

}
