-- PRIMEIRA MUDANÇA NO BANCO DE DADOS
ALTER TABLE `fechamento`.`cad_setores` 
CHANGE COLUMN `cad_setorescol` `empresa` INT NULL DEFAULT NULL ,
CHANGE COLUMN `cta_estoque` `est_tot` INT(11) NULL DEFAULT NULL ,
CHANGE COLUMN `cta_compra_assoc` `est_comp_coop` INT(11) NULL DEFAULT NULL ,
CHANGE COLUMN `cta_compra_terc` `est_comp_terc` INT(11) NULL DEFAULT NULL ,
CHANGE COLUMN `cta_transf_prof` `est_transf_prod` INT(11) NULL DEFAULT NULL ,
CHANGE COLUMN `cta_consumo` `est_cons_int` INT(11) NULL DEFAULT NULL ,
CHANGE COLUMN `ctad_cmv_assoc` `res_repasse` INT(11) NULL DEFAULT NULL ,
CHANGE COLUMN `ctac_cmv_assoc` `est_custo_coop` INT(11) NULL DEFAULT NULL ,
CHANGE COLUMN `ctad_cmv_terc` `res_custo_terc` INT(11) NULL DEFAULT NULL ,
CHANGE COLUMN `ctac_cmv_terc` `est_custo_terc` INT(11) NULL DEFAULT NULL ,
ADD COLUMN `res_rec_int` INT NULL AFTER `controla_cmv`,
ADD COLUMN `res_rec_ext` INT NULL AFTER `res_rec_int`,
ADD COLUMN `res_out_rec` INT NULL AFTER `res_rec_ext`,
ADD COLUMN `res_bon_terc` INT NULL AFTER `res_out_rec`,
ADD COLUMN `res_icms_terc` INT NULL AFTER `res_bon_terc`,
ADD COLUMN `res_pis_terc` INT NULL AFTER `res_icms_terc`,
ADD COLUMN `res_cofins_terc` INT NULL AFTER `res_pis_terc`,
ADD COLUMN `res_iss_terc` INT NULL AFTER `res_cofins_terc`,
ADD COLUMN `res_ipi_terc` INT NULL AFTER `res_iss_terc`,
ADD COLUMN `res_dev_terc` INT NULL AFTER `res_ipi_terc`,
ADD COLUMN `res_ing_int` INT NULL AFTER `res_dev_terc`,
ADD COLUMN `res_ing_ext` INT NULL AFTER `res_ing_int`,
ADD COLUMN `res_out_ing` INT NULL AFTER `res_ing_ext`,
ADD COLUMN `res_bon_coop` INT NULL AFTER `res_out_ing`,
ADD COLUMN `res_icms_coop` INT NULL AFTER `res_bon_coop`,
ADD COLUMN `res_pis_coop` INT NULL AFTER `res_icms_coop`,
ADD COLUMN `res_cofins_coop` INT NULL AFTER `res_pis_coop`,
ADD COLUMN `res_iss_coop` INT NULL AFTER `res_cofins_coop`,
ADD COLUMN `res_ipi_coop` INT NULL AFTER `res_iss_coop`,
ADD COLUMN `res_dev_coop` INT NULL AFTER `res_ipi_coop`,
ADD COLUMN `est_ini` INT NULL AFTER `res_dev_coop`,
ADD COLUMN `est_descarte` INT NULL AFTER `est_ini`,
ADD COLUMN `est_prov_aq` INT NULL AFTER `est_descarte`,
ADD COLUMN `est_transf_e` INT NULL AFTER `est_prov_aq`,
ADD COLUMN `est_tem` INT NULL AFTER `est_transf_e`,
ADD COLUMN `est_perda` INT NULL AFTER `est_tem`,
ADD COLUMN `est_dev_coop` INT NULL AFTER `est_perda`,
ADD COLUMN `est_dev_terc` INT NULL AFTER `est_dev_coop`,
ADD COLUMN `est_transf_s` INT NULL AFTER `est_dev_terc`,
ADD COLUMN `est_bon_coop` INT NULL AFTER `est_transf_s`,
ADD COLUMN `est_bon_terc` INT NULL AFTER `est_bon_coop`,
ADD COLUMN `est_terc_tot` INT NULL AFTER `est_bon_terc`,
ADD COLUMN `est_terc_fix` INT NULL AFTER `est_terc_tot`,
ADD COLUMN `est_terc_fix_dps` INT NULL AFTER `est_terc_fix`,
ADD COLUMN `est_terc` INT NULL AFTER `est_terc_fix_dps`,
ADD COLUMN `est_terc_dps` INT NULL AFTER `est_terc`,
ADD COLUMN `est_terc_cons` INT NULL AFTER `est_terc_dps`,
ADD COLUMN `est_prop_tot` INT NULL AFTER `est_terc_cons`,
ADD COLUMN `est_prop_fut` INT NULL AFTER `est_prop_tot`,
ADD COLUMN `est_prop_con_or` INT NULL AFTER `est_prop_fut`;

-- SEGUNDA MUDANÇA
UPDATE fechamento.cad_setores SET EMPRESA = 1 where id > 0;

-- TERCEIRA MUDANÇA
ALTER TABLE `fechamento`.`cad_setores` 
CHANGE COLUMN `empresa` `empresa` INT(11) NOT NULL FIRST,
CHANGE COLUMN `est_ini` `est_ini` INT(11) NULL DEFAULT NULL AFTER `est_tot`,
CHANGE COLUMN `est_descarte` `est_descarte` INT(11) NULL DEFAULT NULL AFTER `est_comp_terc`,
CHANGE COLUMN `est_prov_aq` `est_prov_aq` INT(11) NULL DEFAULT NULL AFTER `est_descarte`,
CHANGE COLUMN `est_transf_e` `est_transf_e` INT(11) NULL DEFAULT NULL AFTER `est_prov_aq`,
CHANGE COLUMN `est_tem` `est_rem` INT(11) NULL DEFAULT NULL AFTER `est_transf_e`,
CHANGE COLUMN `est_perda` `est_perda` INT(11) NULL DEFAULT NULL AFTER `est_rem`,
CHANGE COLUMN `est_dev_coop` `est_dev_coop` INT(11) NULL DEFAULT NULL AFTER `est_perda`,
CHANGE COLUMN `est_dev_terc` `est_dev_terc` INT(11) NULL DEFAULT NULL AFTER `est_dev_coop`,
CHANGE COLUMN `est_custo_coop` `est_custo_coop` INT(11) NULL DEFAULT NULL AFTER `est_dev_terc`,
CHANGE COLUMN `est_custo_terc` `est_custo_terc` INT(11) NULL DEFAULT NULL AFTER `est_custo_coop`,
CHANGE COLUMN `est_transf_s` `est_transf_s` INT(11) NULL DEFAULT NULL AFTER `est_custo_terc`,
CHANGE COLUMN `est_bon_coop` `est_bon_coop` INT(11) NULL DEFAULT NULL AFTER `est_transf_s`,
CHANGE COLUMN `est_bon_terc` `est_bon_terc` INT(11) NULL DEFAULT NULL AFTER `est_bon_coop`,
CHANGE COLUMN `est_terc_tot` `est_terc_tot` INT(11) NULL DEFAULT NULL AFTER `est_cons_int`,
CHANGE COLUMN `est_terc_fix` `est_terc_fix` INT(11) NULL DEFAULT NULL AFTER `est_terc_tot`,
CHANGE COLUMN `est_terc_fix_dps` `est_terc_fix_dps` INT(11) NULL DEFAULT NULL AFTER `est_terc_fix`,
CHANGE COLUMN `est_terc` `est_terc` INT(11) NULL DEFAULT NULL AFTER `est_terc_fix_dps`,
CHANGE COLUMN `est_terc_dps` `est_terc_dps` INT(11) NULL DEFAULT NULL AFTER `est_terc`,
CHANGE COLUMN `est_terc_cons` `est_terc_cons` INT(11) NULL DEFAULT NULL AFTER `est_terc_dps`,
CHANGE COLUMN `est_prop_tot` `est_prop_tot` INT(11) NULL DEFAULT NULL AFTER `est_terc_cons`,
CHANGE COLUMN `est_prop_fut` `est_prop_fut` INT(11) NULL DEFAULT NULL AFTER `est_prop_tot`,
CHANGE COLUMN `est_prop_con_or` `est_prop_con_or` INT(11) NULL DEFAULT NULL AFTER `est_prop_fut`,
CHANGE COLUMN `res_custo_terc` `res_custo_terc` INT(11) NULL DEFAULT NULL AFTER `res_dev_terc`,
CHANGE COLUMN `res_repasse` `res_repasse` INT(11) NULL DEFAULT NULL AFTER `res_dev_coop`,
CHANGE COLUMN `controla_cmv` `controla_cmv` INT(11) NULL DEFAULT NULL AFTER `res_repasse`,
DROP PRIMARY KEY,
ADD PRIMARY KEY (`empresa`, `id`);

-- QUARTA MUDANÇA
ALTER TABLE `fechamento`.`cad_setores` 
ADD COLUMN `est_prod_acabado` INT NULL AFTER `est_prop_con_or`,
ADD COLUMN `prod_tot` INT NULL AFTER `controla_cmv`,
ADD COLUMN `prod_mp` INT NULL AFTER `prod_tot`,
ADD COLUMN `prod_embalagem` INT NULL AFTER `prod_mp`,
ADD COLUMN `prod_insumos` INT NULL AFTER `prod_embalagem`,
ADD COLUMN `prod_custo_fixo` INT NULL AFTER `prod_insumos`,
ADD COLUMN `prod_transf_e` INT NULL AFTER `prod_custo_fixo`,
ADD COLUMN `prod_transf_s` INT NULL AFTER `prod_transf_e`,
ADD COLUMN `prod_acabado` INT NULL AFTER `prod_transf_s`
ADD COLUMN `producao` TINYINT NOT NULL DEFAULT 0 AFTER `prod_acabado`;
