/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TelaCadastros;

import conn.ConexaoFB;
import conn.ConexaoMySQL;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public final class CadAtividades extends javax.swing.JInternalFrame {

    private String sql;

    /**
     * Creates new form CadAtividades
     */
    public CadAtividades(ConexaoMySQL conn) {
        initComponents();
        this.cn = conn;
        MontaLista();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTipoAtv = new javax.swing.JComboBox();
        txtClassificacaoAtv = new javax.swing.JTextField();
        txtNomeAtv = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescricaoAtv = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        txtPesquisar = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPeriodoAtv = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        txtDtInclAtv = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtIniAtv = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtFimAtv = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtDependenciaAtv = new javax.swing.JComboBox();
        txtCodAtv = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnCadastrarAtv = new javax.swing.JButton();
        btnEditarAtv = new javax.swing.JButton();
        btnCancelarAtv = new javax.swing.JButton();
        btnExpirarAtv = new javax.swing.JButton();
        btnGravarAtv = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabCadAtividades = new javax.swing.JTable();
        txtStatusAtv = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jPasswordField1.setText("jPasswordField1");

        setClosable(true);
        setIconifiable(true);
        setTitle("Cadastro de Atividades");

        jLabel1.setText("Tipo");

        jLabel2.setText("Classificação");

        jLabel3.setText("Atividade");

        jLabel4.setText("Descrição");

        txtTipoAtv.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ANALITICA", "SINTETICA" }));
        txtTipoAtv.setToolTipText("Contas Analíticas recebem Lançamentos. Contas Sintéticas agrupam contas Analíticas.");
        txtTipoAtv.setEnabled(false);
        txtTipoAtv.setNextFocusableComponent(txtClassificacaoAtv);

        txtClassificacaoAtv.setToolTipText("Informe a qual código pertence a atividade");
        txtClassificacaoAtv.setEnabled(false);
        txtClassificacaoAtv.setNextFocusableComponent(txtPeriodoAtv);

        txtNomeAtv.setToolTipText("Informe um nome reduzido para a atividade.");
        txtNomeAtv.setEnabled(false);
        txtNomeAtv.setNextFocusableComponent(txtDescricaoAtv);

        txtDescricaoAtv.setColumns(20);
        txtDescricaoAtv.setLineWrap(true);
        txtDescricaoAtv.setRows(5);
        txtDescricaoAtv.setToolTipText("Informe detalhes sobre a atividade.");
        txtDescricaoAtv.setEnabled(false);
        txtDescricaoAtv.setNextFocusableComponent(txtIniAtv);
        jScrollPane1.setViewportView(txtDescricaoAtv);

        jLabel5.setText("Código");

        txtPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarKeyReleased(evt);
            }
        });

        jLabel6.setText("Periodicidade");

        txtPeriodoAtv.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DIARIO", "SEMANAL", "MENSAL", "ANUAL", "EVENTUAL" }));
        txtPeriodoAtv.setEnabled(false);
        txtPeriodoAtv.setNextFocusableComponent(txtNomeAtv);

        jLabel7.setText("Inclusão");

        txtDtInclAtv.setEnabled(false);

        jLabel9.setText("Início da vigência");

        txtIniAtv.setEnabled(false);

        jLabel10.setText("Expiração");

        txtFimAtv.setEnabled(false);

        jLabel11.setText("Dependência");

        txtDependenciaAtv.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NAO HA" }));
        txtDependenciaAtv.setEnabled(false);

        txtCodAtv.setText("              ");

        btnCadastrarAtv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Cadastrar.png"))); // NOI18N
        btnCadastrarAtv.setText("Cadastrar");
        btnCadastrarAtv.setToolTipText("Incluir nova atividade.");
        btnCadastrarAtv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarAtvActionPerformed(evt);
            }
        });

        btnEditarAtv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Editar.png"))); // NOI18N
        btnEditarAtv.setText("Editar");
        btnEditarAtv.setToolTipText("Editar os dados mostrados.");
        btnEditarAtv.setEnabled(false);
        btnEditarAtv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarAtvActionPerformed(evt);
            }
        });

        btnCancelarAtv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Cancelar.png"))); // NOI18N
        btnCancelarAtv.setText("Cancelar");
        btnCancelarAtv.setToolTipText("Cancelar todas as modificações.");
        btnCancelarAtv.setEnabled(false);
        btnCancelarAtv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarAtvActionPerformed(evt);
            }
        });

        btnExpirarAtv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Expirado.png"))); // NOI18N
        btnExpirarAtv.setText("Expirar");
        btnExpirarAtv.setToolTipText("Declarar que atividade não precisa mais ser realizada.");
        btnExpirarAtv.setEnabled(false);
        btnExpirarAtv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExpirarAtvActionPerformed(evt);
            }
        });

        btnGravarAtv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Gravar.png"))); // NOI18N
        btnGravarAtv.setText("Gravar");
        btnGravarAtv.setToolTipText("Grava os dados");
        btnGravarAtv.setEnabled(false);
        btnGravarAtv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarAtvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnGravarAtv, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCadastrarAtv, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnEditarAtv, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancelarAtv, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnExpirarAtv, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCadastrarAtv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEditarAtv)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancelarAtv)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGravarAtv)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExpirarAtv)
                .addGap(85, 85, 85))
        );

        tabCadAtividades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabCadAtividades.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabCadAtividades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabCadAtividadesMouseClicked(evt);
            }
        });
        tabCadAtividades.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabCadAtividadesKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tabCadAtividades);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
        );

        txtStatusAtv.setText("    ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPesquisar)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtDtInclAtv)
                                            .addComponent(txtDependenciaAtv, 0, 109, Short.MAX_VALUE))
                                        .addGap(90, 90, 90)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtIniAtv, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                            .addComponent(txtFimAtv)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtClassificacaoAtv, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(83, 83, 83)
                                .addComponent(txtStatusAtv))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(26, 26, 26)
                                .addComponent(txtNomeAtv, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCodAtv)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTipoAtv, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPeriodoAtv, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, 0)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtCodAtv)
                            .addComponent(jLabel1)
                            .addComponent(txtTipoAtv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(txtPeriodoAtv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtClassificacaoAtv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtStatusAtv))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtNomeAtv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane1)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtDependenciaAtv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtIniAtv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtDtInclAtv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtFimAtv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private final ConexaoFB cnfb = new ConexaoFB();
    private ConexaoMySQL cn;
    
    DefaultTableModel lista = new DefaultTableModel();
    
    public void MontaLista() {
        
        if (!"".equals(txtPesquisar.getText())) {
            lista.setColumnCount(0);  //limpa a tabela
            lista.setRowCount(0);     //limpa a tabela

            try {
                cn.iniciarTransacao();
                String sql = "SELECT * FROM cad_atividades "
                        + "WHERE UPPER(nome) "
                        + "LIKE '%" + txtPesquisar.getText().toUpperCase() + "%' OR descricao "
                        + "LIKE '%" + txtPesquisar.getText() + "%'"
                        + " ORDER BY nome";
                
                cn.executeConsulta(sql);
                
                lista.addColumn("Código");
                lista.addColumn("Nome");
                lista.addColumn("Descição");
                lista.addColumn("Tipo");
                lista.addColumn("Periodicidade");
                lista.addColumn("Dependencia");
                lista.addColumn("Classificação");
                
                while (cn.rs.next()) {
                    
                    lista.addRow(new String[]{
                        cn.rs.getString("codigo"),
                        cn.rs.getString("nome"),
                        cn.rs.getString("descricao"),
                        cn.rs.getString("tipo"),
                        cn.rs.getString("periodicidade"),
                        cn.rs.getString("dependencia"),
                        cn.rs.getString("classificacao")});
                }
            } catch (SQLException ex) {
                
                JOptionPane.showMessageDialog(null, "Erro ao consultar o banco de dados: " + ex);
            } finally {
                cn.finalizarTransacao();
            }
            
            tabCadAtividades.setModel(lista);
            /* Abaixo, configuração para ocultar colunas na jTable
             * Porém, quando clica, aparecem os dados para edição e consulta
             */
            tabCadAtividades.getColumnModel().getColumn(2).setMaxWidth(0);
            tabCadAtividades.getColumnModel().getColumn(2).setMinWidth(0);
            tabCadAtividades.getTableHeader().getColumnModel().getColumn(2).setMaxWidth(0);
            tabCadAtividades.getTableHeader().getColumnModel().getColumn(2).setMinWidth(0);
            tabCadAtividades.getColumnModel().getColumn(0).setMaxWidth(0);
            tabCadAtividades.getColumnModel().getColumn(0).setMinWidth(0);
            tabCadAtividades.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
            tabCadAtividades.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);
            
        } else { //Configuração para quando não há texto no campo pesquisa
            lista.setColumnCount(0);  //limpa a tabela
            lista.setRowCount(0);     //limpa a tabela
            cn.iniciarTransacao();
            String sql = "SELECT * FROM cad_atividades "
                    + " ORDER BY classificacao";
            
            try {
                cn.executeConsulta(sql);
                
                lista.addColumn("Código");
                lista.addColumn("Nome");
                lista.addColumn("Descrição");
                lista.addColumn("Tipo");
                lista.addColumn("Periodicidade");
                lista.addColumn("Dependencia");
                lista.addColumn("Classificação");
                
                while (cn.rs.next()) {
                    
                    lista.addRow(new String[]{
                        cn.rs.getString("codigo"),
                        cn.rs.getString("nome"),
                        cn.rs.getString("descricao"),
                        cn.rs.getString("tipo"),
                        cn.rs.getString("periodicidade"),
                        cn.rs.getString("dependencia"),
                        cn.rs.getString("classificacao")});
                    
                }
            } catch (SQLException ex) {
                
                JOptionPane.showMessageDialog(null, "Erro ao consultar o banco de dados: " + ex);
            } finally {
                cn.finalizarTransacao();
                
            }
            tabCadAtividades.setModel(lista);

            /* Abaixo, configuração para ocultar colunas na jTable
             * Porém, quando clica, aparecem os dados para edição e consulta
             */
            tabCadAtividades.getColumnModel().getColumn(2).setMaxWidth(0);
            tabCadAtividades.getColumnModel().getColumn(2).setMinWidth(0);
            tabCadAtividades.getTableHeader().getColumnModel().getColumn(2).setMaxWidth(0);
            tabCadAtividades.getTableHeader().getColumnModel().getColumn(2).setMinWidth(0);
            tabCadAtividades.getColumnModel().getColumn(0).setMaxWidth(0);
            tabCadAtividades.getColumnModel().getColumn(0).setMinWidth(0);
            tabCadAtividades.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
            tabCadAtividades.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);

            //Configuração dos botões, quando não há pesquisa
            btnEditarAtv.setEnabled(false);
            btnCadastrarAtv.setEnabled(true);
        }
    }
    
    public void Selecao() {
        
        int linha = tabCadAtividades.getSelectedRow();
        
        txtCodAtv.setText(tabCadAtividades.getValueAt(linha, 0).toString());
        txtNomeAtv.setText(tabCadAtividades.getValueAt(linha, 1).toString());
        txtDescricaoAtv.setText(tabCadAtividades.getValueAt(linha, 2).toString());
        txtTipoAtv.setSelectedItem(tabCadAtividades.getValueAt(linha, 3).toString());
        txtPeriodoAtv.setSelectedItem(tabCadAtividades.getValueAt(linha, 4).toString());
        txtDependenciaAtv.setSelectedItem(tabCadAtividades.getValueAt(linha, 5).toString());
        txtClassificacaoAtv.setText(tabCadAtividades.getValueAt(linha, 6).toString());
    }

    private void btnCancelarAtvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarAtvActionPerformed
        // TODO add your handling code here:
        txtClassificacaoAtv.setEnabled(false);
        txtCodAtv.setText(" ");
        txtStatusAtv.setText(" ");
        txtClassificacaoAtv.setText("");
        txtPesquisar.setText("");
        txtDependenciaAtv.setEnabled(false);
        txtDescricaoAtv.setEnabled(false);
        txtIniAtv.setEnabled(false);
        txtNomeAtv.setEnabled(false);
        txtPeriodoAtv.setEnabled(false);
        txtPesquisar.setEnabled(true);
        txtTipoAtv.setEnabled(false);
        btnCancelarAtv.setEnabled(false);
        btnGravarAtv.setEnabled(false);
        btnEditarAtv.setEnabled(false);
        btnCadastrarAtv.setEnabled(true);
    }//GEN-LAST:event_btnCancelarAtvActionPerformed

    private void btnEditarAtvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarAtvActionPerformed
        txtStatusAtv.setText("ALTERANDO");
        txtClassificacaoAtv.setEnabled(true);
        txtDependenciaAtv.setEnabled(true);
        txtDescricaoAtv.setEnabled(true);
        txtIniAtv.setEnabled(true);
        txtNomeAtv.setEnabled(true);
        txtPeriodoAtv.setEnabled(true);
        txtPesquisar.setEnabled(false);
        txtTipoAtv.setEnabled(true);
        btnCancelarAtv.setEnabled(true);
        btnGravarAtv.setEnabled(true);
        btnCadastrarAtv.setEnabled(false);
        btnEditarAtv.setEnabled(false);
    }//GEN-LAST:event_btnEditarAtvActionPerformed

    private void txtPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarKeyReleased
        MontaLista();
    }//GEN-LAST:event_txtPesquisarKeyReleased

    private void btnCadastrarAtvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarAtvActionPerformed
        // TODO add your handling code here:
        Calendar calendar = new GregorianCalendar();
        SimpleDateFormat out = new SimpleDateFormat("yyyy/MM/dd");
        Date date = new Date();
        calendar.setTime(date);
        
        String iData = out.format(calendar.getTime());
        
        txtCodAtv.setText("NOVO");
        txtStatusAtv.setText("CADASTRANDO");
        txtDescricaoAtv.setText("");
        txtIniAtv.setText("");
        txtFimAtv.setText("");
        txtNomeAtv.setText("");
        txtClassificacaoAtv.setEnabled(true);
        txtDependenciaAtv.setEnabled(true);
        txtDescricaoAtv.setEnabled(true);
        txtIniAtv.setEnabled(true);
        txtNomeAtv.setEnabled(true);
        txtPeriodoAtv.setEnabled(true);
        txtPesquisar.setEnabled(false);
        txtTipoAtv.setEnabled(true);
        txtDtInclAtv.setText(iData);
        btnCancelarAtv.setEnabled(true);
        btnGravarAtv.setEnabled(true);
        btnCadastrarAtv.setEnabled(false);
    }//GEN-LAST:event_btnCadastrarAtvActionPerformed

    private void btnGravarAtvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarAtvActionPerformed
        // TODO add your handling code here:
        if (!"".equals(txtClassificacaoAtv.getText())
                && !"".equals(txtNomeAtv.getText())
                && !"".equals(txtDescricaoAtv.getText()) /*&& !"".equals(txtIniAtv.getText())*/) {
            
            String classAtv = txtClassificacaoAtv.getText();
            String dependAtv = txtDependenciaAtv.getSelectedItem().toString();
            String descrAtv = txtDescricaoAtv.getText();
            String nomeAtv = txtNomeAtv.getText();
            String tipoAtv = txtTipoAtv.getSelectedItem().toString();
            String dtIncAtv = txtDtInclAtv.getText();
            String dtFimAtv = txtFimAtv.getText();
            String perAtv = txtPeriodoAtv.getSelectedItem().toString();
            String dtCad = txtDtInclAtv.getText();
            //String statusAtv = txtStatusAtv.getText();

            try {
                cn.iniciarTransacao();
                if (txtStatusAtv.getText() == "CADASTRANDO") {
                    sql = "INSERT INTO CAD_ATIVIDADES (NOME, CLASSIFICACAO, TIPO, DESCRICAO, PERIODICIDADE, DEPENDENCIA, DATA_CADASTRO, DATA_INI_VIGENCIA) VALUES ('" + nomeAtv + "','" + classAtv + "','" + tipoAtv + "','" + descrAtv + "','" + perAtv + "','" + dependAtv + "','" + dtCad + "','" + dtIncAtv + "')";
                } else {
                    sql = "UPDATE CAD_ATIVIDADES SET NOME = '" + nomeAtv + "', CLASSIFICACAO = '" + classAtv + "', TIPO = '" + tipoAtv + "', DESCRICAO = '" + descrAtv + "', PERIODICIDADE = '" + perAtv + "', DEPENDENCIA = '" + dependAtv + "' WHERE codigo = " + Integer.parseInt(txtCodAtv.getText());
                    //        + "(NOME, DEPARTAMENTO, FUNCAO, ATIVO) VALUES ('" + nomeUser
                }
                    cn.executeAtualizacao(sql);
            } catch (SQLException e) {
                tools.DefaultMsg.errorMsg(e.getMessage());
            } finally {
                cn.finalizarTransacao();
            }
            
            txtClassificacaoAtv.setEnabled(false);
            txtCodAtv.setText(" ");
            txtStatusAtv.setText(" ");
            txtDependenciaAtv.setEnabled(false);
            txtDescricaoAtv.setEnabled(false);
            txtIniAtv.setEnabled(false);
            txtNomeAtv.setEnabled(false);
            txtPeriodoAtv.setEnabled(false);
            txtPesquisar.setEnabled(true);
            txtTipoAtv.setEnabled(false);
            btnCancelarAtv.setEnabled(false);
            btnGravarAtv.setEnabled(false);
            btnCadastrarAtv.setEnabled(true);
            MontaLista();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Algum campo está em Branco.");
        }
    }//GEN-LAST:event_btnGravarAtvActionPerformed

    private void tabCadAtividadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabCadAtividadesMouseClicked
        btnEditarAtv.setEnabled(true);
        Selecao();
    }//GEN-LAST:event_tabCadAtividadesMouseClicked

    private void tabCadAtividadesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabCadAtividadesKeyReleased
        Selecao();
    }//GEN-LAST:event_tabCadAtividadesKeyReleased

    private void btnExpirarAtvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExpirarAtvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExpirarAtvActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarAtv;
    private javax.swing.JButton btnCancelarAtv;
    private javax.swing.JButton btnEditarAtv;
    private javax.swing.JButton btnExpirarAtv;
    private javax.swing.JButton btnGravarAtv;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabCadAtividades;
    private javax.swing.JTextField txtClassificacaoAtv;
    private javax.swing.JLabel txtCodAtv;
    private javax.swing.JComboBox txtDependenciaAtv;
    private javax.swing.JTextArea txtDescricaoAtv;
    private javax.swing.JTextField txtDtInclAtv;
    private javax.swing.JTextField txtFimAtv;
    private javax.swing.JTextField txtIniAtv;
    private javax.swing.JTextField txtNomeAtv;
    private javax.swing.JComboBox txtPeriodoAtv;
    private javax.swing.JTextField txtPesquisar;
    private javax.swing.JLabel txtStatusAtv;
    private javax.swing.JComboBox<String> txtTipoAtv;
    // End of variables declaration//GEN-END:variables

}
