/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TelaCadastros;

import conn.ConexaoMySQL;
import tools.ColorRender;
import tools.IntegraFinanceiro;
import tools.ManipulaData;
import tools.ProvisoesEncargosFolha;
import tools.TelaDeAvisos;
import java.text.DecimalFormat;
import java.text.ParseException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author luiz.barcellos
 */
public class IntegraEncargos extends javax.swing.JInternalFrame {

    private final ConexaoMySQL cn;
    private MaskFormatter competencia;
    private final ProvisoesEncargosFolha prov;
    private String sql;
    private final DecimalFormat df = new DecimalFormat("#,##0.00");
    //private final IntegraFinanceiro integ;
    private final ManipulaData mData = new ManipulaData();

    /**
     * Creates new form IntegraEncargos
     */
    public IntegraEncargos(ConexaoMySQL conn) {

        try {
            competencia = new javax.swing.text.MaskFormatter("##/####");
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

        //this.integ = new IntegraFinanceiro(conn, false);
        this.prov = new ProvisoesEncargosFolha(conn);
        this.cn = conn;
        initComponents();
        montaTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTxtCompetencia = new javax.swing.JFormattedTextField(competencia);
        jButton1 = new javax.swing.JButton();
        jRbFGTS = new javax.swing.JRadioButton();
        jRbINSS = new javax.swing.JRadioButton();
        jRbPIS = new javax.swing.JRadioButton();
        jRbIRRF = new javax.swing.JRadioButton();
        jRbPensao = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jRbFUNRURAL = new javax.swing.JRadioButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jRbINSS1 = new javax.swing.JRadioButton();
        jRbIRRF1 = new javax.swing.JRadioButton();
        jRbFGTS2 = new javax.swing.JRadioButton();
        jRbIRRF2 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Provisão de Encargos");

        jLabel1.setText("Competência");

        jTxtCompetencia.setNextFocusableComponent(jRbFGTS);
        jTxtCompetencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtCompetenciaKeyPressed(evt);
            }
        });

        jButton1.setText("Pesquisar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });

        buttonGroup1.add(jRbFGTS);
        jRbFGTS.setText("FGTS");
        jRbFGTS.setNextFocusableComponent(jCheckBox1);
        jRbFGTS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jRbFGTSKeyPressed(evt);
            }
        });

        buttonGroup1.add(jRbINSS);
        jRbINSS.setText("INSS");
        jRbINSS.setNextFocusableComponent(jCheckBox1);
        jRbINSS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jRbINSSKeyPressed(evt);
            }
        });

        buttonGroup1.add(jRbPIS);
        jRbPIS.setText("PIS");
        jRbPIS.setNextFocusableComponent(jCheckBox1);
        jRbPIS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jRbPISKeyPressed(evt);
            }
        });

        buttonGroup1.add(jRbIRRF);
        jRbIRRF.setText("IRRF");
        jRbIRRF.setNextFocusableComponent(jCheckBox1);
        jRbIRRF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jRbIRRFKeyPressed(evt);
            }
        });

        buttonGroup1.add(jRbPensao);
        jRbPensao.setText("Pensão Judicial");
        jRbPensao.setEnabled(false);
        jRbPensao.setNextFocusableComponent(jCheckBox1);

        jButton2.setText("Lançar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Estornar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRbFUNRURAL);
        jRbFUNRURAL.setText("FUNRURAL");
        jRbFUNRURAL.setNextFocusableComponent(jCheckBox1);
        jRbFUNRURAL.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jRbFUNRURALKeyPressed(evt);
            }
        });

        jCheckBox1.setText("Sincronizar");
        jCheckBox1.setNextFocusableComponent(jButton1);
        jCheckBox1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jCheckBox1KeyPressed(evt);
            }
        });

        buttonGroup1.add(jRbINSS1);
        jRbINSS1.setText("INSS Terceiros");
        jRbINSS1.setEnabled(false);
        jRbINSS1.setNextFocusableComponent(jCheckBox1);
        jRbINSS1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jRbINSS1KeyPressed(evt);
            }
        });

        buttonGroup1.add(jRbIRRF1);
        jRbIRRF1.setText("IRRF Terceiros");
        jRbIRRF1.setNextFocusableComponent(jCheckBox1);
        jRbIRRF1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jRbIRRF1KeyPressed(evt);
            }
        });

        buttonGroup1.add(jRbFGTS2);
        jRbFGTS2.setSelected(true);
        jRbFGTS2.setText("FGTS Terceiros");
        jRbFGTS2.setEnabled(false);
        jRbFGTS2.setNextFocusableComponent(jCheckBox1);
        jRbFGTS2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jRbFGTS2KeyPressed(evt);
            }
        });

        buttonGroup1.add(jRbIRRF2);
        jRbIRRF2.setText("Contribuições Retidas na Fonte");
        jRbIRRF2.setNextFocusableComponent(jCheckBox1);
        jRbIRRF2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jRbIRRF2KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtCompetencia, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jRbFGTS)
                        .addGap(18, 18, 18)
                        .addComponent(jRbINSS)
                        .addGap(18, 18, 18)
                        .addComponent(jRbFUNRURAL)
                        .addGap(18, 18, 18)
                        .addComponent(jRbPIS)
                        .addGap(18, 18, 18)
                        .addComponent(jRbPensao)
                        .addGap(85, 85, 85)
                        .addComponent(jCheckBox1)
                        .addGap(16, 16, 16)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jRbFGTS2)
                        .addGap(18, 18, 18)
                        .addComponent(jRbINSS1)
                        .addGap(18, 18, 18)
                        .addComponent(jRbIRRF)
                        .addGap(18, 18, 18)
                        .addComponent(jRbIRRF1)
                        .addGap(18, 18, 18)
                        .addComponent(jRbIRRF2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxtCompetencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jRbFGTS)
                    .addComponent(jRbINSS)
                    .addComponent(jRbPIS)
                    .addComponent(jRbPensao)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jRbFUNRURAL)
                    .addComponent(jCheckBox1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRbINSS1)
                    .addComponent(jRbIRRF)
                    .addComponent(jRbIRRF1)
                    .addComponent(jRbFGTS2)
                    .addComponent(jRbIRRF2)))
        );

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setEnabled(false);
        jScrollPane1.setViewportView(jTable1);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Resumo"));

        jLabel2.setText("Lançamentos");

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField1.setEnabled(false);

        jLabel3.setText("Valor");

        jTextField2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField2.setEnabled(false);

        jTextField3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField3.setEnabled(false);

        jLabel4.setText("Contábil");

        jTextField4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField4.setEnabled(false);

        jLabel6.setText("Diferença");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel2)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel3)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel4)
                .addComponent(jLabel5)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel6))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String encargo;
        String competencia = jTxtCompetencia.getText();
        String contaContabil = "";

        if (jRbFGTS.isSelected()) {
            encargo = "FGTS";
            contaContabil = "1573";
        } else if (jRbINSS.isSelected()) {
            encargo = "INSS";
            contaContabil = "1579";
        } else if (jRbFUNRURAL.isSelected()) {
            encargo = "FUNRURAL";
            contaContabil = "1580";
        } else if (jRbPIS.isSelected()) {
            encargo = "PIS";
            contaContabil = "1581";
        } else if (jRbIRRF.isSelected()) {
            encargo = "IRRF";
            contaContabil = "56699";
        } else if (jRbPensao.isSelected()) {
            encargo = "PENSAO";
            contaContabil = "36104";
        } else if (jRbIRRF1.isSelected()) {
            encargo = "IRRF_T";
            contaContabil = "1563";
        } else if (jRbIRRF2.isSelected()) {
            encargo = "CONTR_T";
            contaContabil = "10841";
        } else {
            encargo = "";
        }
        try {

            if (jCheckBox1.isSelected()) {
                switch (encargo) {
                    case "FGTS":
                        prov.consultaFGTS(competencia);
                        break;

                    case "INSS":
                        prov.consultaINSS(competencia);
                        break;

                    case "FUNRURAL":
                        prov.consultaFUNRURAL(competencia);
                        break;

                    case "PIS":
                        prov.consultaPIS(competencia);

                        break;

                    case "IRRF":
                        prov.consultaIRRF(competencia);

                        break;
                    case "IRRF_T":
                        prov.consultaProvContabil(competencia, encargo, contaContabil);
                        
                        break;
                    case "CONTR_T":
                        prov.consultaProvContabil(competencia, encargo, contaContabil);
                        
                        break;

                    case "PENSAO":

                        break;

                    default:
                        throw new UnsupportedOperationException("Selecione um encargo válido para continuar.");
                }

            }
            prov.consultaContabil(competencia, contaContabil);
            jTextField3.setText(tools.FormatNumbers.numUsToBr(prov.getSaldoContabil()));
            jLabel5.setText("Conta: " + prov.getContaContabil());

            incluiPesquisa(encargo);

            jTextField4.setText(tools.FormatNumbers.numUsToBr(
                    Double.parseDouble(jTextField2.getText().replace(".", "").replace(",", "."))
                    - Double.parseDouble(jTextField3.getText().replace(".", "").replace(",", "."))
            ));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        try {

            if (jTable1.getRowCount() == 0) {
                throw new Exception();
            }

            if (!jTextField4.getText().equals("0,00")) {
                if (JOptionPane.showConfirmDialog(this, "Há diferença entre a provisão e o Razão Contábil.\nDeseja continuar?", "Integração Financeira", JOptionPane.YES_NO_OPTION) == 1) {
                    throw new Exception();
                }
            }
            //JOptionPane.showMessageDialog(this, "Dados gravados.");
            gravarDados(true);
        } catch (Exception e) {
            System.out.println("Sem dados para integrar com o financeiro.");
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTxtCompetenciaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtCompetenciaKeyPressed
        tools.AcaoPadrao.acaoPadraoTeclado(evt, jTxtCompetencia, this);
    }//GEN-LAST:event_jTxtCompetenciaKeyPressed

    private void jRbFGTSKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jRbFGTSKeyPressed
        tools.AcaoPadrao.acaoPadraoTeclado(evt, jRbFGTS, this);
    }//GEN-LAST:event_jRbFGTSKeyPressed

    private void jRbINSSKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jRbINSSKeyPressed
        tools.AcaoPadrao.acaoPadraoTeclado(evt, jRbINSS, this);
    }//GEN-LAST:event_jRbINSSKeyPressed

    private void jRbFUNRURALKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jRbFUNRURALKeyPressed
        tools.AcaoPadrao.acaoPadraoTeclado(evt, jRbFUNRURAL, this);
    }//GEN-LAST:event_jRbFUNRURALKeyPressed

    private void jRbPISKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jRbPISKeyPressed
        tools.AcaoPadrao.acaoPadraoTeclado(evt, jRbPIS, this);
    }//GEN-LAST:event_jRbPISKeyPressed

    private void jRbIRRFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jRbIRRFKeyPressed
        tools.AcaoPadrao.acaoPadraoTeclado(evt, jRbIRRF, this);
    }//GEN-LAST:event_jRbIRRFKeyPressed

    private void jCheckBox1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCheckBox1KeyPressed
        tools.AcaoPadrao.acaoPadraoTeclado(evt, jCheckBox1, this);        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1KeyPressed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        tools.AcaoPadrao.acaoPadraoTeclado(evt, jButton1, this);
    }//GEN-LAST:event_jButton1KeyPressed

    private void jRbINSS1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jRbINSS1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRbINSS1KeyPressed

    private void jRbIRRF1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jRbIRRF1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRbIRRF1KeyPressed

    private void jRbFGTS2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jRbFGTS2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRbFGTS2KeyPressed

    private void jRbIRRF2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jRbIRRF2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRbIRRF2KeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRbFGTS;
    private javax.swing.JRadioButton jRbFGTS2;
    private javax.swing.JRadioButton jRbFUNRURAL;
    private javax.swing.JRadioButton jRbINSS;
    private javax.swing.JRadioButton jRbINSS1;
    private javax.swing.JRadioButton jRbIRRF;
    private javax.swing.JRadioButton jRbIRRF1;
    private javax.swing.JRadioButton jRbIRRF2;
    private javax.swing.JRadioButton jRbPIS;
    private javax.swing.JRadioButton jRbPensao;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JFormattedTextField jTxtCompetencia;
    // End of variables declaration//GEN-END:variables

    private DefaultTableModel montaTabela() {
        DefaultTableModel lista = (DefaultTableModel) jTable1.getModel();

        lista.setColumnCount(0);
        lista.setRowCount(0);

        lista.addColumn("Encargo");
        lista.addColumn("Competência");
        lista.addColumn("Unidade");
        lista.addColumn("Código");
        lista.addColumn("Valor");
        lista.addColumn("Financeiro");

        jTable1.setDefaultRenderer(Object.class, new ColorRender());

        return lista;
    }

    private void incluiPesquisa(String encargo) {
        DefaultTableModel lista = montaTabela();

        sql = "SELECT a.encargo, a.competencia, a.nomfil, a.unidade, a.financeiro, sum(a.valeve) as valeve "
                + "FROM fechamento.folha_provisao a "
                + "WHERE a.competencia = '" + jTxtCompetencia.getText() + "' "
                + "AND a.encargo = '" + encargo + "' "
                + "GROUP BY a.nomfil;";

        if (cn.iniciarTransacao()) {
            try {
                cn.executeConsulta(sql);
                while (cn.rs.next()) {
                    lista.addRow(new String[]{
                        cn.rs.getString("encargo"),
                        cn.rs.getString("competencia"),
                        cn.rs.getString("nomfil"),
                        cn.rs.getString("unidade"),
                        df.format(cn.rs.getDouble("valeve")),
                        cn.rs.getString("financeiro")
                    });
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            } finally {
                cn.finalizarTransacao();
            }
        }
        somaDados();
    }

    private void somaDados() {
        int qtd = 0;
        Double total = 0.00;

        for (int i = 0; i < jTable1.getRowCount(); i++) {
            qtd++;
            total += Double.parseDouble(jTable1.getValueAt(i, 4).toString().replace(".", "").replace(",", "."));
        }

        jTextField1.setText(qtd + "");
        jTextField2.setText(df.format(total));

    }

    private void gravarDados(final boolean b) {

        final IntegraEncargos p = this;
        p.setVisible(false);

        new Thread() {
            public void run() {
                TelaDeAvisos tela = null;
                try {
                    tela = new TelaDeAvisos();

                    System.out.println("\nPreparando para gravar dados.");
                    String competencia = jTxtCompetencia.getText();
                    String unidade;
                    String valor;
                    String encargo = "";
                    String financeiro = "";

                    tela.setMsgStatus("Gravando financeiro...", 0, 0);
                    gravar:
                    for (int i = 0; i < jTable1.getRowCount(); i++) {
                        tela.setProgresso(i + 1, jTable1.getRowCount());

                        System.out.println("Carregando variáveis.");
                        encargo = jTable1.getValueAt(i, 0).toString();
                        competencia = jTable1.getValueAt(i, 1).toString();
                        unidade = jTable1.getValueAt(i, 3).toString();
                        valor = jTable1.getValueAt(i, 4).toString().replace(".", "").replace(",", ".");

                        try {
                            financeiro = jTable1.getValueAt(i, 5).toString();
                        } catch (Exception e) {
                            financeiro = "";
                        }

                        System.out.println("Varíáveis carregadas.");

                        if ((financeiro == null || financeiro == "") && b) {
                            System.out.println("Chamando classe de lançamentos.");
                            if (prov.lancaFinanceiro(unidade, valor, competencia, encargo) == false) {
                                break gravar;
                            }
                        } else if ((financeiro != null || financeiro != "") && b == false) {
                            if (prov.deletaFinanceiro(financeiro) == false) {
                                break gravar;
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "A tabela não contém dados financeiros válidos.");

                            break gravar;
                        }
                    }

                    incluiPesquisa(encargo);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());
                } finally {
                    tela.dispose();
                    p.setVisible(true);
                }
            }
        }.start();
    }
}
