/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import calendar.IntFrm_RegDepartment;
import calendar.IntFrm_RegPerson;
import calendar.IntFrm_TaxStatements;
import calendar.IntFrm_schedule_category;
import conn.ConexaoFB;
import conn.ConexaoMySQL;
import dirf.FrmExportaDirf;
import finQuadroSocial.IntFrm_DevolCota;
import financiamentos.IntFrm_CadBens;
import financiamentos.IntFrm_Financ_Garantias;
import java.awt.Dimension;
import java.io.FileInputStream;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.util.Properties;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import lancamentos.IntFrm_UpdCity;
import ocepar.AjustarAgilBalancoSocial;
import sped_ecd_ecf.IntFrm_PlanoReferencial;

/**
 *
 * @author Luiz Fernando Dill Barcellos
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    private String usuario;
    
    private String arquivo = "./src/properties/default.properties";
    private Properties props = new Properties();

    //private final ConexaoFB cnfb = new ConexaoFB();
    public ConexaoMySQL cn = new ConexaoMySQL();

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        defineBD();
        try {
            ConexaoMySQL.tela = this;
            System.out.println("Tela atribuída para a conexao.");
            
            cn.conecta();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        
        try {
            jLabel5.setText(InetAddress.getLocalHost().getHostAddress().toString());
        } catch (UnknownHostException ex) {
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jAreaDeTrabalho = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTxtBdMySQL = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTxtBdFb = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jArquivo = new javax.swing.JMenu();
        jEmpresa = new javax.swing.JMenuItem();
        jEmpresa1 = new javax.swing.JMenuItem();
        jSair = new javax.swing.JMenuItem();
        jManutencao = new javax.swing.JMenu();
        mnuAtividades = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        mnuPrazos = new javax.swing.JMenuItem();
        mnuPrazos1 = new javax.swing.JMenuItem();
        jMenu15 = new javax.swing.JMenu();
        mnuPrazos5 = new javax.swing.JMenuItem();
        jMenuItem55 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        mnuPrazos2 = new javax.swing.JMenuItem();
        jMenu14 = new javax.swing.JMenu();
        jMenuItem51 = new javax.swing.JMenuItem();
        mnuPrazos3 = new javax.swing.JMenuItem();
        mnuPrazos4 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem42 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem26 = new javax.swing.JMenuItem();
        jMenuItem27 = new javax.swing.JMenuItem();
        jMenuItem28 = new javax.swing.JMenuItem();
        jMenuItem56 = new javax.swing.JMenuItem();
        jMenuItem33 = new javax.swing.JMenuItem();
        jMenuItem47 = new javax.swing.JMenuItem();
        jMenuItem31 = new javax.swing.JMenuItem();
        jMenuItem29 = new javax.swing.JMenuItem();
        jMenuItem32 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu12 = new javax.swing.JMenu();
        jMenuItem39 = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem37 = new javax.swing.JMenuItem();
        jMenuItem35 = new javax.swing.JMenuItem();
        jMenuItem36 = new javax.swing.JMenuItem();
        jMenuItem38 = new javax.swing.JMenuItem();
        jMenu13 = new javax.swing.JMenu();
        jMenuItem43 = new javax.swing.JMenuItem();
        jMenuItem44 = new javax.swing.JMenuItem();
        jMenuItem45 = new javax.swing.JMenuItem();
        jMenuItem50 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem40 = new javax.swing.JMenuItem();
        jMenuItem46 = new javax.swing.JMenuItem();
        jMenuItem52 = new javax.swing.JMenuItem();
        jMenuItem54 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem25 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem24 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItem41 = new javax.swing.JMenuItem();
        jMenuItem48 = new javax.swing.JMenuItem();
        jRelatorios = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jSobre1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem30 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem34 = new javax.swing.JMenuItem();
        jMenuItem49 = new javax.swing.JMenuItem();
        jMenuItem53 = new javax.swing.JMenuItem();
        jSobre = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fechamento Contábil");

        jPanel1.setMinimumSize(new java.awt.Dimension(50, 50));

        jAreaDeTrabalho.setBackground(new java.awt.Color(102, 102, 102));
        jAreaDeTrabalho.setPreferredSize(new java.awt.Dimension(800, 600));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jAreaDeTrabalho, javax.swing.GroupLayout.DEFAULT_SIZE, 1123, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jAreaDeTrabalho, javax.swing.GroupLayout.DEFAULT_SIZE, 676, Short.MAX_VALUE)
        );

        jLabel1.setText("Banco de Dados MySQL");

        jTxtBdMySQL.setEnabled(false);

        jButton1.setText("Alternar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Alternar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTxtBdFb.setEnabled(false);

        jLabel2.setText("Banco de Dados Firebird");

        jTextField1.setEnabled(false);

        jLabel3.setText("Fb:");

        jLabel4.setText("MySQL:");

        jTextField2.setEnabled(false);

        jLabel5.setText("jLabel5");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtBdMySQL, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtBdFb, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(jTxtBdMySQL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton1)
                .addComponent(jLabel2)
                .addComponent(jTxtBdFb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton2)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel3)
                .addComponent(jLabel4)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel5))
        );

        jArquivo.setText("Arquivo");
        jArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jArquivoActionPerformed(evt);
            }
        });

        jEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Empresa.png"))); // NOI18N
        jEmpresa.setText("Empresa");
        jEmpresa.setToolTipText("Cadastro das empresas onde será controlado o progresso do fechamento contábil.");
        jEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEmpresaActionPerformed(evt);
            }
        });
        jArquivo.add(jEmpresa);

        jEmpresa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/setup.png"))); // NOI18N
        jEmpresa1.setText("Configurações");
        jEmpresa1.setToolTipText("Cadastro das empresas onde será controlado o progresso do fechamento contábil.");
        jEmpresa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEmpresa1ActionPerformed(evt);
            }
        });
        jArquivo.add(jEmpresa1);

        jSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Sair.png"))); // NOI18N
        jSair.setText("Sair");
        jSair.setToolTipText("Sair do sistema.");
        jSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSairActionPerformed(evt);
            }
        });
        jArquivo.add(jSair);

        jMenuBar1.add(jArquivo);

        jManutencao.setText("Manutenção");

        mnuAtividades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Atividades.png"))); // NOI18N
        mnuAtividades.setText("Atividades");
        mnuAtividades.setToolTipText("Relação de atividades mensais necessárias ao fechamento da contabilidade.");
        mnuAtividades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAtividadesActionPerformed(evt);
            }
        });
        jManutencao.add(mnuAtividades);

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Responsaveis.png"))); // NOI18N
        jMenuItem5.setText("Pessoas");
        jMenuItem5.setToolTipText("Vinculação das atividades aos usuários.");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jManutencao.add(jMenuItem5);

        mnuPrazos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Prazos.png"))); // NOI18N
        mnuPrazos.setText("Prazos");
        mnuPrazos.setToolTipText("Cadastro de prazos ideais para encerramento de cada atividade.");
        mnuPrazos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPrazosActionPerformed(evt);
            }
        });
        jManutencao.add(mnuPrazos);

        mnuPrazos1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lancPadroes.png"))); // NOI18N
        mnuPrazos1.setText("Lancamentos Padrões");
        mnuPrazos1.setToolTipText("Cadastro de lançamentos padrões para a geração de lançamentos automáticos.");
        mnuPrazos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPrazos1ActionPerformed(evt);
            }
        });
        jManutencao.add(mnuPrazos1);

        jMenu15.setText("SPED");

        mnuPrazos5.setText("Plano de Contas Referencial");
        mnuPrazos5.setToolTipText("");
        mnuPrazos5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPrazos5ActionPerformed(evt);
            }
        });
        jMenu15.add(mnuPrazos5);

        jManutencao.add(jMenu15);

        jMenuItem55.setText("Bens");
        jMenuItem55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem55ActionPerformed(evt);
            }
        });
        jManutencao.add(jMenuItem55);
        jManutencao.add(jSeparator4);

        mnuPrazos2.setText("Setores");
        mnuPrazos2.setToolTipText("");
        mnuPrazos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPrazos2ActionPerformed(evt);
            }
        });
        jManutencao.add(mnuPrazos2);

        jMenu14.setText("Calendário");

        jMenuItem51.setText("Categorias");
        jMenuItem51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem51ActionPerformed(evt);
            }
        });
        jMenu14.add(jMenuItem51);

        jManutencao.add(jMenu14);

        mnuPrazos3.setText("Departamentos");
        mnuPrazos3.setToolTipText("");
        mnuPrazos3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPrazos3ActionPerformed(evt);
            }
        });
        jManutencao.add(mnuPrazos3);

        mnuPrazos4.setText("Obrigações Fiscais");
        mnuPrazos4.setToolTipText("");
        mnuPrazos4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPrazos4ActionPerformed(evt);
            }
        });
        jManutencao.add(mnuPrazos4);

        jMenuBar1.add(jManutencao);

        jMenu1.setText("Movimentação");

        jMenuItem2.setText("Movimentar Atividade");
        jMenu1.add(jMenuItem2);
        jMenu1.add(jSeparator2);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quebra.png"))); // NOI18N
        jMenu5.setText("Quebra Técnica");

        jMenuItem3.setText("Calcular Quebra");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem3);

        jMenuItem13.setText("Ajustar Cadastros");
        jMenuItem13.setToolTipText("Ajusta os cadastros que envolvem estoques, para fins de emissão de relatórios.");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem13);

        jMenuItem14.setText("Lançar Quebra Técnica");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem14);

        jMenu1.add(jMenu5);

        jMenu2.setText("Despesas Antecipadas");

        jMenuItem4.setText("Importação de Lançamentos");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem6.setText("Calcular Amortizações");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem15.setText("Apropriar Despesas");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem15);
        jMenu2.add(jSeparator1);

        jMenuItem16.setText("Ajusta Lancamentos Antigos");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem16);

        jMenu1.add(jMenu2);

        jMenu3.setText("Custo da Produção");

        jMenuItem42.setText("Ajuste Custo Consignações");
        jMenuItem42.setToolTipText("Analisa as importações e gera os lançamentos de acordo com as regras de lançamentos padrões.");
        jMenuItem42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem42ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem42);

        jMenuItem18.setText("Importação de Disponibilidades");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem18);

        jMenu6.setText("Provisão para aquisição de estoque");

        jMenuItem19.setText("Tipos de Produtos");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem19);

        jMenuItem20.setText("Preço de Mercado");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem20);

        jMenuItem21.setText("Lançamento de Preços");
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem21ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem21);

        jMenu3.add(jMenu6);

        jMenuItem8.setText("Importação de Ordens");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem8);

        jMenuItem9.setText("Importação de Apuração");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem9);

        jMenu1.add(jMenu3);

        jMenu10.setText("Financiamentos");

        jMenuItem26.setText("Modalidades");
        jMenuItem26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem26ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem26);

        jMenuItem27.setText("Bancos");
        jMenu10.add(jMenuItem27);

        jMenuItem28.setText("Manutenção de Contratos");
        jMenuItem28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem28ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem28);

        jMenuItem56.setText("Garantias");
        jMenuItem56.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem56ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem56);

        jMenuItem33.setText("Importar Arquivo");
        jMenuItem33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem33ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem33);

        jMenuItem47.setText("Lançamento Manual de Juros");
        jMenuItem47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem47ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem47);

        jMenuItem31.setText("Saldos");
        jMenuItem31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem31ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem31);

        jMenuItem29.setText("Cálculo de Juros");
        jMenuItem29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem29ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem29);

        jMenuItem32.setText("Lançamento Financeiro");
        jMenuItem32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem32ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem32);

        jMenu1.add(jMenu10);

        jMenu4.setText("Fidelização");

        jMenuItem10.setText("Provisões");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem10);

        jMenuItem11.setText("Pagamentos");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem11);

        jMenu1.add(jMenu4);

        jMenu12.setText("FUNRURAL");

        jMenuItem39.setText("Lançamento e Integração");
        jMenuItem39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem39ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem39);

        jMenu1.add(jMenu12);

        jMenu11.setText("Deemed Cost");

        jMenuItem37.setText("Resumo dos Lançamentos");
        jMenuItem37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem37ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem37);

        jMenuItem35.setText("Combinação de Lançamentos");
        jMenuItem35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem35ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem35);

        jMenuItem36.setText("Baixas por Alienação");
        jMenuItem36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem36ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem36);

        jMenuItem38.setText("Apropriação Mensal");
        jMenuItem38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem38ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem38);

        jMenu1.add(jMenu11);

        jMenu13.setText("Lançamentos Contábeis");

        jMenuItem43.setText("Liberação de Lançamentos");
        jMenuItem43.setToolTipText("Libera os Lançamentos Contábeis de acordo com a conta informada");
        jMenuItem43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem43ActionPerformed(evt);
            }
        });
        jMenu13.add(jMenuItem43);

        jMenuItem44.setText("Alteração de Lançamentos");
        jMenuItem44.setToolTipText("Altera os as contas débito e crédito em lote");
        jMenuItem44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem44ActionPerformed(evt);
            }
        });
        jMenu13.add(jMenuItem44);

        jMenuItem45.setText("Bloqueio de Lançamentos");
        jMenuItem45.setToolTipText("Bloqueia o período contábil para todas as unidades para a mesma data");
        jMenuItem45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem45ActionPerformed(evt);
            }
        });
        jMenu13.add(jMenuItem45);

        jMenuItem50.setText("Altera Municípios Entradas");
        jMenuItem50.setToolTipText("Bloqueia o período contábil para todas as unidades para a mesma data");
        jMenuItem50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem50ActionPerformed(evt);
            }
        });
        jMenu13.add(jMenuItem50);

        jMenu1.add(jMenu13);

        jMenuItem12.setText("Lançamentos de PIS/COFINS");
        jMenuItem12.setToolTipText("Analisa as importações e gera os lançamentos de acordo com as regras de lançamentos padrões.");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem12);

        jMenuItem40.setText("Provisão Encargos Sociais");
        jMenuItem40.setToolTipText("Analisa as importações e gera os lançamentos de acordo com as regras de lançamentos padrões.");
        jMenuItem40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem40ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem40);

        jMenuItem46.setText("Aplicações Financeiras");
        jMenuItem46.setToolTipText("Analisa as importações e gera os lançamentos de acordo com as regras de lançamentos padrões.");
        jMenuItem46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem46ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem46);

        jMenuItem52.setText("Demissões de Cooperados");
        jMenuItem52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem52ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem52);

        jMenuItem54.setText("Receita de Frete");
        jMenuItem54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem54ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem54);
        jMenu1.add(jSeparator3);

        jMenuItem25.setText("Importar Inventário");
        jMenuItem25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem25ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem25);

        jMenuItem23.setText("Importar Balancete");
        jMenuItem23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem23ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem23);

        jMenu7.setText("Agil - Balanço Social");

        jMenu8.setText("Agropecuario");

        jMenuItem22.setText("jMenuItem22");
        jMenu8.add(jMenuItem22);

        jMenu7.add(jMenu8);

        jMenu9.setText("Transporte");

        jMenuItem24.setText("Dados Econômicos");
        jMenuItem24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem24ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem24);

        jMenu7.add(jMenu9);

        jMenu1.add(jMenu7);
        jMenu1.add(jSeparator5);

        jMenuItem41.setText("Exportação Domínio Sistemas");
        jMenuItem41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem41ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem41);

        jMenuItem48.setText("Exportação DIRF");
        jMenuItem48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem48ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem48);

        jMenuBar1.add(jMenu1);

        jRelatorios.setText("Relatórios");

        jMenuItem7.setText("Desempenho");
        jRelatorios.add(jMenuItem7);

        jMenuBar1.add(jRelatorios);

        jSobre1.setText("Utilitários");

        jMenuItem1.setText("Fornecedores para Contratos");
        jMenuItem1.setEnabled(false);
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jSobre1.add(jMenuItem1);

        jMenuItem30.setText("TipoDoc para Contratos");
        jMenuItem30.setEnabled(false);
        jMenuItem30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem30ActionPerformed(evt);
            }
        });
        jSobre1.add(jMenuItem30);

        jMenuItem17.setText("Ajusta IP");
        jMenuItem17.setEnabled(false);
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jSobre1.add(jMenuItem17);

        jMenuItem34.setText("Sincroniza Memorandos");
        jMenuItem34.setEnabled(false);
        jMenuItem34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem34ActionPerformed(evt);
            }
        });
        jSobre1.add(jMenuItem34);

        jMenuItem49.setText("Ajusta Saldos OCEPAR");
        jMenuItem49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem49ActionPerformed(evt);
            }
        });
        jSobre1.add(jMenuItem49);

        jMenuItem53.setText("Sincroniza Despesas Antecipadas");
        jMenuItem53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem53ActionPerformed(evt);
            }
        });
        jSobre1.add(jMenuItem53);

        jMenuBar1.add(jSobre1);

        jSobre.setText("Sobre");
        jMenuBar1.add(jSobre);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSairActionPerformed
        try {
            cn.desconecta();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
        System.exit(0);
    }//GEN-LAST:event_jSairActionPerformed

    private void jArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jArquivoActionPerformed

    }//GEN-LAST:event_jArquivoActionPerformed

    private void mnuAtividadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAtividadesActionPerformed
        // TODO add your handling code here:
        abreTelaInterna(new TelaCadastros.CadAtividades(cn));
    }//GEN-LAST:event_mnuAtividadesActionPerformed

    private void mnuPrazosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPrazosActionPerformed
        abreTelaInterna(new TelaCadastros.CadPrazos(cn));

    }//GEN-LAST:event_mnuPrazosActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        abreTelaInterna(new TelaCadastros.QuebraTecnica(cn));

    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void mnuPrazos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPrazos1ActionPerformed
        abreTelaInterna(new TelaCadastros.LancamentosPadroes(cn));

    }//GEN-LAST:event_mnuPrazos1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        abreTelaInterna(new TelaCadastros.DespAntecipada(cn));

    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        abreTelaInterna(new TelaCadastros.AmortDespAnt(cn));

    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        /*
        with
    produtos as (
        select
        prod.empresa,
        prod.codigo ||' - ' ||prod.nome as Cod_Produto,
        prod.codigo,
        prod.nome,
        prod.nome_reduzido,
        prod.marca,
        s.nome as setor,
s.codigo as cod_setor,
        ps.peneira,
        ps.cultivar,
        prod.class_gerencial,
        case when prod.tipo_item_sped = '00' then '00 - Mercadoria p/ Revenda'
             when prod.tipo_item_sped = '01' then '01 - Matéria-Prima'
             when prod.tipo_item_sped = '02' then '02 - Embalagens'
             when prod.tipo_item_sped = '03' then '03 - Produto em Processo'
             when prod.tipo_item_sped = '04' then '04 - Produto Acabado'
             when prod.tipo_item_sped = '05' then '05 - Sub-Produto'
             when prod.tipo_item_sped = '06' then '06 - Produto Intermediário'
             when prod.tipo_item_sped = '07' then '07 - Material de Uso e Consumo'
             when prod.tipo_item_sped = '08' then '08 - Ativo Imobilizado'
             when prod.tipo_item_sped = '09' then '09 - Serviços'
             when prod.tipo_item_sped = '10' then '10 - Outros Insumos'
             when prod.tipo_item_sped = '99' then '99 - Outras'
             end as tipo_item,

        coalesce(u.cus_grandeza,1) as grandeza,
        coalesce(ub.cus_grandeza,1) as conversao

        from
        cad_produtos prod
        inner join cad_unidades u on (prod.empresa=u.empresa and prod.unidade=u.codigo)
        inner join cad_setores s on (prod.empresa=s.empresa and prod.setor=s.codigo)
        left join cad_unidades ub on (prod.empresa=ub.empresa and prod.unidade_base=ub.codigo)
        left join cad_produtos_sementes ps on (prod.empresa=ps.empresa and prod.codigo=ps.codigo)

    ),


    materia_prima as (

        select
        m.codigo as ordem,
m.data_inc,
m.data_baixa,
        lpad(o.estabelec,2,0) || ' - ' || e.nome as estabelec,
        case when o.producao_interna = 'I' then 'Beneficiada'
             when o.producao_interna = 'F' then 'Ensacada'
             when o.producao_interna = 'M' then 'Movimentada'
             else 'Ensacada' end as tipo_ordem,
        case when o.centro_custos is null then '00 - Não informado' else lpad(o.centro_custos,2,0) || ' - ' || cc.nome end as centro_custos,
        m.codigo || ' - ' || pp.nome as desc_producao,
        pp.codigo as cod_produzido,
        pp.nome  as produto_produzido,
        pp.setor as setor_produzido,
        pp.cod_setor as cod_setor_pp,
        mp.nome  as materia_prima,
        s.nome as setor_materia_prima,
        s.codigo as cod_setor_mp,
        case when m.sequencia = (select first 1 (m1.sequencia) from prod_ordem_prod_produtos m1 where m.empresa=m1.empresa and m.codigo=m1.codigo) then (p.quantidade * pp.grandeza / pp.conversao) else 0 end as qtd_produzida,
        (m.quantidade) as qtd_mp,
        m.unitario,
        m.vlr_total as total_mp
        
        from
        prod_ordem_prod_produtos m
        join prod_ordem_producao o on (m.empresa=o.empresa and m.codigo=o.codigo)
        join cad_produtos mp on (m.empresa=mp.empresa and m.produto=mp.codigo)
        join cad_setores s on (mp.empresa=s.empresa and mp.setor=s.codigo)
        join prod_op_produtos_produzidos p on (m.empresa=p.empresa and m.codigo=p.codigo and m.produto_produzido=p.sequencia)
        join produtos pp on (p.empresa=pp.empresa and p.produto=pp.codigo)
        left join cad_estabelecimentos e on (o.empresa=e.empresa and o.estabelec=e.codigo)
        left join cad_ccustos cc on (o.empresa=cc.empresa and o.centro_custos=cc.codigo)

        where (o.data >=? and o.data <=?) 

    )

    SELECT * FROM MATERIA_PRIMA M;
        
         */
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        abreTelaInterna(new fidelizacao.fidelizacao_lcto(cn));        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        abreTelaInterna(new TelaCadastros.ApropriaPisCofins(cn));

    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        //new AtualizaFornecedores();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        abreTelaInterna(new TelaCadastros.AjustaCadastros(cn));

    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        abreTelaInterna(new TelaCadastros.QuebraTecnicaLcto(cn));

    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        abreTelaInterna(new TelaCadastros.ApropriarDespesas(cn));

    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        abreTelaInterna(new TelaCadastros.LancamentosAntigos(cn));

    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jEmpresa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEmpresa1ActionPerformed
        TelaCadastros.ConfConexao x = new TelaCadastros.ConfConexao();
        jAreaDeTrabalho.add(x);
        centralizaForm(x);
        x.setVisible(true);
    }//GEN-LAST:event_jEmpresa1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            java.io.FileOutputStream out = new java.io.FileOutputStream(arquivo);
            if ("PRODUÇÃO".equals(jTxtBdMySQL.getText())) {
                props.setProperty("bd_mysql_default", "mysqlcasa.properties");
            } else {
                props.setProperty("bd_mysql_default", "mysql.properties");
            }
            props.store(out, "");
            out.close();
            
            defineBD();
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            java.io.FileOutputStream out = new java.io.FileOutputStream(arquivo);
            if ("PRODUÇÃO".equals(jTxtBdFb.getText())) {
                props.setProperty("bd_fb_default", "fbcasa.properties");
            } else {
                props.setProperty("bd_fb_default", "fb.properties");
            }
            props.store(out, "");
            out.close();
            
            defineBD();
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        TelaCadastros.AjustaIP x = new TelaCadastros.AjustaIP();
        jAreaDeTrabalho.add(x);
        centralizaForm(x);
        x.setVisible(true);
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        abreTelaInterna(new TelaCadastros.Import_disp(cn));

    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        abreTelaInterna(new TelaCadastros.CadTiposProdutos(cn));

    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        abreTelaInterna(new TelaCadastros.PrecoMercado(cn));

    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void jMenuItem21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem21ActionPerformed
        abreTelaInterna(new TelaCadastros.PrecoMercadoLcto(cn));

    }//GEN-LAST:event_jMenuItem21ActionPerformed

    private void jEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEmpresaActionPerformed

    private void jMenuItem23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem23ActionPerformed
        abreTelaInterna(new TelaCadastros.ImportaBalancete(cn));
    }//GEN-LAST:event_jMenuItem23ActionPerformed

    private void jMenuItem24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem24ActionPerformed
        abreTelaInterna(new TelaCadastros.DadosEconomicosTransp(cn));
    }//GEN-LAST:event_jMenuItem24ActionPerformed

    private void mnuPrazos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPrazos2ActionPerformed
        abreTelaInterna(new TelaCadastros.CadSetor(cn));
    }//GEN-LAST:event_mnuPrazos2ActionPerformed

    private void jMenuItem25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem25ActionPerformed
        abreTelaInterna(new TelaCadastros.ImportaInventario(cn));
    }//GEN-LAST:event_jMenuItem25ActionPerformed

    private void jMenuItem28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem28ActionPerformed
        abreTelaInterna(new financiamentos.Fin_Contratos(cn));
    }//GEN-LAST:event_jMenuItem28ActionPerformed

    private void jMenuItem31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem31ActionPerformed
        abreTelaInterna(new financiamentos.UtilSaldoContrato(cn));
    }//GEN-LAST:event_jMenuItem31ActionPerformed

    private void jMenuItem29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem29ActionPerformed
        abreTelaInterna(new financiamentos.Fin_Juros(cn));
    }//GEN-LAST:event_jMenuItem29ActionPerformed

    private void jMenuItem30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem30ActionPerformed
        //new AtualizaFornecedores(false);
    }//GEN-LAST:event_jMenuItem30ActionPerformed

    private void jMenuItem32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem32ActionPerformed
        abreTelaInterna(new financiamentos.FinLançaJuros(cn));
    }//GEN-LAST:event_jMenuItem32ActionPerformed

    private void jMenuItem33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem33ActionPerformed
        abreTelaInterna(new financiamentos.FinImportarCsvJuros(cn));        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem33ActionPerformed

    private void jMenuItem34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem34ActionPerformed
        //new ExportaMemorandos();        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem34ActionPerformed

    private void jMenuItem35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem35ActionPerformed
        abreTelaInterna(new TelaCadastros.DeemedCost(cn));
    }//GEN-LAST:event_jMenuItem35ActionPerformed

    private void jMenuItem36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem36ActionPerformed
        // TODO add your handling code here:
        abreTelaInterna(new TelaCadastros.DeemedCost_baixa(cn));
    }//GEN-LAST:event_jMenuItem36ActionPerformed

    private void jMenuItem37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem37ActionPerformed
        // TODO add your handling code here:
        abreTelaInterna(new TelaCadastros.DeemedCost_Resumo(cn));
    }//GEN-LAST:event_jMenuItem37ActionPerformed

    private void jMenuItem38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem38ActionPerformed
        // TODO add your handling code here:
        abreTelaInterna(new TelaCadastros.DeemedCost_Lctos(cn));
    }//GEN-LAST:event_jMenuItem38ActionPerformed

    private void jMenuItem39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem39ActionPerformed
        abreTelaInterna(new funrural.ImportFunrural(cn));        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem39ActionPerformed

    private void jMenuItem40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem40ActionPerformed
        abreTelaInterna(new TelaCadastros.IntegraEncargos(cn));        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem40ActionPerformed

    private void jMenuItem26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem26ActionPerformed
        abreTelaInterna(new financiamentos.Fin_Modalidades(cn));        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem26ActionPerformed

    private void jMenuItem41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem41ActionPerformed
        abreTelaInterna(new dominiosistemas.Exporta_DomSis(this));
    }//GEN-LAST:event_jMenuItem41ActionPerformed

    private void jMenuItem42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem42ActionPerformed
        abreTelaInterna(new custoMedio.IntFrm_AjusteCustoMedio());
    }//GEN-LAST:event_jMenuItem42ActionPerformed

    private void jMenuItem43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem43ActionPerformed
        abreTelaInterna(new lancamentos.IntFrm_LiberaLancamentos());
    }//GEN-LAST:event_jMenuItem43ActionPerformed

    private void jMenuItem44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem44ActionPerformed
        abreTelaInterna(new lancamentos.IntFrm_AlteraLancamentos());        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem44ActionPerformed

    private void jMenuItem45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem45ActionPerformed
        abreTelaInterna(new lancamentos.IntFrm_BloqueiaPeriodo());        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem45ActionPerformed

    private void jMenuItem46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem46ActionPerformed
        abreTelaInterna(new finInvestments.IntFrm_Investments());        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem46ActionPerformed

    private void jMenuItem47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem47ActionPerformed
        abreTelaInterna(new financiamentos.IntFrmLancaJurosManual(cn));
    }//GEN-LAST:event_jMenuItem47ActionPerformed

    private void jMenuItem48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem48ActionPerformed
        abreTelaInterna(new FrmExportaDirf());        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem48ActionPerformed

    private void jMenuItem49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem49ActionPerformed
        try {
            new AjustarAgilBalancoSocial();
            JOptionPane.showMessageDialog(this, "Saldos atualizados com sucesso!", "Ajustar Saldo Balancete OCEPAR", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e, "Ajustar Saldo Balancete OCEPAR", JOptionPane.ERROR_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem49ActionPerformed

    private void jMenuItem50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem50ActionPerformed
        abreTelaInterna(new IntFrm_UpdCity());        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem50ActionPerformed

    private void jMenuItem51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem51ActionPerformed
        abreTelaInterna(new IntFrm_schedule_category(cn));        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem51ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        abreTelaInterna(new IntFrm_RegPerson(cn));
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void mnuPrazos3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPrazos3ActionPerformed
        abreTelaInterna(new IntFrm_RegDepartment(cn));        // TODO add your handling code here:
    }//GEN-LAST:event_mnuPrazos3ActionPerformed

    private void mnuPrazos4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPrazos4ActionPerformed
        abreTelaInterna(new IntFrm_TaxStatements(cn));        // TODO add your handling code here:
    }//GEN-LAST:event_mnuPrazos4ActionPerformed

    private void jMenuItem52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem52ActionPerformed
        abreTelaInterna(new IntFrm_DevolCota(cn));        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem52ActionPerformed

    private void jMenuItem53ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem53ActionPerformed
        new util.ExportLancAntec(cn);
    }//GEN-LAST:event_jMenuItem53ActionPerformed

    private void jMenuItem54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem54ActionPerformed
        abreTelaInterna(new finReceitaFrete.IntFrm_ReceitaFrete(cn));
    }//GEN-LAST:event_jMenuItem54ActionPerformed

    private void mnuPrazos5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPrazos5ActionPerformed
        abreTelaInterna(new IntFrm_PlanoReferencial());
    }//GEN-LAST:event_mnuPrazos5ActionPerformed

    private void jMenuItem55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem55ActionPerformed
        abreTelaInterna(new IntFrm_CadBens(cn));        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem55ActionPerformed

    private void jMenuItem56ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem56ActionPerformed
        abreTelaInterna(new IntFrm_Financ_Garantias(cn));        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem56ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        new TelaPrincipal().setVisible(true);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JDesktopPane jAreaDeTrabalho;
    private javax.swing.JMenu jArquivo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JMenuItem jEmpresa;
    private javax.swing.JMenuItem jEmpresa1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jManutencao;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem28;
    private javax.swing.JMenuItem jMenuItem29;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem30;
    private javax.swing.JMenuItem jMenuItem31;
    private javax.swing.JMenuItem jMenuItem32;
    private javax.swing.JMenuItem jMenuItem33;
    private javax.swing.JMenuItem jMenuItem34;
    private javax.swing.JMenuItem jMenuItem35;
    private javax.swing.JMenuItem jMenuItem36;
    private javax.swing.JMenuItem jMenuItem37;
    private javax.swing.JMenuItem jMenuItem38;
    private javax.swing.JMenuItem jMenuItem39;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem40;
    private javax.swing.JMenuItem jMenuItem41;
    private javax.swing.JMenuItem jMenuItem42;
    private javax.swing.JMenuItem jMenuItem43;
    private javax.swing.JMenuItem jMenuItem44;
    private javax.swing.JMenuItem jMenuItem45;
    private javax.swing.JMenuItem jMenuItem46;
    private javax.swing.JMenuItem jMenuItem47;
    private javax.swing.JMenuItem jMenuItem48;
    private javax.swing.JMenuItem jMenuItem49;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem50;
    private javax.swing.JMenuItem jMenuItem51;
    private javax.swing.JMenuItem jMenuItem52;
    private javax.swing.JMenuItem jMenuItem53;
    private javax.swing.JMenuItem jMenuItem54;
    private javax.swing.JMenuItem jMenuItem55;
    private javax.swing.JMenuItem jMenuItem56;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenu jRelatorios;
    private javax.swing.JMenuItem jSair;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JMenu jSobre;
    private javax.swing.JMenu jSobre1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTxtBdFb;
    private javax.swing.JTextField jTxtBdMySQL;
    private javax.swing.JMenuItem mnuAtividades;
    private javax.swing.JMenuItem mnuPrazos;
    private javax.swing.JMenuItem mnuPrazos1;
    private javax.swing.JMenuItem mnuPrazos2;
    private javax.swing.JMenuItem mnuPrazos3;
    private javax.swing.JMenuItem mnuPrazos4;
    private javax.swing.JMenuItem mnuPrazos5;
    // End of variables declaration//GEN-END:variables

    private void centralizaForm(JInternalFrame frame) {
        Dimension desktopSize = jAreaDeTrabalho.getSize();
        Dimension jInternalFrameSize = frame.getSize();
        frame.setLocation((desktopSize.width - jInternalFrameSize.width) / 2,
                (desktopSize.height - jInternalFrameSize.height) / 2);
    }

    /**
     * Define se entrará apontado para banco produção ou teste. Le o arquivo
     * Default.properties e verifica qual é o arquivo de configurações que está
     * sendo informado. Então, aponta este arquivo nas configurações da conexão.
     * Na tela inicial, retorna com a informação 'PRODUÇÃO' ou 'TESTE'.
     */
    public void defineBD() {
        try {
            FileInputStream file = new FileInputStream(arquivo);
            props.load(file);
            
            if ("mysql.properties".equals(props.getProperty("bd_mysql_default"))) {
                ConexaoMySQL.arquivo = "mysql.properties";
                jTxtBdMySQL.setText("PRODUÇÃO");
            } else {
                ConexaoMySQL.arquivo = "mysqlcasa.properties";
                jTxtBdMySQL.setText("TESTE");
            }
            if ("fb.properties".equals(props.getProperty("bd_fb_default"))) {
                ConexaoFB.arquivo = "fb.properties";
                jTxtBdFb.setText("PRODUÇÃO");
            } else {
                ConexaoFB.arquivo = "fbcasa.properties";
                jTxtBdFb.setText("TESTE");
            }
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Não foi possível encontrar o arquivo Default: " + ex);
        }
    }
    
    private void setPosicao(JInternalFrame x) {
        Dimension d = x.getDesktopPane().getSize();
        x.setLocation((d.width - x.getSize().width) / 2, (d.height - x.getSize().height) / 2);
    }
    
    private void abreTelaInterna(JInternalFrame tela) {
        
        for (JInternalFrame internal : jAreaDeTrabalho.getAllFrames()) {
            
            if (internal.getClass().toString().equalsIgnoreCase(tela.getClass().toString())) {
                try {
                    internal.setSelected(true);
                } catch (Exception e) {
                    
                }
                return;
            }
            
        }
        
        try {
            //PREPARAÇÃO PARA RECEBER INSTRUÇÕES PARA NAO ABRIR VÁRIAS JANELAS
            if (false) {
                tela.setSelected(true);
            } else {
                tela.setVisible(true);
                jAreaDeTrabalho.add(tela);
                tela.setSelected(true);
                setPosicao(tela);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ops! Não foi possível abrir a tela '" + tela + "'. \nErro: " + e);
        }
    }
    
    public void setStatus(String msg, int bd) {
        switch (bd) {
            case 1:
                jTextField2.setText(msg);
                break;
            
            case 2:
                jTextField1.setText(msg);
                
                break;
        }
    }
    
}
