/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fidelizacao;

import conn.ConexaoFB;
import conn.ConexaoMySQL;
import tools.FiltrarTabela;
import tools.IntegraFinanceiro;
import tools.JNumberFormatField99;
import java.awt.event.KeyEvent;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author luiz.barcellos
 */
public class fidelizacao_lcto extends javax.swing.JInternalFrame {

    /**
     * Creates new form fidelizacao_lcto
     */
    private ConexaoMySQL cn;
    private final ConexaoFB cnfb = new ConexaoFB();
    private int var_consulta;
    private javax.swing.text.MaskFormatter data, safra;
    private DateFormat dateIn = new SimpleDateFormat("dd/MM/yyyy");
    private DateFormat dateOut = new SimpleDateFormat("yyyy/MM/dd");
    private DecimalFormat df = new DecimalFormat("#,##0.00");
    private IntegraFinanceiro integ;

    public fidelizacao_lcto(ConexaoMySQL conn) {
        try {
            data = new javax.swing.text.MaskFormatter("##/##/####");
            safra = new javax.swing.text.MaskFormatter("####/####");
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        initComponents();

        this.cn = conn;
        integ = new IntegraFinanceiro(conn, true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPesquisar = new javax.swing.JFrame();
        jPanel10 = new javax.swing.JPanel();
        jTxtPesquisa_Multi2 = new javax.swing.JTextField();
        jBtnConfirmar = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTblConsulta_Multi = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTxtId = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTxtIdPessoa = new javax.swing.JTextField();
        jTxtNomePessoa = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jTxtIdEstab = new javax.swing.JTextField();
        jTxtNomeEstab = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTxtData = new javax.swing.JFormattedTextField(data);
        jTxtVencimento = new javax.swing.JFormattedTextField(data);
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTxtObs = new javax.swing.JTextField();
        jTxtMovimentacao = new JNumberFormatField99(new DecimalFormat("#,##0.00"));
        jTxtBonificacao = new JNumberFormatField99(new DecimalFormat("#,##0.00"));
        jTxtSafra = new javax.swing.JFormattedTextField(safra);
        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jBtnExcluir = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jTxtContagem = new javax.swing.JTextField();

        jPesquisar.setTitle("Pesquisar");
        jPesquisar.setMinimumSize(new java.awt.Dimension(700, 400));

        jTxtPesquisa_Multi2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTxtPesquisa_Multi2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtPesquisa_Multi2KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxtPesquisa_Multi2KeyReleased(evt);
            }
        });

        jBtnConfirmar.setText("Adicionar");
        jBtnConfirmar.setEnabled(false);
        jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmarActionPerformed(evt);
            }
        });

        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        jTblConsulta_Multi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTblConsulta_Multi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTblConsulta_Multi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTblConsulta_MultiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTblConsulta_MultiMouseEntered(evt);
            }
        });
        jScrollPane4.setViewportView(jTblConsulta_Multi);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addGap(0, 453, Short.MAX_VALUE)
                        .addComponent(jBtnCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnConfirmar))
                    .addComponent(jTxtPesquisa_Multi2)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTxtPesquisa_Multi2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnConfirmar)
                    .addComponent(jBtnCancelar))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPesquisarLayout = new javax.swing.GroupLayout(jPesquisar.getContentPane());
        jPesquisar.getContentPane().setLayout(jPesquisarLayout);
        jPesquisarLayout.setHorizontalGroup(
            jPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPesquisarLayout.setVerticalGroup(
            jPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setClosable(true);
        setTitle("Pagamento de Fidelização Insumos");

        jLabel1.setText("Lançamento");

        jTxtId.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jButton1.setText("...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Produtor");

        jTxtIdPessoa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtIdPessoaFocusLost(evt);
            }
        });
        jTxtIdPessoa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtIdPessoaKeyPressed(evt);
            }
        });

        jTxtNomePessoa.setEnabled(false);

        jButton2.setText("...");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel11.setText("Estabelecimento");

        jTxtIdEstab.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtIdEstabFocusLost(evt);
            }
        });
        jTxtIdEstab.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtIdEstabKeyPressed(evt);
            }
        });

        jTxtNomeEstab.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTxtIdPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtNomePessoa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTxtId, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTxtIdEstab, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtNomeEstab))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel11)
                    .addComponent(jTxtIdEstab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtNomeEstab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTxtIdPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtNomePessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Financeiro"));

        jLabel3.setText("Data");

        jTxtData.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtDataKeyPressed(evt);
            }
        });

        jTxtVencimento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtVencimentoKeyPressed(evt);
            }
        });

        jLabel4.setText("Vencimento");

        jLabel5.setText("Movimentação");

        jLabel6.setText("Bonificação");

        jLabel7.setText("Segmento");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GRAOS", "INSUMOS" }));
        jComboBox1.setSelectedIndex(1);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "FEIJAO", "SOJA", "MILHO", "TRIGO" }));

        jLabel8.setText("Cultura");

        jLabel9.setText("Safra");

        jLabel10.setText("Observações");

        jTxtObs.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtObsKeyPressed(evt);
            }
        });

        jTxtMovimentacao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtMovimentacaoFocusLost(evt);
            }
        });

        jTxtSafra.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtSafraFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtData, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtMovimentacao, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtBonificacao, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtSafra))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtObs)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTxtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jTxtMovimentacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtBonificacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jTxtSafra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTxtObs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jButton3.setMnemonic('G');
        jButton3.setText("Gravar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jBtnExcluir.setMnemonic('X');
        jBtnExcluir.setText("Excluir");
        jBtnExcluir.setEnabled(false);
        jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirActionPerformed(evt);
            }
        });

        jButton5.setMnemonic('C');
        jButton5.setText("Cancelar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setMnemonic('L');
        jButton6.setText("Limpar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel12.setText("Contagem");

        jTxtContagem.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTxtContagem.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtContagem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton3)
            .addComponent(jBtnExcluir)
            .addComponent(jButton5)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton6)
                .addComponent(jLabel12)
                .addComponent(jTxtContagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        gravar();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirActionPerformed
        if (excluiRegistro()) {
            limpaCampos();
        } else {
            JOptionPane.showMessageDialog(null, "Dados não foram excluídos.");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnExcluirActionPerformed

    private void jTxtPesquisa_Multi2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtPesquisa_Multi2KeyReleased
        new FiltrarTabela(jTblConsulta_Multi, jTxtPesquisa_Multi2.getText());
    }//GEN-LAST:event_jTxtPesquisa_Multi2KeyReleased

    private void jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmarActionPerformed
        incluiPesquisa();
        jPesquisar.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jBtnConfirmarActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        jPesquisar.setVisible(false);        // TODO add your handling code here:
        jPesquisar.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jTblConsulta_MultiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblConsulta_MultiMouseClicked
        jBtnConfirmar.setEnabled(true);    // TODO add your handling code here:
    }//GEN-LAST:event_jTblConsulta_MultiMouseClicked

    private void jTblConsulta_MultiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblConsulta_MultiMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTblConsulta_MultiMouseEntered

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        var_consulta = 1;
        jPesquisar.setVisible(true);
        montaLista();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        var_consulta = 2;
        jPesquisar.setVisible(true);
        montaLista();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTxtMovimentacaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtMovimentacaoFocusLost
        boolean calculo;

        if ("0,00".equals(jTxtBonificacao.getText())) {

            calculo = true;
        } else {
            calculo = false;
        }

        if (calculo) {
            Double movimentacao = Double.parseDouble(jTxtMovimentacao.getText().replace(".", "").replace(",", "."));
            System.out.println("Movimentação = " + movimentacao);
            Double bonificacao = movimentacao * 0.01;
            System.out.println("Bonificação = " + bonificacao);

            jTxtBonificacao.setText(df.format(bonificacao));

        }
    }//GEN-LAST:event_jTxtMovimentacaoFocusLost

    private void jTxtIdPessoaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtIdPessoaFocusLost
        String idPessoa = jTxtIdPessoa.getText();

        jTxtNomePessoa.setText("");

        if (!"".equals(idPessoa)) {
            var_consulta = 22;
            incluiPesquisa();
        }
    }//GEN-LAST:event_jTxtIdPessoaFocusLost

    private void jTxtIdPessoaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtIdPessoaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_F2) {
            var_consulta = 2;
            jPesquisar.setVisible(true);
            montaLista();
        }
    }//GEN-LAST:event_jTxtIdPessoaKeyPressed

    private void jTxtIdEstabFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtIdEstabFocusLost
        String idEstab = jTxtIdEstab.getText();

        jTxtNomeEstab.setText("");

        if (!"".equals(idEstab)) {

            var_consulta = 55;
            incluiPesquisa();
        }
    }//GEN-LAST:event_jTxtIdEstabFocusLost

    private void jTxtIdEstabKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtIdEstabKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_F2) {
            var_consulta = 5;
            jPesquisar.setVisible(true);
            montaLista();
        }
    }//GEN-LAST:event_jTxtIdEstabKeyPressed

    private void jTxtDataKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtDataKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            jTxtData.setText(dateIn.format(new Date()));
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtDataKeyPressed

    private void jTxtVencimentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtVencimentoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            jTxtData.setText(dateIn.format(new Date()));
        }
    }//GEN-LAST:event_jTxtVencimentoKeyPressed

    private void jTxtPesquisa_Multi2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtPesquisa_Multi2KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTblConsulta_Multi.setRowSelectionInterval(0, 0);
            incluiPesquisa();
            jPesquisar.setVisible(false);
        }
    }//GEN-LAST:event_jTxtPesquisa_Multi2KeyPressed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        limpaCampos();
        jTxtData.setValue(null);        // TODO add your handling code here:
        jTxtVencimento.setValue(null);        // TODO add your handling code here:
        jTxtSafra.setValue(null);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTxtSafraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtSafraFocusLost
        somaLancamentos();
    }//GEN-LAST:event_jTxtSafraFocusLost

    private void jTxtObsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtObsKeyPressed
if(evt.getKeyCode() == KeyEvent.VK_ENTER){
    gravaDados();
}
    }//GEN-LAST:event_jTxtObsKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnConfirmar;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JFrame jPesquisar;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTblConsulta_Multi;
    private javax.swing.JTextField jTxtBonificacao;
    private javax.swing.JTextField jTxtContagem;
    private javax.swing.JFormattedTextField jTxtData;
    private javax.swing.JTextField jTxtId;
    private javax.swing.JTextField jTxtIdEstab;
    private javax.swing.JTextField jTxtIdPessoa;
    private javax.swing.JTextField jTxtMovimentacao;
    private javax.swing.JTextField jTxtNomeEstab;
    private javax.swing.JTextField jTxtNomePessoa;
    private javax.swing.JTextField jTxtObs;
    private javax.swing.JTextField jTxtPesquisa_Multi2;
    private javax.swing.JFormattedTextField jTxtSafra;
    private javax.swing.JFormattedTextField jTxtVencimento;
    // End of variables declaration//GEN-END:variables

    private boolean gravaDados() {

        boolean resposta = false;

        String sql = "";
        String id = jTxtId.getText();
        String idPessoa = jTxtIdPessoa.getText();
        String nomePessoa = jTxtNomePessoa.getText();
        String data;
        String vencimento;
        String movimentacao = jTxtMovimentacao.getText().replace(".", "").replace(",", ".");
        String bonificacao = jTxtBonificacao.getText().replace(".", "").replace(",", ".");
        String segmento = jComboBox1.getSelectedItem().toString();
        String cultura = jComboBox2.getSelectedItem().toString();
        String safra = jTxtSafra.getText();
        String obs = jTxtObs.getText();
        String idEstab = jTxtIdEstab.getText();

        gravando:
        try {

            if ("".equals(jTxtNomePessoa.getText())) {
                jTxtIdPessoa.grabFocus();
                throw new UnsupportedOperationException("Selecione uma pessoa para continuar.");
            } else if ("  /  /    ".equals(jTxtData.getText())) {
                jTxtData.grabFocus();
                throw new UnsupportedOperationException("Informe uma data para continuar.");
            } else if ("  /  /    ".equals(jTxtVencimento.getText())) {
                jTxtVencimento.grabFocus();
                throw new UnsupportedOperationException("Informe um vencimento para continuar.");
            } else if ("0,00".equals(jTxtMovimentacao.getText())) {
                jTxtMovimentacao.grabFocus();
                throw new UnsupportedOperationException("Informe um valor para movimentação para continuar.");
            } else if ("0,00".equals(jTxtBonificacao.getText())) {
                jTxtBonificacao.grabFocus();
                throw new UnsupportedOperationException("Informe um valor para bonificação para continuar.");
            } else if ("    /    ".equals(jTxtSafra.getText())) {
                jTxtSafra.grabFocus();
                throw new UnsupportedOperationException("Informe uma safra para continuar.");
            } else if ("".equals(jTxtNomeEstab.getText())) {
                jTxtIdEstab.grabFocus();
                throw new UnsupportedOperationException("Informe um estabelecimento para continuar.");
            }

            data = dateOut.format(dateIn.parse(jTxtData.getText()));
            vencimento = dateOut.format(dateIn.parse(jTxtVencimento.getText()));

            if (!"".equals(jTxtId.getText()) && jBtnExcluir.isEnabled() == false) {

                sql = "INSERT INTO fidelizacao (lancamento, produtor, nome, "
                        + "segmento, cultura, movimentacao, bonificacao, "
                        + "data, vencimento,  obs, safra) VALUES ('" + id + "',"
                        + "'" + idPessoa + "','" + nomePessoa + "',"
                        + "'" + segmento + "','" + cultura + "','" + movimentacao + "',"
                        + "'" + bonificacao + "','" + data + "','" + vencimento + "',"
                        + "'" + obs + "','" + safra + "')";
            } else if (!"".equals(jTxtId.getText()) && jBtnExcluir.isEnabled()) {

                sql = "UPDATE fidelizacao SET produtor = '" + idPessoa + "',"
                        + "nome = '" + nomePessoa + "', segmento = '" + segmento + "',"
                        + "cultura = '" + cultura + "', movimentacao = '" + movimentacao + "',"
                        + "bonificacao = '" + bonificacao + "', data = '" + data + "',"
                        + "vencimento = '" + vencimento + "', obs = '" + obs + "',"
                        + "safra = '" + safra + "' WHERE lancamento = '" + id + "';";

            } else {

                String historico = "Pagamento bonificacao INSUMOS " + cultura + " para " + nomePessoa + " referente safra " + safra + ".";

                if (integ.integraFinanceiro(id, "67", idPessoa, jTxtData.getText().replace("/", ""),
                        dateIn.parse(jTxtData.getText()), dateIn.parse(jTxtVencimento.getText()),
                        "36627", bonificacao, historico, null, historico, false, idEstab, false)) {

                    jTxtId.setText(integ.getCodigo() + "");

                    resposta = gravaDados();
                }

            }

            if (cn.iniciarTransacao() && !"".equals(jTxtId.getText()) && !"".equals(sql)) {
                resposta = cn.executeAtualizacao(sql);
                if (resposta) {
                    integ.confirmaIntegracao();
                } else {
                    integ.desfazIntegracao();
                    jTxtId.setText("");
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());

        } finally {
            cn.finalizarTransacao();
        }

        return resposta;
    }

    private boolean excluiRegistro() {

        boolean resposta = false;

        String id = jTxtId.getText();

        String sql = "DELETE FROM fidelizacao WHERE lancamento = '" + id + "';";

        if (cn.iniciarTransacao()) {
            try {
                resposta = cn.executeAtualizacao(sql);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            } finally {
                cn.finalizarTransacao();
            }
        }

        return resposta;
    }

    private void incluiPesquisa() {
        int linha = jTblConsulta_Multi.getSelectedRow();
        String sql;

        switch (var_consulta) {

            case 1:

                jTxtId.setText(jTblConsulta_Multi.getValueAt(linha, 0).toString());

            case 11:

                String id = jTxtId.getText();

                sql = "SELECT * FROM fidelizacao WHERE lancamento = '" + id + "';";

                if (cn.iniciarTransacao()) {
                    try {
                        cn.executeConsulta(sql);
                        while (cn.rs.next()) {
                            jTxtIdPessoa.setText(cn.rs.getString("produtor"));
                            jTxtNomePessoa.setText(cn.rs.getString("nome"));
                            jTxtData.setValue(dateIn.format(cn.rs.getDate("data")));
                            jTxtVencimento.setValue(dateIn.format(cn.rs.getDate("vencimento")));
                            jTxtMovimentacao.setText(df.format(cn.rs.getDouble("movimentacao")));
                            jTxtBonificacao.setText(df.format(cn.rs.getDouble("bonificacao")));
                            jComboBox1.setSelectedItem(cn.rs.getString("segmento").toString());
                            jComboBox2.setSelectedItem(cn.rs.getString("cultura").toString());
                            jTxtSafra.setText(cn.rs.getString("safra"));
                            jTxtObs.setText(cn.rs.getString("obs"));
                        }

                        jBtnExcluir.setEnabled(true);

                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    } finally {
                        cn.finalizarTransacao();
                    }
                }

                break;

            case 2:
                jTxtIdPessoa.setText(jTblConsulta_Multi.getValueAt(linha, 0).toString());
                jTxtNomePessoa.setText(jTblConsulta_Multi.getValueAt(linha, 1).toString());
                break;
            case 22:

                String idPessoa = jTxtIdPessoa.getText();

                sql = "SELECT codigo, nome FROM cad_terceiros WHERE empresa = 1 and codigo = '" + idPessoa + "';";

                if (cnfb.conecta()) {
                    try {
                        cnfb.executeConsulta(sql);
                        while (cnfb.rs.next()) {
                            jTxtNomePessoa.setText(cnfb.rs.getString("nome"));
                        }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    } finally {
                        cnfb.desconecta();
                    }
                }

                break;

            case 55:

                String idEstab = jTxtIdEstab.getText();

                sql = "SELECT codigo, nome FROM cad_estabelecimentos WHERE empresa = 1 and codigo = '" + idEstab + "';";

                if (cnfb.conecta()) {
                    try {
                        cnfb.executeConsulta(sql);
                        while (cnfb.rs.next()) {
                            jTxtNomeEstab.setText(cnfb.rs.getString("nome"));
                        }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    } finally {
                        cnfb.desconecta();
                    }
                }

                break;
        }

        jTxtPesquisa_Multi2.setText("");
    }

    private void montaLista() {

        String sql;

        DefaultTableModel lista = (DefaultTableModel) jTblConsulta_Multi.getModel();

        lista.setRowCount(0);
        lista.setColumnCount(0);

        switch (var_consulta) {
            case 1:

                lista.addColumn("Lançamento");
                lista.addColumn("Produtor");
                lista.addColumn("Segmento");
                lista.addColumn("Cultura");
                lista.addColumn("Valor");
                jTblConsulta_Multi.getColumnModel().getColumn(0).setMaxWidth(80);
                jTblConsulta_Multi.getColumnModel().getColumn(0).setMinWidth(80);
                jTblConsulta_Multi.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(80);
                jTblConsulta_Multi.getTableHeader().getColumnModel().getColumn(0).setMinWidth(80);
                jTblConsulta_Multi.getColumnModel().getColumn(2).setMaxWidth(80);
                jTblConsulta_Multi.getColumnModel().getColumn(2).setMinWidth(80);
                jTblConsulta_Multi.getTableHeader().getColumnModel().getColumn(2).setMaxWidth(80);
                jTblConsulta_Multi.getTableHeader().getColumnModel().getColumn(2).setMinWidth(80);
                jTblConsulta_Multi.getColumnModel().getColumn(3).setMaxWidth(80);
                jTblConsulta_Multi.getColumnModel().getColumn(3).setMinWidth(80);
                jTblConsulta_Multi.getTableHeader().getColumnModel().getColumn(3).setMaxWidth(80);
                jTblConsulta_Multi.getTableHeader().getColumnModel().getColumn(3).setMinWidth(80);
                jTblConsulta_Multi.getColumnModel().getColumn(4).setMaxWidth(80);
                jTblConsulta_Multi.getColumnModel().getColumn(4).setMinWidth(80);
                jTblConsulta_Multi.getTableHeader().getColumnModel().getColumn(4).setMaxWidth(80);
                jTblConsulta_Multi.getTableHeader().getColumnModel().getColumn(4).setMinWidth(80);

                sql = "SELECT * FROM fidelizacao ORDER BY nome;";

                if (cn.iniciarTransacao()) {
                    try {
                        cn.executeConsulta(sql);
                        while (cn.rs.next()) {
                            lista.addRow(new String[]{
                                cn.rs.getString("lancamento"),
                                cn.rs.getString("nome"),
                                cn.rs.getString("segmento"),
                                cn.rs.getString("cultura"),
                                df.format(cn.rs.getDouble("bonificacao"))
                            });
                        }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    } finally {
                        cn.finalizarTransacao();
                    }

                }

                break;

            case 2:

                lista.addColumn("Código");
                lista.addColumn("Nome");

                jTblConsulta_Multi.getColumnModel().getColumn(0).setMaxWidth(40);
                jTblConsulta_Multi.getColumnModel().getColumn(0).setMinWidth(40);
                jTblConsulta_Multi.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(40);
                jTblConsulta_Multi.getTableHeader().getColumnModel().getColumn(0).setMinWidth(40);

                sql = "SELECT a.codigo, a.nome, a.ativo "
                        + "FROM cad_terceiros_cooperados b "
                        + "INNER JOIN cad_terceiros a ON (b.empresa = a.empresa and b.codigo = a.codigo and a.ativo = 'A') "
                        + "WHERE b.empresa = 1 "
                        + "ORDER BY a.nome;";

                if (cnfb.conecta()) {
                    try {
                        cnfb.executeConsulta(sql);
                        while (cnfb.rs.next()) {
                            lista.addRow(new String[]{
                                cnfb.rs.getString("codigo"),
                                cnfb.rs.getString("nome")
                            });
                        }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    } finally {
                        cnfb.desconecta();
                    }

                }

                break;

            case 5:
                lista.addColumn("Código");
                lista.addColumn("Nome");

                jTblConsulta_Multi.getColumnModel().getColumn(0).setMaxWidth(40);
                jTblConsulta_Multi.getColumnModel().getColumn(0).setMinWidth(40);
                jTblConsulta_Multi.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(40);
                jTblConsulta_Multi.getTableHeader().getColumnModel().getColumn(0).setMinWidth(40);

                sql = "SELECT a.codigo, a.nome "
                        + "FROM cad_estabelecimentos a "
                        + "WHERE a.empresa = 1 and a.ativo != 'N' "
                        + "ORDER BY a.nome;";

                if (cnfb.conecta()) {
                    try {
                        cnfb.executeConsulta(sql);
                        while (cnfb.rs.next()) {
                            lista.addRow(new String[]{
                                cnfb.rs.getString("codigo"),
                                cnfb.rs.getString("nome")
                            });
                        }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    } finally {
                        cnfb.desconecta();
                    }

                }
                break;
        }

    }

    private void limpaCampos() {
        jTxtId.setText("");
        jTxtIdPessoa.setText("");
        jTxtNomePessoa.setText("");
        //jTxtData.setValue(null);
        //jTxtVencimento.setValue(null);
        jTxtMovimentacao.setText("0,00");
        jTxtBonificacao.setText("0,00");
        //jTxtSafra.setValue(null);
        jComboBox1.setSelectedIndex(1);
        jComboBox2.setSelectedIndex(0);
        jTxtObs.setText("");

        jBtnExcluir.setEnabled(false);
    }

    private void somaLancamentos() {
        String sql = "SELECT count(*) as qtd "
                + "FROM fidelizacao "
                + "WHERE safra = '" + jTxtSafra.getText() + "';";
        if (cn.iniciarTransacao()) {
            try {
                cn.executeConsulta(sql);
                while (cn.rs.next()) {
                    jTxtContagem.setText(cn.rs.getString("qtd"));
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            } finally {
                cn.finalizarTransacao();
            }
        }

    }

    private void gravar() {
        if (gravaDados()) {

            limpaCampos();
            jTxtIdPessoa.grabFocus();

        } else {
            JOptionPane.showMessageDialog(null, "Os dados não foram gravados.");
        }
    }
}
